/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiApplicationsResponsesApplicationsV2Response,
  ApiSystemString,
  GetApiV2ApplicationsParams
} from '../model';

import { ogmMutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getApiV2Applications = (
    params?: GetApiV2ApplicationsParams,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiApplicationsResponsesApplicationsV2Response>(
      {url: `/api/v2/applications`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiV2ApplicationsQueryKey = (params?: GetApiV2ApplicationsParams,) => {
    return [
    `/api/v2/applications`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV2ApplicationsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2Applications>>, TError = unknown>(params?: GetApiV2ApplicationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2Applications>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2ApplicationsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2Applications>>> = ({ signal }) => getApiV2Applications(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV2Applications>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2ApplicationsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2Applications>>>
export type GetApiV2ApplicationsQueryError = unknown


export function useGetApiV2Applications<TData = Awaited<ReturnType<typeof getApiV2Applications>>, TError = unknown>(
 params: undefined |  GetApiV2ApplicationsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2Applications>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2Applications>>,
          TError,
          Awaited<ReturnType<typeof getApiV2Applications>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2Applications<TData = Awaited<ReturnType<typeof getApiV2Applications>>, TError = unknown>(
 params?: GetApiV2ApplicationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2Applications>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2Applications>>,
          TError,
          Awaited<ReturnType<typeof getApiV2Applications>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2Applications<TData = Awaited<ReturnType<typeof getApiV2Applications>>, TError = unknown>(
 params?: GetApiV2ApplicationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2Applications>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2Applications<TData = Awaited<ReturnType<typeof getApiV2Applications>>, TError = unknown>(
 params?: GetApiV2ApplicationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2Applications>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2ApplicationsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiV2ApplicationsHealthcheck = (

 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiSystemString>(
      {url: `/api/v2/applications/healthcheck`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV2ApplicationsHealthcheckQueryKey = () => {
    return [
    `/api/v2/applications/healthcheck`
    ] as const;
    }


export const getGetApiV2ApplicationsHealthcheckQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheck>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheck>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2ApplicationsHealthcheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheck>>> = ({ signal }) => getApiV2ApplicationsHealthcheck(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheck>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2ApplicationsHealthcheckQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheck>>>
export type GetApiV2ApplicationsHealthcheckQueryError = unknown


export function useGetApiV2ApplicationsHealthcheck<TData = Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheck>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheck>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2ApplicationsHealthcheck<TData = Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheck>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2ApplicationsHealthcheck<TData = Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheck>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2ApplicationsHealthcheck<TData = Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheck>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2ApplicationsHealthcheckQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiV2ApplicationsHealthcheckWithJwt = (

 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiSystemString>(
      {url: `/api/v2/applications/healthcheck-with-jwt`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV2ApplicationsHealthcheckWithJwtQueryKey = () => {
    return [
    `/api/v2/applications/healthcheck-with-jwt`
    ] as const;
    }


export const getGetApiV2ApplicationsHealthcheckWithJwtQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheckWithJwt>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheckWithJwt>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2ApplicationsHealthcheckWithJwtQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheckWithJwt>>> = ({ signal }) => getApiV2ApplicationsHealthcheckWithJwt(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheckWithJwt>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2ApplicationsHealthcheckWithJwtQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheckWithJwt>>>
export type GetApiV2ApplicationsHealthcheckWithJwtQueryError = unknown


export function useGetApiV2ApplicationsHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheckWithJwt>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheckWithJwt>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheckWithJwt>>,
          TError,
          Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheckWithJwt>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2ApplicationsHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheckWithJwt>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheckWithJwt>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheckWithJwt>>,
          TError,
          Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheckWithJwt>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2ApplicationsHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheckWithJwt>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheckWithJwt>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2ApplicationsHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheckWithJwt>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2ApplicationsHealthcheckWithJwt>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2ApplicationsHealthcheckWithJwtQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






