/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GetApiSettingsGetParams,
  PostApiSettingsSetParams,
  SettingResponseApiResponse,
  StringApiResponse,
} from "../model";

import { ogmMutator } from "../../mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type getApiSettingsGetResponse200TextPlain = {
  data: SettingResponseApiResponse;
  status: 200;
};

export type getApiSettingsGetResponse200ApplicationJson = {
  data: SettingResponseApiResponse;
  status: 200;
};

export type getApiSettingsGetResponse200TextJson = {
  data: SettingResponseApiResponse;
  status: 200;
};

export type getApiSettingsGetResponseSuccess = (
  | getApiSettingsGetResponse200TextPlain
  | getApiSettingsGetResponse200ApplicationJson
  | getApiSettingsGetResponse200TextJson
) & {
  headers: Headers;
};
export type getApiSettingsGetResponse = getApiSettingsGetResponseSuccess;

export const getGetApiSettingsGetUrl = (params: GetApiSettingsGetParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/settings/get?${stringifiedParams}`
    : `/api/settings/get`;
};

export const getApiSettingsGet = async (
  params: GetApiSettingsGetParams,
  options?: RequestInit,
): Promise<getApiSettingsGetResponse> => {
  return ogmMutator<getApiSettingsGetResponse>(
    getGetApiSettingsGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiSettingsGetQueryKey = (
  params?: GetApiSettingsGetParams,
) => {
  return [`/api/settings/get`, ...(params ? [params] : [])] as const;
};

export const getGetApiSettingsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiSettingsGet>>,
  TError = unknown,
>(
  params: GetApiSettingsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiSettingsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiSettingsGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiSettingsGet>>
  > = ({ signal }) => getApiSettingsGet(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiSettingsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiSettingsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiSettingsGet>>
>;
export type GetApiSettingsGetQueryError = unknown;

export function useGetApiSettingsGet<
  TData = Awaited<ReturnType<typeof getApiSettingsGet>>,
  TError = unknown,
>(
  params: GetApiSettingsGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiSettingsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSettingsGet>>,
          TError,
          Awaited<ReturnType<typeof getApiSettingsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiSettingsGet<
  TData = Awaited<ReturnType<typeof getApiSettingsGet>>,
  TError = unknown,
>(
  params: GetApiSettingsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiSettingsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSettingsGet>>,
          TError,
          Awaited<ReturnType<typeof getApiSettingsGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiSettingsGet<
  TData = Awaited<ReturnType<typeof getApiSettingsGet>>,
  TError = unknown,
>(
  params: GetApiSettingsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiSettingsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiSettingsGet<
  TData = Awaited<ReturnType<typeof getApiSettingsGet>>,
  TError = unknown,
>(
  params: GetApiSettingsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiSettingsGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiSettingsGetQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type postApiSettingsSetResponse200TextPlain = {
  data: SettingResponseApiResponse;
  status: 200;
};

export type postApiSettingsSetResponse200ApplicationJson = {
  data: SettingResponseApiResponse;
  status: 200;
};

export type postApiSettingsSetResponse200TextJson = {
  data: SettingResponseApiResponse;
  status: 200;
};

export type postApiSettingsSetResponseSuccess = (
  | postApiSettingsSetResponse200TextPlain
  | postApiSettingsSetResponse200ApplicationJson
  | postApiSettingsSetResponse200TextJson
) & {
  headers: Headers;
};
export type postApiSettingsSetResponse = postApiSettingsSetResponseSuccess;

export const getPostApiSettingsSetUrl = (params: PostApiSettingsSetParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/settings/set?${stringifiedParams}`
    : `/api/settings/set`;
};

export const postApiSettingsSet = async (
  params: PostApiSettingsSetParams,
  options?: RequestInit,
): Promise<postApiSettingsSetResponse> => {
  return ogmMutator<postApiSettingsSetResponse>(
    getPostApiSettingsSetUrl(params),
    {
      ...options,
      method: "POST",
    },
  );
};

export const getPostApiSettingsSetMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiSettingsSet>>,
    TError,
    { params: PostApiSettingsSetParams },
    TContext
  >;
  request?: SecondParameter<typeof ogmMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiSettingsSet>>,
  TError,
  { params: PostApiSettingsSetParams },
  TContext
> => {
  const mutationKey = ["postApiSettingsSet"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiSettingsSet>>,
    { params: PostApiSettingsSetParams }
  > = (props) => {
    const { params } = props ?? {};

    return postApiSettingsSet(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiSettingsSetMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiSettingsSet>>
>;

export type PostApiSettingsSetMutationError = unknown;

export const usePostApiSettingsSet = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiSettingsSet>>,
      TError,
      { params: PostApiSettingsSetParams },
      TContext
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiSettingsSet>>,
  TError,
  { params: PostApiSettingsSetParams },
  TContext
> => {
  return useMutation(
    getPostApiSettingsSetMutationOptions(options),
    queryClient,
  );
};
export type getApiSettingsHealthcheckResponse200TextPlain = {
  data: StringApiResponse;
  status: 200;
};

export type getApiSettingsHealthcheckResponse200ApplicationJson = {
  data: StringApiResponse;
  status: 200;
};

export type getApiSettingsHealthcheckResponse200TextJson = {
  data: StringApiResponse;
  status: 200;
};

export type getApiSettingsHealthcheckResponseSuccess = (
  | getApiSettingsHealthcheckResponse200TextPlain
  | getApiSettingsHealthcheckResponse200ApplicationJson
  | getApiSettingsHealthcheckResponse200TextJson
) & {
  headers: Headers;
};
export type getApiSettingsHealthcheckResponse =
  getApiSettingsHealthcheckResponseSuccess;

export const getGetApiSettingsHealthcheckUrl = () => {
  return `/api/settings/healthcheck`;
};

export const getApiSettingsHealthcheck = async (
  options?: RequestInit,
): Promise<getApiSettingsHealthcheckResponse> => {
  return ogmMutator<getApiSettingsHealthcheckResponse>(
    getGetApiSettingsHealthcheckUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiSettingsHealthcheckQueryKey = () => {
  return [`/api/settings/healthcheck`] as const;
};

export const getGetApiSettingsHealthcheckQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiSettingsHealthcheck>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiSettingsHealthcheck>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof ogmMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiSettingsHealthcheckQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiSettingsHealthcheck>>
  > = ({ signal }) => getApiSettingsHealthcheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiSettingsHealthcheck>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiSettingsHealthcheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiSettingsHealthcheck>>
>;
export type GetApiSettingsHealthcheckQueryError = unknown;

export function useGetApiSettingsHealthcheck<
  TData = Awaited<ReturnType<typeof getApiSettingsHealthcheck>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiSettingsHealthcheck>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSettingsHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiSettingsHealthcheck>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiSettingsHealthcheck<
  TData = Awaited<ReturnType<typeof getApiSettingsHealthcheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiSettingsHealthcheck>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSettingsHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiSettingsHealthcheck>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiSettingsHealthcheck<
  TData = Awaited<ReturnType<typeof getApiSettingsHealthcheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiSettingsHealthcheck>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiSettingsHealthcheck<
  TData = Awaited<ReturnType<typeof getApiSettingsHealthcheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiSettingsHealthcheck>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiSettingsHealthcheckQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type getApiSettingsHealthcheckWithJwtResponse200TextPlain = {
  data: StringApiResponse;
  status: 200;
};

export type getApiSettingsHealthcheckWithJwtResponse200ApplicationJson = {
  data: StringApiResponse;
  status: 200;
};

export type getApiSettingsHealthcheckWithJwtResponse200TextJson = {
  data: StringApiResponse;
  status: 200;
};

export type getApiSettingsHealthcheckWithJwtResponseSuccess = (
  | getApiSettingsHealthcheckWithJwtResponse200TextPlain
  | getApiSettingsHealthcheckWithJwtResponse200ApplicationJson
  | getApiSettingsHealthcheckWithJwtResponse200TextJson
) & {
  headers: Headers;
};
export type getApiSettingsHealthcheckWithJwtResponse =
  getApiSettingsHealthcheckWithJwtResponseSuccess;

export const getGetApiSettingsHealthcheckWithJwtUrl = () => {
  return `/api/settings/healthcheck-with-jwt`;
};

export const getApiSettingsHealthcheckWithJwt = async (
  options?: RequestInit,
): Promise<getApiSettingsHealthcheckWithJwtResponse> => {
  return ogmMutator<getApiSettingsHealthcheckWithJwtResponse>(
    getGetApiSettingsHealthcheckWithJwtUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiSettingsHealthcheckWithJwtQueryKey = () => {
  return [`/api/settings/healthcheck-with-jwt`] as const;
};

export const getGetApiSettingsHealthcheckWithJwtQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiSettingsHealthcheckWithJwt>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiSettingsHealthcheckWithJwt>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof ogmMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiSettingsHealthcheckWithJwtQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiSettingsHealthcheckWithJwt>>
  > = ({ signal }) =>
    getApiSettingsHealthcheckWithJwt({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiSettingsHealthcheckWithJwt>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiSettingsHealthcheckWithJwtQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiSettingsHealthcheckWithJwt>>
>;
export type GetApiSettingsHealthcheckWithJwtQueryError = unknown;

export function useGetApiSettingsHealthcheckWithJwt<
  TData = Awaited<ReturnType<typeof getApiSettingsHealthcheckWithJwt>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiSettingsHealthcheckWithJwt>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSettingsHealthcheckWithJwt>>,
          TError,
          Awaited<ReturnType<typeof getApiSettingsHealthcheckWithJwt>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiSettingsHealthcheckWithJwt<
  TData = Awaited<ReturnType<typeof getApiSettingsHealthcheckWithJwt>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiSettingsHealthcheckWithJwt>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSettingsHealthcheckWithJwt>>,
          TError,
          Awaited<ReturnType<typeof getApiSettingsHealthcheckWithJwt>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiSettingsHealthcheckWithJwt<
  TData = Awaited<ReturnType<typeof getApiSettingsHealthcheckWithJwt>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiSettingsHealthcheckWithJwt>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiSettingsHealthcheckWithJwt<
  TData = Awaited<ReturnType<typeof getApiSettingsHealthcheckWithJwt>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiSettingsHealthcheckWithJwt>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiSettingsHealthcheckWithJwtQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
