/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DataGate Monitor API
 * OpenAPI spec version: v1
 */

export interface AddServerRequest {
  /** @minLength 1 */
  serverName: string;
  isOnline?: boolean;
  isDefault?: boolean;
  /** @nullable */
  apiUrl?: string | null;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
  isEnableWss?: boolean;
  /** @nullable */
  quotaPlanIds?: number[] | null;
  /** @nullable */
  tagIds?: number[] | null;
}
