/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */

export interface AddServerRequest {
  /** @minLength 1 */
  serverName: string;
  isOnline?: boolean;
  isDefault?: boolean;
  /** @nullable */
  apiUrl?: string | null;
}
