/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { AuthResponsesAdminForgotPasswordResponse } from './authResponsesAdminForgotPasswordResponse';

export interface ApiAuthResponsesAdminForgotPasswordResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: AuthResponsesAdminForgotPasswordResponse;
}
