/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { AuthResponsesRefreshResponse } from './authResponsesRefreshResponse';

export interface ApiAuthResponsesRefreshResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: AuthResponsesRefreshResponse;
}
