/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { EmailBroadcastResponsesDtoEmailBroadcastTemplateDto } from './emailBroadcastResponsesDtoEmailBroadcastTemplateDto';

export interface ApiEmailBroadcastResponsesDtoEmailBroadcastTemplateDto {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: EmailBroadcastResponsesDtoEmailBroadcastTemplateDto;
}
