/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { GeoLiteResponsesGetVersionDatabaseResponse } from './geoLiteResponsesGetVersionDatabaseResponse';

export interface ApiGeoLiteResponsesGetVersionDatabaseResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: GeoLiteResponsesGetVersionDatabaseResponse;
}
