/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { OpenVpnFilesResponsesDownloadFileResponse } from './openVpnFilesResponsesDownloadFileResponse';

export interface ApiOpenVpnFilesResponsesDownloadFileResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: OpenVpnFilesResponsesDownloadFileResponse;
}
