/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { QuotaPlanAllowedServersResponsesQuotaPlanAllowedServerResponse } from "./quotaPlanAllowedServersResponsesQuotaPlanAllowedServerResponse";

export interface ApiQuotaPlanAllowedServersResponsesQuotaPlanAllowedServerResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: QuotaPlanAllowedServersResponsesQuotaPlanAllowedServerResponse;
}
