/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { QuotaPlansResponsesQuotaPlansV2Response } from './quotaPlansResponsesQuotaPlansV2Response';

export interface ApiQuotaPlansResponsesQuotaPlansV2Response {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: QuotaPlansResponsesQuotaPlansV2Response;
}
