/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { TelegramBotUserResponsesUserResponse } from './telegramBotUserResponsesUserResponse';

export interface ApiTelegramBotUserResponsesUserResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: TelegramBotUserResponsesUserResponse;
}
