/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { TelegramBotIncomingMessageLogResponsesGetByIdMessageResponse } from './telegramBotIncomingMessageLogResponsesGetByIdMessageResponse';

export interface ApiTelegramBotIncomingMessageLogResponsesGetByIdMessageResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: TelegramBotIncomingMessageLogResponsesGetByIdMessageResponse;
}
