/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { TelegramBotUserResponsesGetAllTelegramUsersResponse } from "./telegramBotUserResponsesGetAllTelegramUsersResponse";

export interface ApiTelegramBotUserResponsesGetAllTelegramUsersResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: TelegramBotUserResponsesGetAllTelegramUsersResponse;
}
