/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { TelegramBotIncomingMessageLogResponsesGetAllMessagesResponse } from "./telegramBotIncomingMessageLogResponsesGetAllMessagesResponse";

export interface ApiTelegramBotIncomingMessageLogResponsesGetAllMessagesResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: TelegramBotIncomingMessageLogResponsesGetAllMessagesResponse;
}
