/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { TagsResponsesTagsResponse } from './tagsResponsesTagsResponse';

export interface ApiTagsResponsesTagsResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: TagsResponsesTagsResponse;
}
