/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { UserVpnServerAccessRulesResponsesGetUserVpnServerAccessRulesByUserIdResponse } from './userVpnServerAccessRulesResponsesGetUserVpnServerAccessRulesByUserIdResponse';

export interface ApiUserVpnServerAccessRulesResponsesGetUserVpnServerAccessRulesByUserIdResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: UserVpnServerAccessRulesResponsesGetUserVpnServerAccessRulesByUserIdResponse;
}
