/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { UserResponsesAdminSetUserPasswordResponse } from './userResponsesAdminSetUserPasswordResponse';

export interface ApiUserResponsesAdminSetUserPasswordResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: UserResponsesAdminSetUserPasswordResponse;
}
