/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { VpnServerStatisticsResponsesGeoConnectionsResponse } from './vpnServerStatisticsResponsesGeoConnectionsResponse';

export interface ApiVpnServerStatisticsResponsesGeoConnectionsResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: VpnServerStatisticsResponsesGeoConnectionsResponse;
}
