/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { VpnServerClientsResponsesVpnClientsV2Response } from './vpnServerClientsResponsesVpnClientsV2Response';

export interface ApiVpnServerClientsResponsesVpnClientsV2Response {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: VpnServerClientsResponsesVpnClientsV2Response;
}
