/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { VpnServerConflogResponsesVpnServerConflogPageResponse } from "./vpnServerConflogResponsesVpnServerConflogPageResponse";

export interface ApiVpnServerConflogResponsesVpnServerConflogPageResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: VpnServerConflogResponsesVpnServerConflogPageResponse;
}
