/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { VpnDnsQueryResponsesVpnDnsQueryPageResponse } from './vpnDnsQueryResponsesVpnDnsQueryPageResponse';

export interface ApiVpnDnsQueryResponsesVpnDnsQueryPageResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: VpnDnsQueryResponsesVpnDnsQueryPageResponse;
}
