/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { XrayClientLinksResponsesXrayClientLinksWithTokensResponse } from './xrayClientLinksResponsesXrayClientLinksWithTokensResponse';

export interface ApiXrayClientLinksResponsesXrayClientLinksWithTokensResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: XrayClientLinksResponsesXrayClientLinksWithTokensResponse;
}
