/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */

export interface AuthResponsesRegisterUserResponse {
  userId?: number;
  /** @nullable */
  displayName?: string | null;
  /** @nullable */
  email?: string | null;
  hasDashboardAccess?: boolean;
}
