/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */

export interface AuthResponsesFreeTierAccessStatusResponse {
  isApplicable?: boolean;
  isCompliant?: boolean;
  isMergedAccount?: boolean;
  isChannelSubscribed?: boolean;
  isGracePeriod?: boolean;
  isLinkedToTelegram?: boolean;
  canRequestAccountLinkCode?: boolean;
  /** @nullable */
  activePlanName?: string | null;
  /** @nullable */
  requiredChannel?: string | null;
}
