/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */

export interface AuthRequestsCompleteTelegramAccountLinkFromAppRequest {
  /**
     * @minLength 4
     * @maxLength 32
     */
  code: string;
}
