/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */

export interface AuthRequestsTotpVerifyLoginRequest {
  /** @nullable */
  loginChallengeId?: string | null;
  /** @nullable */
  code?: string | null;
}
