/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */

export interface AuthRequestsConfirmEmailRequest {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  code?: string | null;
}
