/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */

export interface AuthResponsesGoogleLoginResponse {
  userId?: number;
  /** @nullable */
  displayName?: string | null;
  /** @nullable */
  email?: string | null;
  isNewUser?: boolean;
  /** @nullable */
  avatarUrl?: string | null;
  /** @nullable */
  token?: string | null;
  expiration?: string;
  /** @nullable */
  refreshToken?: string | null;
  /** @nullable */
  refreshExpiration?: string | null;
}
