/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */

export interface AvailabilityCheckRequestsUpdateAvailabilityCheckSettingsRequest {
  enabled?: boolean;
  /** @nullable */
  probeUrl?: string | null;
  /** Background probe interval in seconds (60–86400). */
  intervalSeconds?: number;
}
