/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DataGate Monitor API
 * OpenAPI spec version: v1
 */
import type { AverageSessionDurationsResponse } from "./averageSessionDurationsResponse";

export interface AverageSessionDurationsResponseApiResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: AverageSessionDurationsResponse;
}
