/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { BuildCertificateResponse } from "./buildCertificateResponse";

export interface BuildCertificateResponseApiResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: BuildCertificateResponse;
}
