/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DataGate Monitor API
 * OpenAPI spec version: v1
 */

export interface BuildCertificateRequest {
  /**
   * @minimum 1
   * @maximum 2147483647
   */
  vpnServerId: number;
  /** @minLength 1 */
  commonName: string;
  certExpireDays?: number;
}
