/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */

export interface EmailBroadcastRequestsSendAdminEmailRequest {
  /** @nullable */
  subject?: string | null;
  /** @nullable */
  htmlBody?: string | null;
  /** @nullable */
  targetUserId?: number | null;
}
