/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */

export type EnumsCertExpiryServerFetchStatus = typeof EnumsCertExpiryServerFetchStatus[keyof typeof EnumsCertExpiryServerFetchStatus];


export const EnumsCertExpiryServerFetchStatus = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
