/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { GeoConnectionDto } from "./geoConnectionDto";

export interface GeoConnectionsResponse {
  /** @nullable */
  geoConnections?: GeoConnectionDto[] | null;
}
