/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DataGate Monitor API
 * OpenAPI spec version: v1
 */

export type GetApiOpenVpnEventsGetByServerParams = {
  /**
   * @minimum 1
   * @maximum 2147483647
   */
  VpnServerId: number;
  /**
   * @minimum 1
   * @maximum 2147483647
   */
  Page?: number;
  /**
   * @minimum 1
   * @maximum 2147483647
   */
  PageSize?: number;
};
