/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { GetAllMessagesResponse } from "./getAllMessagesResponse";

export interface GetAllMessagesResponseApiResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: GetAllMessagesResponse;
}
