/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { GetGeoInfoResponse } from "./getGeoInfoResponse";

export interface GetGeoInfoResponseApiResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: GetGeoInfoResponse;
}
