/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DataGate Monitor API
 * OpenAPI spec version: v1
 */
import type { QuotaPlanAllowedServerDto } from "./quotaPlanAllowedServerDto";

export interface GetQuotaPlanAllowedServersByVpnServerIdResponse {
  /** @nullable */
  items?: QuotaPlanAllowedServerDto[] | null;
}
