/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { GetVersionDatabaseResponse } from "./getVersionDatabaseResponse";

export interface GetVersionDatabaseResponseApiResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: GetVersionDatabaseResponse;
}
