/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { IsExistTelegramUserLanguagePreferenceResponse } from "./isExistTelegramUserLanguagePreferenceResponse";

export interface IsExistTelegramUserLanguagePreferenceResponseApiResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: IsExistTelegramUserLanguagePreferenceResponse;
}
