/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { MessageDto } from "./messageDto";

export interface MessageDtoPagedResponse {
  page?: number;
  pageSize?: number;
  totalCount?: number;
  /** @nullable */
  items?: MessageDto[] | null;
  readonly totalPages?: number;
  readonly hasNext?: boolean;
  readonly hasPrev?: boolean;
}
