/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */

export interface MobileRequestsInstallationIdRequest {
  /** @minLength 1 */
  installationId: string;
}
