/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { EnumsNotificationSeverity } from './enumsNotificationSeverity';
import type { NotificationsResponsesNotificationDeliveryDto } from './notificationsResponsesNotificationDeliveryDto';

export interface NotificationsResponsesNotificationItemDto {
  id?: number;
  /** @nullable */
  type?: string | null;
  severity?: EnumsNotificationSeverity;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  message?: string | null;
  isRead?: boolean;
  createdAt?: string;
  /** @nullable */
  readAt?: string | null;
  /** @nullable */
  deliveries?: NotificationsResponsesNotificationDeliveryDto[] | null;
}
