/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { OpenVpnServerWithStatusResponse } from "./openVpnServerWithStatusResponse";

export interface OpenVpnServerWithStatusResponseApiResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: OpenVpnServerWithStatusResponse;
}
