/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */

export interface OpenVpnManagementInfoResponse {
  /** @nullable */
  host?: string | null;
  /** @nullable */
  port?: string | null;
}
