/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */

export interface OverviewMetaDto {
  from?: string;
  to?: string;
  /** @nullable */
  grouping?: string | null;
  /** @nullable */
  timezone?: string | null;
  /** @nullable */
  trafficUnit?: string | null;
  /** @nullable */
  vpnServerId?: number | null;
}
