/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { GeoPointAggDto } from "./geoPointAggDto";

export interface OverviewPointsResponse {
  /** @nullable */
  geoPointAggs?: GeoPointAggDto[] | null;
}
