/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DataGate Monitor API
 * OpenAPI spec version: v1
 */
import type { OverviewTotalsResponse } from "./overviewTotalsResponse";

export interface OverviewTotalsResponseApiResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: OverviewTotalsResponse;
}
