/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DataGate Monitor API
 * OpenAPI spec version: v1
 */

export interface OvpnFileConfigResponse {
  id?: number;
  vpnServerId?: number;
  /** @nullable */
  vpnServerIp?: string | null;
  vpnServerPort?: number;
  /** @nullable */
  configTemplate?: string | null;
}
