/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { VpnServerEventDtoVpnServerEventLogDto } from "./vpnServerEventDtoVpnServerEventLogDto";

export interface PagedVpnServerEventDtoVpnServerEventLogDto {
  page?: number;
  pageSize?: number;
  totalCount?: number;
  /** @nullable */
  items?: VpnServerEventDtoVpnServerEventLogDto[] | null;
  readonly totalPages?: number;
  readonly hasNext?: boolean;
  readonly hasPrev?: boolean;
}
