/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { AuthResponsesAdminTvLoginSessionDto } from './authResponsesAdminTvLoginSessionDto';

export interface PagedAuthResponsesAdminTvLoginSessionDto {
  page?: number;
  pageSize?: number;
  totalCount?: number;
  /** @nullable */
  items?: AuthResponsesAdminTvLoginSessionDto[] | null;
  readonly totalPages?: number;
  readonly hasNext?: boolean;
  readonly hasPrev?: boolean;
}
