/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { VpnProfileNotificationPreferenceItemDto } from "./vpnProfileNotificationPreferenceItemDto";

export interface PutVpnProfileNotificationPreferencesRequest {
  /** @nullable */
  globallyEnabled?: boolean | null;
  /** @nullable */
  preferences?: VpnProfileNotificationPreferenceItemDto[] | null;
}
