/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { QuotaPlanDto } from "./quotaPlanDto";

export interface QuotaPlansResponse {
  /** @nullable */
  quotaPlans?: QuotaPlanDto[] | null;
}
