/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { QuotaPlansResponse } from "./quotaPlansResponse";

export interface QuotaPlansResponseApiResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: QuotaPlansResponse;
}
