/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DataGate Monitor API
 * OpenAPI spec version: v1
 */

export interface RegisterApplicationResponse {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  clientId?: string | null;
  /** @nullable */
  clientSecret?: string | null;
  isRevoked?: boolean;
  isSystem?: boolean;
}
