/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DataGate Monitor API
 * OpenAPI spec version: v1
 */
import type { RegisterUserResponse } from "./registerUserResponse";

export interface RegisterUserResponseApiResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: RegisterUserResponse;
}
