/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { ServerCertificate } from "./serverCertificate";

export interface RevokeCertificateResponse {
  serverCertificate?: ServerCertificate;
}
