/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { RfAvailabilityDtoRfAvailabilityProbeResultDto } from './rfAvailabilityDtoRfAvailabilityProbeResultDto';

export interface RfAvailabilityResponsesRfAvailabilityStatusResponse {
  enabled?: boolean;
  /** @nullable */
  targetUrl?: string | null;
  /** @nullable */
  probeBaseUrl?: string | null;
  /** @nullable */
  lastCheckedAtUtc?: string | null;
  /** @nullable */
  lastDurationMs?: number | null;
  /** @nullable */
  lastError?: string | null;
  lastResult?: RfAvailabilityDtoRfAvailabilityProbeResultDto;
}
