/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DataGate Monitor API
 * OpenAPI spec version: v1
 */
import type { ServiceStatusesResponse } from "./serviceStatusesResponse";

export interface ServiceStatusesResponseApiResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: ServiceStatusesResponse;
}
