/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { TagResponse } from "./tagResponse";

export interface TagResponseApiResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: TagResponse;
}
