/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */

export interface UpdateServerRequest {
  /**
   * @minimum 1
   * @maximum 2147483647
   */
  id: number;
  /** @minLength 1 */
  serverName: string;
  isOnline?: boolean;
  isDefault?: boolean;
  /** @nullable */
  apiUrl?: string | null;
}
