/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { UserDto } from "./userDto";

export interface UsersResponse {
  user?: UserDto;
}
