/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { VpnServersDtoVpnServerDto } from './vpnServersDtoVpnServerDto';

export interface VpnServersResponsesVpnServerResponse {
  vpnServer?: VpnServersDtoVpnServerDto;
}
