/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { VpnServerStatisticsDtoClientTrafficDto } from './vpnServerStatisticsDtoClientTrafficDto';

export interface VpnServerStatisticsResponsesTrafficByClientsResponse {
  /** @nullable */
  clientTraffics?: VpnServerStatisticsDtoClientTrafficDto[] | null;
}
