/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { VpnServerClientsDtoOverviewMetaDto } from './vpnServerClientsDtoOverviewMetaDto';
import type { VpnServerClientsDtoOverviewSeriesRowDto } from './vpnServerClientsDtoOverviewSeriesRowDto';
import type { VpnServerClientsDtoOverviewSummaryDto } from './vpnServerClientsDtoOverviewSummaryDto';

export interface VpnServerClientsResponsesOverviewSeriesResponse {
  meta?: VpnServerClientsDtoOverviewMetaDto;
  summary?: VpnServerClientsDtoOverviewSummaryDto;
  /** @nullable */
  overviewSeriesRows?: VpnServerClientsDtoOverviewSeriesRowDto[] | null;
}
