/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */

export interface VpnServerClientsDtoOverviewUserDto {
  /** @nullable */
  externalId?: string | null;
  /** @nullable */
  displayName?: string | null;
  /** @nullable */
  vpnServerId?: number | null;
  sessions?: number;
  trafficInBytes?: number;
  trafficOutBytes?: number;
  readonly trafficTotalBytes?: number;
  firstSeen?: string;
  lastSeen?: string;
}
