/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { VpnServerWithStatusesV2Response } from "./vpnServerWithStatusesV2Response";

export interface VpnServerWithStatusesV2ResponseApiResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  data?: VpnServerWithStatusesV2Response;
}
