/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { PagedVpnServersDtoVpnClientInfoDto } from './pagedVpnServersDtoVpnClientInfoDto';

export interface VpnServerClientsResponsesVpnClientsV2Response {
  clients?: PagedVpnServersDtoVpnClientInfoDto;
}
