/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DataGate Monitor API
 * OpenAPI spec version: v1
 */
import type { OpenVpnServerEventLogDtoPagedResponse } from "./openVpnServerEventLogDtoPagedResponse";

export interface VpnServerEventResponse {
  events?: OpenVpnServerEventLogDtoPagedResponse;
}
