/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import type { VpnServerStatisticsDtoGeoConnectionDto } from './vpnServerStatisticsDtoGeoConnectionDto';

export interface VpnServerStatisticsResponsesGeoConnectionsResponse {
  /** @nullable */
  geoConnections?: VpnServerStatisticsDtoGeoConnectionDto[] | null;
}
