/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */

export interface XrayClientLinksRequestsDownloadXrayClientLinkRequest {
  /**
     * @minimum 1
     * @maximum 2147483647
     */
  issuedXrayClientLinkId: number;
  /**
     * @minimum 1
     * @maximum 2147483647
     */
  vpnServerId: number;
}
