/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiQuotaPlansResponsesQuotaPlanResponse,
  ApiQuotaPlansResponsesQuotaPlansResponse,
  ApiSystemString,
  QuotaPlansRequestsCreateOrUpdateQuotaPlanRequest,
  QuotaPlansRequestsGetQuotaPlansRequest
} from '../model';

import { ogmMutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const postApiQuotaPlansGetAll = (
    quotaPlansRequestsGetQuotaPlansRequest?: QuotaPlansRequestsGetQuotaPlansRequest,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiQuotaPlansResponsesQuotaPlansResponse>(
      {url: `/api/quota-plans/get-all`, method: 'POST',
      headers: {'Content-Type': 'application/json-patch+json', },
      data: quotaPlansRequestsGetQuotaPlansRequest, signal
    },
      options);
    }



export const getPostApiQuotaPlansGetAllMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiQuotaPlansGetAll>>, TError,{data?: QuotaPlansRequestsGetQuotaPlansRequest}, TContext>, request?: SecondParameter<typeof ogmMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiQuotaPlansGetAll>>, TError,{data?: QuotaPlansRequestsGetQuotaPlansRequest}, TContext> => {

const mutationKey = ['postApiQuotaPlansGetAll'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiQuotaPlansGetAll>>, {data?: QuotaPlansRequestsGetQuotaPlansRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiQuotaPlansGetAll(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiQuotaPlansGetAllMutationResult = NonNullable<Awaited<ReturnType<typeof postApiQuotaPlansGetAll>>>
    export type PostApiQuotaPlansGetAllMutationBody = QuotaPlansRequestsGetQuotaPlansRequest | undefined
    export type PostApiQuotaPlansGetAllMutationError = unknown

    export const usePostApiQuotaPlansGetAll = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiQuotaPlansGetAll>>, TError,{data?: QuotaPlansRequestsGetQuotaPlansRequest}, TContext>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiQuotaPlansGetAll>>,
        TError,
        {data?: QuotaPlansRequestsGetQuotaPlansRequest},
        TContext
      > => {
      return useMutation(getPostApiQuotaPlansGetAllMutationOptions(options), queryClient);
    }
    export const getApiQuotaPlansGetId = (
    id: number,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiQuotaPlansResponsesQuotaPlanResponse>(
      {url: `/api/quota-plans/get/${id}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiQuotaPlansGetIdQueryKey = (id: number,) => {
    return [
    `/api/quota-plans/get/${id}`
    ] as const;
    }


export const getGetApiQuotaPlansGetIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiQuotaPlansGetId>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiQuotaPlansGetId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiQuotaPlansGetIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiQuotaPlansGetId>>> = ({ signal }) => getApiQuotaPlansGetId(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiQuotaPlansGetId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiQuotaPlansGetIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiQuotaPlansGetId>>>
export type GetApiQuotaPlansGetIdQueryError = unknown


export function useGetApiQuotaPlansGetId<TData = Awaited<ReturnType<typeof getApiQuotaPlansGetId>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiQuotaPlansGetId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiQuotaPlansGetId>>,
          TError,
          Awaited<ReturnType<typeof getApiQuotaPlansGetId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiQuotaPlansGetId<TData = Awaited<ReturnType<typeof getApiQuotaPlansGetId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiQuotaPlansGetId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiQuotaPlansGetId>>,
          TError,
          Awaited<ReturnType<typeof getApiQuotaPlansGetId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiQuotaPlansGetId<TData = Awaited<ReturnType<typeof getApiQuotaPlansGetId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiQuotaPlansGetId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiQuotaPlansGetId<TData = Awaited<ReturnType<typeof getApiQuotaPlansGetId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiQuotaPlansGetId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiQuotaPlansGetIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiQuotaPlansCreate = (
    quotaPlansRequestsCreateOrUpdateQuotaPlanRequest?: QuotaPlansRequestsCreateOrUpdateQuotaPlanRequest,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiQuotaPlansResponsesQuotaPlanResponse>(
      {url: `/api/quota-plans/create`, method: 'POST',
      headers: {'Content-Type': 'application/json-patch+json', },
      data: quotaPlansRequestsCreateOrUpdateQuotaPlanRequest, signal
    },
      options);
    }



export const getPostApiQuotaPlansCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiQuotaPlansCreate>>, TError,{data?: QuotaPlansRequestsCreateOrUpdateQuotaPlanRequest}, TContext>, request?: SecondParameter<typeof ogmMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiQuotaPlansCreate>>, TError,{data?: QuotaPlansRequestsCreateOrUpdateQuotaPlanRequest}, TContext> => {

const mutationKey = ['postApiQuotaPlansCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiQuotaPlansCreate>>, {data?: QuotaPlansRequestsCreateOrUpdateQuotaPlanRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiQuotaPlansCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiQuotaPlansCreateMutationResult = NonNullable<Awaited<ReturnType<typeof postApiQuotaPlansCreate>>>
    export type PostApiQuotaPlansCreateMutationBody = QuotaPlansRequestsCreateOrUpdateQuotaPlanRequest | undefined
    export type PostApiQuotaPlansCreateMutationError = unknown

    export const usePostApiQuotaPlansCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiQuotaPlansCreate>>, TError,{data?: QuotaPlansRequestsCreateOrUpdateQuotaPlanRequest}, TContext>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiQuotaPlansCreate>>,
        TError,
        {data?: QuotaPlansRequestsCreateOrUpdateQuotaPlanRequest},
        TContext
      > => {
      return useMutation(getPostApiQuotaPlansCreateMutationOptions(options), queryClient);
    }
    export const putApiQuotaPlansUpdate = (
    quotaPlansRequestsCreateOrUpdateQuotaPlanRequest?: QuotaPlansRequestsCreateOrUpdateQuotaPlanRequest,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiSystemString>(
      {url: `/api/quota-plans/update`, method: 'PUT',
      headers: {'Content-Type': 'application/json-patch+json', },
      data: quotaPlansRequestsCreateOrUpdateQuotaPlanRequest, signal
    },
      options);
    }



export const getPutApiQuotaPlansUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiQuotaPlansUpdate>>, TError,{data?: QuotaPlansRequestsCreateOrUpdateQuotaPlanRequest}, TContext>, request?: SecondParameter<typeof ogmMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiQuotaPlansUpdate>>, TError,{data?: QuotaPlansRequestsCreateOrUpdateQuotaPlanRequest}, TContext> => {

const mutationKey = ['putApiQuotaPlansUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiQuotaPlansUpdate>>, {data?: QuotaPlansRequestsCreateOrUpdateQuotaPlanRequest}> = (props) => {
          const {data} = props ?? {};

          return  putApiQuotaPlansUpdate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiQuotaPlansUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof putApiQuotaPlansUpdate>>>
    export type PutApiQuotaPlansUpdateMutationBody = QuotaPlansRequestsCreateOrUpdateQuotaPlanRequest | undefined
    export type PutApiQuotaPlansUpdateMutationError = unknown

    export const usePutApiQuotaPlansUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiQuotaPlansUpdate>>, TError,{data?: QuotaPlansRequestsCreateOrUpdateQuotaPlanRequest}, TContext>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiQuotaPlansUpdate>>,
        TError,
        {data?: QuotaPlansRequestsCreateOrUpdateQuotaPlanRequest},
        TContext
      > => {
      return useMutation(getPutApiQuotaPlansUpdateMutationOptions(options), queryClient);
    }
    export const deleteApiQuotaPlansDeleteId = (
    id: number,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiSystemString>(
      {url: `/api/quota-plans/delete/${id}`, method: 'DELETE', signal
    },
      options);
    }



export const getDeleteApiQuotaPlansDeleteIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiQuotaPlansDeleteId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof ogmMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiQuotaPlansDeleteId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteApiQuotaPlansDeleteId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiQuotaPlansDeleteId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiQuotaPlansDeleteId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiQuotaPlansDeleteIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiQuotaPlansDeleteId>>>

    export type DeleteApiQuotaPlansDeleteIdMutationError = unknown

    export const useDeleteApiQuotaPlansDeleteId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiQuotaPlansDeleteId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiQuotaPlansDeleteId>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteApiQuotaPlansDeleteIdMutationOptions(options), queryClient);
    }
    export const postApiQuotaPlansSetDefaultId = (
    id: number,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiSystemString>(
      {url: `/api/quota-plans/set-default/${id}`, method: 'POST', signal
    },
      options);
    }



export const getPostApiQuotaPlansSetDefaultIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiQuotaPlansSetDefaultId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof ogmMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiQuotaPlansSetDefaultId>>, TError,{id: number}, TContext> => {

const mutationKey = ['postApiQuotaPlansSetDefaultId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiQuotaPlansSetDefaultId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  postApiQuotaPlansSetDefaultId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiQuotaPlansSetDefaultIdMutationResult = NonNullable<Awaited<ReturnType<typeof postApiQuotaPlansSetDefaultId>>>

    export type PostApiQuotaPlansSetDefaultIdMutationError = unknown

    export const usePostApiQuotaPlansSetDefaultId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiQuotaPlansSetDefaultId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiQuotaPlansSetDefaultId>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getPostApiQuotaPlansSetDefaultIdMutationOptions(options), queryClient);
    }
    export const getApiQuotaPlansHealthcheck = (

 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiSystemString>(
      {url: `/api/quota-plans/healthcheck`, method: 'GET', signal
    },
      options);
    }




export const getGetApiQuotaPlansHealthcheckQueryKey = () => {
    return [
    `/api/quota-plans/healthcheck`
    ] as const;
    }


export const getGetApiQuotaPlansHealthcheckQueryOptions = <TData = Awaited<ReturnType<typeof getApiQuotaPlansHealthcheck>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiQuotaPlansHealthcheck>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiQuotaPlansHealthcheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiQuotaPlansHealthcheck>>> = ({ signal }) => getApiQuotaPlansHealthcheck(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiQuotaPlansHealthcheck>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiQuotaPlansHealthcheckQueryResult = NonNullable<Awaited<ReturnType<typeof getApiQuotaPlansHealthcheck>>>
export type GetApiQuotaPlansHealthcheckQueryError = unknown


export function useGetApiQuotaPlansHealthcheck<TData = Awaited<ReturnType<typeof getApiQuotaPlansHealthcheck>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiQuotaPlansHealthcheck>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiQuotaPlansHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiQuotaPlansHealthcheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiQuotaPlansHealthcheck<TData = Awaited<ReturnType<typeof getApiQuotaPlansHealthcheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiQuotaPlansHealthcheck>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiQuotaPlansHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiQuotaPlansHealthcheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiQuotaPlansHealthcheck<TData = Awaited<ReturnType<typeof getApiQuotaPlansHealthcheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiQuotaPlansHealthcheck>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiQuotaPlansHealthcheck<TData = Awaited<ReturnType<typeof getApiQuotaPlansHealthcheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiQuotaPlansHealthcheck>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiQuotaPlansHealthcheckQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiQuotaPlansHealthcheckWithJwt = (

 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiSystemString>(
      {url: `/api/quota-plans/healthcheck-with-jwt`, method: 'GET', signal
    },
      options);
    }




export const getGetApiQuotaPlansHealthcheckWithJwtQueryKey = () => {
    return [
    `/api/quota-plans/healthcheck-with-jwt`
    ] as const;
    }


export const getGetApiQuotaPlansHealthcheckWithJwtQueryOptions = <TData = Awaited<ReturnType<typeof getApiQuotaPlansHealthcheckWithJwt>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiQuotaPlansHealthcheckWithJwt>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiQuotaPlansHealthcheckWithJwtQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiQuotaPlansHealthcheckWithJwt>>> = ({ signal }) => getApiQuotaPlansHealthcheckWithJwt(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiQuotaPlansHealthcheckWithJwt>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiQuotaPlansHealthcheckWithJwtQueryResult = NonNullable<Awaited<ReturnType<typeof getApiQuotaPlansHealthcheckWithJwt>>>
export type GetApiQuotaPlansHealthcheckWithJwtQueryError = unknown


export function useGetApiQuotaPlansHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiQuotaPlansHealthcheckWithJwt>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiQuotaPlansHealthcheckWithJwt>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiQuotaPlansHealthcheckWithJwt>>,
          TError,
          Awaited<ReturnType<typeof getApiQuotaPlansHealthcheckWithJwt>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiQuotaPlansHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiQuotaPlansHealthcheckWithJwt>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiQuotaPlansHealthcheckWithJwt>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiQuotaPlansHealthcheckWithJwt>>,
          TError,
          Awaited<ReturnType<typeof getApiQuotaPlansHealthcheckWithJwt>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiQuotaPlansHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiQuotaPlansHealthcheckWithJwt>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiQuotaPlansHealthcheckWithJwt>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiQuotaPlansHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiQuotaPlansHealthcheckWithJwt>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiQuotaPlansHealthcheckWithJwt>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiQuotaPlansHealthcheckWithJwtQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






