/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ConnectedClientsResponseApiResponse,
  GetApiOpenVpnClientsGetAllConnectedParams,
  GetApiOpenVpnClientsGetAllHistoryParams,
  GetApiOpenVpnClientsOverviewPointsParams,
  GetApiOpenVpnClientsOverviewSeriesParams,
  GetApiOpenVpnClientsOverviewSummaryParams,
  GetApiOpenVpnClientsOverviewUsersParams,
  GetApiOpenVpnClientsOverviewUsersSeriesParams,
  OverviewPointsResponseApiResponse,
  OverviewSeriesResponseApiResponse,
  OverviewTotalsResponseApiResponse,
  OverviewUsersResponseApiResponse,
  OverviewUsersSeriesResponseApiResponse,
  StringApiResponse,
} from "../model";

import { ogmMutator } from "../../mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type getApiOpenVpnClientsGetAllConnectedResponse200TextPlain = {
  data: ConnectedClientsResponseApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsGetAllConnectedResponse200ApplicationJson = {
  data: ConnectedClientsResponseApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsGetAllConnectedResponse200TextJson = {
  data: ConnectedClientsResponseApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsGetAllConnectedResponseSuccess = (
  | getApiOpenVpnClientsGetAllConnectedResponse200TextPlain
  | getApiOpenVpnClientsGetAllConnectedResponse200ApplicationJson
  | getApiOpenVpnClientsGetAllConnectedResponse200TextJson
) & {
  headers: Headers;
};
export type getApiOpenVpnClientsGetAllConnectedResponse =
  getApiOpenVpnClientsGetAllConnectedResponseSuccess;

export const getGetApiOpenVpnClientsGetAllConnectedUrl = (
  params: GetApiOpenVpnClientsGetAllConnectedParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/open-vpn-clients/get-all-connected?${stringifiedParams}`
    : `/api/open-vpn-clients/get-all-connected`;
};

export const getApiOpenVpnClientsGetAllConnected = async (
  params: GetApiOpenVpnClientsGetAllConnectedParams,
  options?: RequestInit,
): Promise<getApiOpenVpnClientsGetAllConnectedResponse> => {
  return ogmMutator<getApiOpenVpnClientsGetAllConnectedResponse>(
    getGetApiOpenVpnClientsGetAllConnectedUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiOpenVpnClientsGetAllConnectedQueryKey = (
  params?: GetApiOpenVpnClientsGetAllConnectedParams,
) => {
  return [
    `/api/open-vpn-clients/get-all-connected`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetApiOpenVpnClientsGetAllConnectedQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllConnected>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsGetAllConnectedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllConnected>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetApiOpenVpnClientsGetAllConnectedQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllConnected>>
  > = ({ signal }) =>
    getApiOpenVpnClientsGetAllConnected(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllConnected>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiOpenVpnClientsGetAllConnectedQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllConnected>>
>;
export type GetApiOpenVpnClientsGetAllConnectedQueryError = unknown;

export function useGetApiOpenVpnClientsGetAllConnected<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllConnected>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsGetAllConnectedParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllConnected>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllConnected>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllConnected>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnClientsGetAllConnected<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllConnected>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsGetAllConnectedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllConnected>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllConnected>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllConnected>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnClientsGetAllConnected<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllConnected>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsGetAllConnectedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllConnected>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiOpenVpnClientsGetAllConnected<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllConnected>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsGetAllConnectedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllConnected>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiOpenVpnClientsGetAllConnectedQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type getApiOpenVpnClientsGetAllHistoryResponse200TextPlain = {
  data: ConnectedClientsResponseApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsGetAllHistoryResponse200ApplicationJson = {
  data: ConnectedClientsResponseApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsGetAllHistoryResponse200TextJson = {
  data: ConnectedClientsResponseApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsGetAllHistoryResponseSuccess = (
  | getApiOpenVpnClientsGetAllHistoryResponse200TextPlain
  | getApiOpenVpnClientsGetAllHistoryResponse200ApplicationJson
  | getApiOpenVpnClientsGetAllHistoryResponse200TextJson
) & {
  headers: Headers;
};
export type getApiOpenVpnClientsGetAllHistoryResponse =
  getApiOpenVpnClientsGetAllHistoryResponseSuccess;

export const getGetApiOpenVpnClientsGetAllHistoryUrl = (
  params: GetApiOpenVpnClientsGetAllHistoryParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/open-vpn-clients/get-all-history?${stringifiedParams}`
    : `/api/open-vpn-clients/get-all-history`;
};

export const getApiOpenVpnClientsGetAllHistory = async (
  params: GetApiOpenVpnClientsGetAllHistoryParams,
  options?: RequestInit,
): Promise<getApiOpenVpnClientsGetAllHistoryResponse> => {
  return ogmMutator<getApiOpenVpnClientsGetAllHistoryResponse>(
    getGetApiOpenVpnClientsGetAllHistoryUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiOpenVpnClientsGetAllHistoryQueryKey = (
  params?: GetApiOpenVpnClientsGetAllHistoryParams,
) => {
  return [
    `/api/open-vpn-clients/get-all-history`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetApiOpenVpnClientsGetAllHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllHistory>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsGetAllHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetApiOpenVpnClientsGetAllHistoryQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllHistory>>
  > = ({ signal }) =>
    getApiOpenVpnClientsGetAllHistory(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllHistory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiOpenVpnClientsGetAllHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllHistory>>
>;
export type GetApiOpenVpnClientsGetAllHistoryQueryError = unknown;

export function useGetApiOpenVpnClientsGetAllHistory<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllHistory>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsGetAllHistoryParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllHistory>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllHistory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnClientsGetAllHistory<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllHistory>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsGetAllHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllHistory>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllHistory>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnClientsGetAllHistory<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllHistory>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsGetAllHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiOpenVpnClientsGetAllHistory<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllHistory>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsGetAllHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsGetAllHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiOpenVpnClientsGetAllHistoryQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type getApiOpenVpnClientsOverviewSeriesResponse200TextPlain = {
  data: OverviewSeriesResponseApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsOverviewSeriesResponse200ApplicationJson = {
  data: OverviewSeriesResponseApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsOverviewSeriesResponse200TextJson = {
  data: OverviewSeriesResponseApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsOverviewSeriesResponseSuccess = (
  | getApiOpenVpnClientsOverviewSeriesResponse200TextPlain
  | getApiOpenVpnClientsOverviewSeriesResponse200ApplicationJson
  | getApiOpenVpnClientsOverviewSeriesResponse200TextJson
) & {
  headers: Headers;
};
export type getApiOpenVpnClientsOverviewSeriesResponse =
  getApiOpenVpnClientsOverviewSeriesResponseSuccess;

export const getGetApiOpenVpnClientsOverviewSeriesUrl = (
  params: GetApiOpenVpnClientsOverviewSeriesParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/open-vpn-clients/overview/series?${stringifiedParams}`
    : `/api/open-vpn-clients/overview/series`;
};

export const getApiOpenVpnClientsOverviewSeries = async (
  params: GetApiOpenVpnClientsOverviewSeriesParams,
  options?: RequestInit,
): Promise<getApiOpenVpnClientsOverviewSeriesResponse> => {
  return ogmMutator<getApiOpenVpnClientsOverviewSeriesResponse>(
    getGetApiOpenVpnClientsOverviewSeriesUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiOpenVpnClientsOverviewSeriesQueryKey = (
  params?: GetApiOpenVpnClientsOverviewSeriesParams,
) => {
  return [
    `/api/open-vpn-clients/overview/series`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetApiOpenVpnClientsOverviewSeriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSeries>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsOverviewSeriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSeries>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetApiOpenVpnClientsOverviewSeriesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSeries>>
  > = ({ signal }) =>
    getApiOpenVpnClientsOverviewSeries(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSeries>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiOpenVpnClientsOverviewSeriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSeries>>
>;
export type GetApiOpenVpnClientsOverviewSeriesQueryError = unknown;

export function useGetApiOpenVpnClientsOverviewSeries<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSeries>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsOverviewSeriesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSeries>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSeries>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSeries>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnClientsOverviewSeries<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSeries>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsOverviewSeriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSeries>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSeries>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSeries>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnClientsOverviewSeries<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSeries>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsOverviewSeriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSeries>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiOpenVpnClientsOverviewSeries<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSeries>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsOverviewSeriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSeries>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiOpenVpnClientsOverviewSeriesQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type getApiOpenVpnClientsOverviewSummaryResponse200TextPlain = {
  data: OverviewTotalsResponseApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsOverviewSummaryResponse200ApplicationJson = {
  data: OverviewTotalsResponseApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsOverviewSummaryResponse200TextJson = {
  data: OverviewTotalsResponseApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsOverviewSummaryResponseSuccess = (
  | getApiOpenVpnClientsOverviewSummaryResponse200TextPlain
  | getApiOpenVpnClientsOverviewSummaryResponse200ApplicationJson
  | getApiOpenVpnClientsOverviewSummaryResponse200TextJson
) & {
  headers: Headers;
};
export type getApiOpenVpnClientsOverviewSummaryResponse =
  getApiOpenVpnClientsOverviewSummaryResponseSuccess;

export const getGetApiOpenVpnClientsOverviewSummaryUrl = (
  params: GetApiOpenVpnClientsOverviewSummaryParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/open-vpn-clients/overview/summary?${stringifiedParams}`
    : `/api/open-vpn-clients/overview/summary`;
};

export const getApiOpenVpnClientsOverviewSummary = async (
  params: GetApiOpenVpnClientsOverviewSummaryParams,
  options?: RequestInit,
): Promise<getApiOpenVpnClientsOverviewSummaryResponse> => {
  return ogmMutator<getApiOpenVpnClientsOverviewSummaryResponse>(
    getGetApiOpenVpnClientsOverviewSummaryUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiOpenVpnClientsOverviewSummaryQueryKey = (
  params?: GetApiOpenVpnClientsOverviewSummaryParams,
) => {
  return [
    `/api/open-vpn-clients/overview/summary`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetApiOpenVpnClientsOverviewSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSummary>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsOverviewSummaryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSummary>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetApiOpenVpnClientsOverviewSummaryQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSummary>>
  > = ({ signal }) =>
    getApiOpenVpnClientsOverviewSummary(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSummary>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiOpenVpnClientsOverviewSummaryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSummary>>
>;
export type GetApiOpenVpnClientsOverviewSummaryQueryError = unknown;

export function useGetApiOpenVpnClientsOverviewSummary<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSummary>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsOverviewSummaryParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSummary>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSummary>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSummary>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnClientsOverviewSummary<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSummary>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsOverviewSummaryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSummary>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSummary>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSummary>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnClientsOverviewSummary<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSummary>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsOverviewSummaryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSummary>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiOpenVpnClientsOverviewSummary<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSummary>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsOverviewSummaryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewSummary>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiOpenVpnClientsOverviewSummaryQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type getApiOpenVpnClientsOverviewPointsResponse200TextPlain = {
  data: OverviewPointsResponseApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsOverviewPointsResponse200ApplicationJson = {
  data: OverviewPointsResponseApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsOverviewPointsResponse200TextJson = {
  data: OverviewPointsResponseApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsOverviewPointsResponseSuccess = (
  | getApiOpenVpnClientsOverviewPointsResponse200TextPlain
  | getApiOpenVpnClientsOverviewPointsResponse200ApplicationJson
  | getApiOpenVpnClientsOverviewPointsResponse200TextJson
) & {
  headers: Headers;
};
export type getApiOpenVpnClientsOverviewPointsResponse =
  getApiOpenVpnClientsOverviewPointsResponseSuccess;

export const getGetApiOpenVpnClientsOverviewPointsUrl = (
  params: GetApiOpenVpnClientsOverviewPointsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/open-vpn-clients/overview/points?${stringifiedParams}`
    : `/api/open-vpn-clients/overview/points`;
};

export const getApiOpenVpnClientsOverviewPoints = async (
  params: GetApiOpenVpnClientsOverviewPointsParams,
  options?: RequestInit,
): Promise<getApiOpenVpnClientsOverviewPointsResponse> => {
  return ogmMutator<getApiOpenVpnClientsOverviewPointsResponse>(
    getGetApiOpenVpnClientsOverviewPointsUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiOpenVpnClientsOverviewPointsQueryKey = (
  params?: GetApiOpenVpnClientsOverviewPointsParams,
) => {
  return [
    `/api/open-vpn-clients/overview/points`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetApiOpenVpnClientsOverviewPointsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewPoints>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsOverviewPointsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewPoints>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetApiOpenVpnClientsOverviewPointsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewPoints>>
  > = ({ signal }) =>
    getApiOpenVpnClientsOverviewPoints(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewPoints>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiOpenVpnClientsOverviewPointsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewPoints>>
>;
export type GetApiOpenVpnClientsOverviewPointsQueryError = unknown;

export function useGetApiOpenVpnClientsOverviewPoints<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewPoints>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsOverviewPointsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewPoints>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewPoints>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewPoints>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnClientsOverviewPoints<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewPoints>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsOverviewPointsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewPoints>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewPoints>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewPoints>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnClientsOverviewPoints<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewPoints>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsOverviewPointsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewPoints>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiOpenVpnClientsOverviewPoints<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewPoints>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsOverviewPointsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewPoints>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiOpenVpnClientsOverviewPointsQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type getApiOpenVpnClientsOverviewUsersResponse200TextPlain = {
  data: OverviewUsersResponseApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsOverviewUsersResponse200ApplicationJson = {
  data: OverviewUsersResponseApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsOverviewUsersResponse200TextJson = {
  data: OverviewUsersResponseApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsOverviewUsersResponseSuccess = (
  | getApiOpenVpnClientsOverviewUsersResponse200TextPlain
  | getApiOpenVpnClientsOverviewUsersResponse200ApplicationJson
  | getApiOpenVpnClientsOverviewUsersResponse200TextJson
) & {
  headers: Headers;
};
export type getApiOpenVpnClientsOverviewUsersResponse =
  getApiOpenVpnClientsOverviewUsersResponseSuccess;

export const getGetApiOpenVpnClientsOverviewUsersUrl = (
  params: GetApiOpenVpnClientsOverviewUsersParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/open-vpn-clients/overview/users?${stringifiedParams}`
    : `/api/open-vpn-clients/overview/users`;
};

export const getApiOpenVpnClientsOverviewUsers = async (
  params: GetApiOpenVpnClientsOverviewUsersParams,
  options?: RequestInit,
): Promise<getApiOpenVpnClientsOverviewUsersResponse> => {
  return ogmMutator<getApiOpenVpnClientsOverviewUsersResponse>(
    getGetApiOpenVpnClientsOverviewUsersUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiOpenVpnClientsOverviewUsersQueryKey = (
  params?: GetApiOpenVpnClientsOverviewUsersParams,
) => {
  return [
    `/api/open-vpn-clients/overview/users`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetApiOpenVpnClientsOverviewUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsers>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsOverviewUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsers>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetApiOpenVpnClientsOverviewUsersQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsers>>
  > = ({ signal }) =>
    getApiOpenVpnClientsOverviewUsers(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiOpenVpnClientsOverviewUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsers>>
>;
export type GetApiOpenVpnClientsOverviewUsersQueryError = unknown;

export function useGetApiOpenVpnClientsOverviewUsers<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsers>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsOverviewUsersParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsers>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsers>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsers>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnClientsOverviewUsers<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsers>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsOverviewUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsers>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsers>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsers>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnClientsOverviewUsers<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsers>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsOverviewUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsers>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiOpenVpnClientsOverviewUsers<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsers>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsOverviewUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsers>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiOpenVpnClientsOverviewUsersQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type getApiOpenVpnClientsOverviewUsersSeriesResponse200TextPlain = {
  data: OverviewUsersSeriesResponseApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsOverviewUsersSeriesResponse200ApplicationJson =
  {
    data: OverviewUsersSeriesResponseApiResponse;
    status: 200;
  };

export type getApiOpenVpnClientsOverviewUsersSeriesResponse200TextJson = {
  data: OverviewUsersSeriesResponseApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsOverviewUsersSeriesResponseSuccess = (
  | getApiOpenVpnClientsOverviewUsersSeriesResponse200TextPlain
  | getApiOpenVpnClientsOverviewUsersSeriesResponse200ApplicationJson
  | getApiOpenVpnClientsOverviewUsersSeriesResponse200TextJson
) & {
  headers: Headers;
};
export type getApiOpenVpnClientsOverviewUsersSeriesResponse =
  getApiOpenVpnClientsOverviewUsersSeriesResponseSuccess;

export const getGetApiOpenVpnClientsOverviewUsersSeriesUrl = (
  params: GetApiOpenVpnClientsOverviewUsersSeriesParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/open-vpn-clients/overview/users/series?${stringifiedParams}`
    : `/api/open-vpn-clients/overview/users/series`;
};

export const getApiOpenVpnClientsOverviewUsersSeries = async (
  params: GetApiOpenVpnClientsOverviewUsersSeriesParams,
  options?: RequestInit,
): Promise<getApiOpenVpnClientsOverviewUsersSeriesResponse> => {
  return ogmMutator<getApiOpenVpnClientsOverviewUsersSeriesResponse>(
    getGetApiOpenVpnClientsOverviewUsersSeriesUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiOpenVpnClientsOverviewUsersSeriesQueryKey = (
  params?: GetApiOpenVpnClientsOverviewUsersSeriesParams,
) => {
  return [
    `/api/open-vpn-clients/overview/users/series`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetApiOpenVpnClientsOverviewUsersSeriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsersSeries>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsOverviewUsersSeriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsersSeries>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetApiOpenVpnClientsOverviewUsersSeriesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsersSeries>>
  > = ({ signal }) =>
    getApiOpenVpnClientsOverviewUsersSeries(params, {
      signal,
      ...requestOptions,
    });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsersSeries>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiOpenVpnClientsOverviewUsersSeriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsersSeries>>
>;
export type GetApiOpenVpnClientsOverviewUsersSeriesQueryError = unknown;

export function useGetApiOpenVpnClientsOverviewUsersSeries<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsersSeries>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsOverviewUsersSeriesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsersSeries>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsersSeries>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsersSeries>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnClientsOverviewUsersSeries<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsersSeries>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsOverviewUsersSeriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsersSeries>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsersSeries>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsersSeries>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnClientsOverviewUsersSeries<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsersSeries>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsOverviewUsersSeriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsersSeries>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiOpenVpnClientsOverviewUsersSeries<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsersSeries>>,
  TError = unknown,
>(
  params: GetApiOpenVpnClientsOverviewUsersSeriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsOverviewUsersSeries>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiOpenVpnClientsOverviewUsersSeriesQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type getApiOpenVpnClientsHealthcheckResponse200TextPlain = {
  data: StringApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsHealthcheckResponse200ApplicationJson = {
  data: StringApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsHealthcheckResponse200TextJson = {
  data: StringApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsHealthcheckResponseSuccess = (
  | getApiOpenVpnClientsHealthcheckResponse200TextPlain
  | getApiOpenVpnClientsHealthcheckResponse200ApplicationJson
  | getApiOpenVpnClientsHealthcheckResponse200TextJson
) & {
  headers: Headers;
};
export type getApiOpenVpnClientsHealthcheckResponse =
  getApiOpenVpnClientsHealthcheckResponseSuccess;

export const getGetApiOpenVpnClientsHealthcheckUrl = () => {
  return `/api/open-vpn-clients/healthcheck`;
};

export const getApiOpenVpnClientsHealthcheck = async (
  options?: RequestInit,
): Promise<getApiOpenVpnClientsHealthcheckResponse> => {
  return ogmMutator<getApiOpenVpnClientsHealthcheckResponse>(
    getGetApiOpenVpnClientsHealthcheckUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiOpenVpnClientsHealthcheckQueryKey = () => {
  return [`/api/open-vpn-clients/healthcheck`] as const;
};

export const getGetApiOpenVpnClientsHealthcheckQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheck>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheck>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof ogmMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiOpenVpnClientsHealthcheckQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheck>>
  > = ({ signal }) =>
    getApiOpenVpnClientsHealthcheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheck>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiOpenVpnClientsHealthcheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheck>>
>;
export type GetApiOpenVpnClientsHealthcheckQueryError = unknown;

export function useGetApiOpenVpnClientsHealthcheck<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheck>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheck>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheck>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnClientsHealthcheck<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheck>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheck>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnClientsHealthcheck<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheck>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiOpenVpnClientsHealthcheck<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheck>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiOpenVpnClientsHealthcheckQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type getApiOpenVpnClientsHealthcheckWithJwtResponse200TextPlain = {
  data: StringApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsHealthcheckWithJwtResponse200ApplicationJson = {
  data: StringApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsHealthcheckWithJwtResponse200TextJson = {
  data: StringApiResponse;
  status: 200;
};

export type getApiOpenVpnClientsHealthcheckWithJwtResponseSuccess = (
  | getApiOpenVpnClientsHealthcheckWithJwtResponse200TextPlain
  | getApiOpenVpnClientsHealthcheckWithJwtResponse200ApplicationJson
  | getApiOpenVpnClientsHealthcheckWithJwtResponse200TextJson
) & {
  headers: Headers;
};
export type getApiOpenVpnClientsHealthcheckWithJwtResponse =
  getApiOpenVpnClientsHealthcheckWithJwtResponseSuccess;

export const getGetApiOpenVpnClientsHealthcheckWithJwtUrl = () => {
  return `/api/open-vpn-clients/healthcheck-with-jwt`;
};

export const getApiOpenVpnClientsHealthcheckWithJwt = async (
  options?: RequestInit,
): Promise<getApiOpenVpnClientsHealthcheckWithJwtResponse> => {
  return ogmMutator<getApiOpenVpnClientsHealthcheckWithJwtResponse>(
    getGetApiOpenVpnClientsHealthcheckWithJwtUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiOpenVpnClientsHealthcheckWithJwtQueryKey = () => {
  return [`/api/open-vpn-clients/healthcheck-with-jwt`] as const;
};

export const getGetApiOpenVpnClientsHealthcheckWithJwtQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheckWithJwt>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheckWithJwt>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof ogmMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetApiOpenVpnClientsHealthcheckWithJwtQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheckWithJwt>>
  > = ({ signal }) =>
    getApiOpenVpnClientsHealthcheckWithJwt({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheckWithJwt>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiOpenVpnClientsHealthcheckWithJwtQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheckWithJwt>>
>;
export type GetApiOpenVpnClientsHealthcheckWithJwtQueryError = unknown;

export function useGetApiOpenVpnClientsHealthcheckWithJwt<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheckWithJwt>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheckWithJwt>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheckWithJwt>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheckWithJwt>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnClientsHealthcheckWithJwt<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheckWithJwt>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheckWithJwt>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheckWithJwt>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheckWithJwt>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnClientsHealthcheckWithJwt<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheckWithJwt>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheckWithJwt>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiOpenVpnClientsHealthcheckWithJwt<
  TData = Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheckWithJwt>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnClientsHealthcheckWithJwt>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetApiOpenVpnClientsHealthcheckWithJwtQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
