/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { ogmMutator } from "../../mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getApiOpenVpnServersStatusStream = (
  options?: SecondParameter<typeof ogmMutator>,
  signal?: AbortSignal,
) => {
  return ogmMutator<void>(
    { url: `/api/open-vpn-servers/status-stream`, method: "GET", signal },
    options,
  );
};

export const getGetApiOpenVpnServersStatusStreamQueryKey = () => {
  return [`/api/open-vpn-servers/status-stream`] as const;
};

export const getGetApiOpenVpnServersStatusStreamQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiOpenVpnServersStatusStream>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiOpenVpnServersStatusStream>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof ogmMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiOpenVpnServersStatusStreamQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiOpenVpnServersStatusStream>>
  > = ({ signal }) => getApiOpenVpnServersStatusStream(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiOpenVpnServersStatusStream>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiOpenVpnServersStatusStreamQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiOpenVpnServersStatusStream>>
>;
export type GetApiOpenVpnServersStatusStreamQueryError = unknown;

export function useGetApiOpenVpnServersStatusStream<
  TData = Awaited<ReturnType<typeof getApiOpenVpnServersStatusStream>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnServersStatusStream>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnServersStatusStream>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnServersStatusStream>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnServersStatusStream<
  TData = Awaited<ReturnType<typeof getApiOpenVpnServersStatusStream>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnServersStatusStream>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnServersStatusStream>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnServersStatusStream>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnServersStatusStream<
  TData = Awaited<ReturnType<typeof getApiOpenVpnServersStatusStream>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnServersStatusStream>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiOpenVpnServersStatusStream<
  TData = Awaited<ReturnType<typeof getApiOpenVpnServersStatusStream>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnServersStatusStream>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiOpenVpnServersStatusStreamQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
