/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiSystemString
} from '../model';

import { ogmMutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getApiBaseHealthcheck = (

 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiSystemString>(
      {url: `/api/base/healthcheck`, method: 'GET', signal
    },
      options);
    }




export const getGetApiBaseHealthcheckQueryKey = () => {
    return [
    `/api/base/healthcheck`
    ] as const;
    }


export const getGetApiBaseHealthcheckQueryOptions = <TData = Awaited<ReturnType<typeof getApiBaseHealthcheck>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBaseHealthcheck>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiBaseHealthcheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBaseHealthcheck>>> = ({ signal }) => getApiBaseHealthcheck(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiBaseHealthcheck>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiBaseHealthcheckQueryResult = NonNullable<Awaited<ReturnType<typeof getApiBaseHealthcheck>>>
export type GetApiBaseHealthcheckQueryError = unknown


export function useGetApiBaseHealthcheck<TData = Awaited<ReturnType<typeof getApiBaseHealthcheck>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBaseHealthcheck>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBaseHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiBaseHealthcheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBaseHealthcheck<TData = Awaited<ReturnType<typeof getApiBaseHealthcheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBaseHealthcheck>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBaseHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiBaseHealthcheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBaseHealthcheck<TData = Awaited<ReturnType<typeof getApiBaseHealthcheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBaseHealthcheck>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiBaseHealthcheck<TData = Awaited<ReturnType<typeof getApiBaseHealthcheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBaseHealthcheck>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiBaseHealthcheckQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiBaseHealthcheckWithJwt = (

 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiSystemString>(
      {url: `/api/base/healthcheck-with-jwt`, method: 'GET', signal
    },
      options);
    }




export const getGetApiBaseHealthcheckWithJwtQueryKey = () => {
    return [
    `/api/base/healthcheck-with-jwt`
    ] as const;
    }


export const getGetApiBaseHealthcheckWithJwtQueryOptions = <TData = Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiBaseHealthcheckWithJwtQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>> = ({ signal }) => getApiBaseHealthcheckWithJwt(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiBaseHealthcheckWithJwtQueryResult = NonNullable<Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>>
export type GetApiBaseHealthcheckWithJwtQueryError = unknown


export function useGetApiBaseHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>,
          TError,
          Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBaseHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>,
          TError,
          Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBaseHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiBaseHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiBaseHealthcheckWithJwtQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






