/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { StringApiResponse } from ".././model";

import { ogmMutator } from ".././mutator";

export const getApiBaseHealthcheck = (signal?: AbortSignal) => {
  return ogmMutator<StringApiResponse>({
    url: `/api/base/healthcheck`,
    method: "GET",
    signal,
  });
};

export const getGetApiBaseHealthcheckQueryKey = () => {
  return [`/api/base/healthcheck`] as const;
};

export const getGetApiBaseHealthcheckQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiBaseHealthcheck>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiBaseHealthcheck>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiBaseHealthcheckQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiBaseHealthcheck>>
  > = ({ signal }) => getApiBaseHealthcheck(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiBaseHealthcheck>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiBaseHealthcheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiBaseHealthcheck>>
>;
export type GetApiBaseHealthcheckQueryError = unknown;

export function useGetApiBaseHealthcheck<
  TData = Awaited<ReturnType<typeof getApiBaseHealthcheck>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiBaseHealthcheck>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBaseHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiBaseHealthcheck>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiBaseHealthcheck<
  TData = Awaited<ReturnType<typeof getApiBaseHealthcheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiBaseHealthcheck>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBaseHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiBaseHealthcheck>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiBaseHealthcheck<
  TData = Awaited<ReturnType<typeof getApiBaseHealthcheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiBaseHealthcheck>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiBaseHealthcheck<
  TData = Awaited<ReturnType<typeof getApiBaseHealthcheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiBaseHealthcheck>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiBaseHealthcheckQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiBaseHealthcheckWithJwt = (signal?: AbortSignal) => {
  return ogmMutator<StringApiResponse>({
    url: `/api/base/healthcheck-with-jwt`,
    method: "GET",
    signal,
  });
};

export const getGetApiBaseHealthcheckWithJwtQueryKey = () => {
  return [`/api/base/healthcheck-with-jwt`] as const;
};

export const getGetApiBaseHealthcheckWithJwtQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiBaseHealthcheckWithJwtQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>
  > = ({ signal }) => getApiBaseHealthcheckWithJwt(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiBaseHealthcheckWithJwtQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>
>;
export type GetApiBaseHealthcheckWithJwtQueryError = unknown;

export function useGetApiBaseHealthcheckWithJwt<
  TData = Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>,
          TError,
          Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiBaseHealthcheckWithJwt<
  TData = Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>,
          TError,
          Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiBaseHealthcheckWithJwt<
  TData = Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiBaseHealthcheckWithJwt<
  TData = Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiBaseHealthcheckWithJwt>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiBaseHealthcheckWithJwtQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
