/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiDataGateOpenVpnManagerDiagnosticsResponsesPiHoleDiagnosticsResponse,
  ApiSystemString,
  ApiVpnServerPiHoleResponsesApplyVpnServerPiHoleRuntimeResponse,
  ApiVpnServerPiHoleResponsesVpnServerPiHoleConfigResponse,
  ApiVpnServerPiHoleResponsesVpnServerPiHoleRuntimeConfigResponse,
  VpnServerPiHoleRequestsUpsertVpnServerPiHoleConfigRequest
} from '../model';

import { ogmMutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getApiOpenVpnServersPiHoleConfigVpnServerId = (
    vpnServerId: number,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiVpnServerPiHoleResponsesVpnServerPiHoleConfigResponse>(
      {url: `/api/open-vpn-servers/pi-hole-config/${vpnServerId}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiOpenVpnServersPiHoleConfigVpnServerIdQueryKey = (vpnServerId: number,) => {
    return [
    `/api/open-vpn-servers/pi-hole-config/${vpnServerId}`
    ] as const;
    }


export const getGetApiOpenVpnServersPiHoleConfigVpnServerIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerId>>, TError = unknown>(vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiOpenVpnServersPiHoleConfigVpnServerIdQueryKey(vpnServerId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerId>>> = ({ signal }) => getApiOpenVpnServersPiHoleConfigVpnServerId(vpnServerId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: vpnServerId !== null && vpnServerId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiOpenVpnServersPiHoleConfigVpnServerIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerId>>>
export type GetApiOpenVpnServersPiHoleConfigVpnServerIdQueryError = unknown


export function useGetApiOpenVpnServersPiHoleConfigVpnServerId<TData = Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerId>>, TError = unknown>(
 vpnServerId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerId>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiOpenVpnServersPiHoleConfigVpnServerId<TData = Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerId>>, TError = unknown>(
 vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerId>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiOpenVpnServersPiHoleConfigVpnServerId<TData = Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerId>>, TError = unknown>(
 vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiOpenVpnServersPiHoleConfigVpnServerId<TData = Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerId>>, TError = unknown>(
 vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiOpenVpnServersPiHoleConfigVpnServerIdQueryOptions(vpnServerId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const putApiOpenVpnServersPiHoleConfig = (
    vpnServerPiHoleRequestsUpsertVpnServerPiHoleConfigRequest?: VpnServerPiHoleRequestsUpsertVpnServerPiHoleConfigRequest,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiVpnServerPiHoleResponsesVpnServerPiHoleConfigResponse>(
      {url: `/api/open-vpn-servers/pi-hole-config`, method: 'PUT',
      headers: {'Content-Type': 'application/json-patch+json', },
      data: vpnServerPiHoleRequestsUpsertVpnServerPiHoleConfigRequest, signal
    },
      options);
    }



export const getPutApiOpenVpnServersPiHoleConfigMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiOpenVpnServersPiHoleConfig>>, TError,{data?: VpnServerPiHoleRequestsUpsertVpnServerPiHoleConfigRequest}, TContext>, request?: SecondParameter<typeof ogmMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiOpenVpnServersPiHoleConfig>>, TError,{data?: VpnServerPiHoleRequestsUpsertVpnServerPiHoleConfigRequest}, TContext> => {

const mutationKey = ['putApiOpenVpnServersPiHoleConfig'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiOpenVpnServersPiHoleConfig>>, {data?: VpnServerPiHoleRequestsUpsertVpnServerPiHoleConfigRequest}> = (props) => {
          const {data} = props ?? {};

          return  putApiOpenVpnServersPiHoleConfig(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiOpenVpnServersPiHoleConfigMutationResult = NonNullable<Awaited<ReturnType<typeof putApiOpenVpnServersPiHoleConfig>>>
    export type PutApiOpenVpnServersPiHoleConfigMutationBody = VpnServerPiHoleRequestsUpsertVpnServerPiHoleConfigRequest | undefined
    export type PutApiOpenVpnServersPiHoleConfigMutationError = unknown

    export const usePutApiOpenVpnServersPiHoleConfig = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiOpenVpnServersPiHoleConfig>>, TError,{data?: VpnServerPiHoleRequestsUpsertVpnServerPiHoleConfigRequest}, TContext>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiOpenVpnServersPiHoleConfig>>,
        TError,
        {data?: VpnServerPiHoleRequestsUpsertVpnServerPiHoleConfigRequest},
        TContext
      > => {
      return useMutation(getPutApiOpenVpnServersPiHoleConfigMutationOptions(options), queryClient);
    }
    export const postApiOpenVpnServersPiHoleConfigVpnServerIdApplyRuntime = (
    vpnServerId: number,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiVpnServerPiHoleResponsesApplyVpnServerPiHoleRuntimeResponse>(
      {url: `/api/open-vpn-servers/pi-hole-config/${vpnServerId}/apply-runtime`, method: 'POST', signal
    },
      options);
    }



export const getPostApiOpenVpnServersPiHoleConfigVpnServerIdApplyRuntimeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiOpenVpnServersPiHoleConfigVpnServerIdApplyRuntime>>, TError,{vpnServerId: number}, TContext>, request?: SecondParameter<typeof ogmMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiOpenVpnServersPiHoleConfigVpnServerIdApplyRuntime>>, TError,{vpnServerId: number}, TContext> => {

const mutationKey = ['postApiOpenVpnServersPiHoleConfigVpnServerIdApplyRuntime'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiOpenVpnServersPiHoleConfigVpnServerIdApplyRuntime>>, {vpnServerId: number}> = (props) => {
          const {vpnServerId} = props ?? {};

          return  postApiOpenVpnServersPiHoleConfigVpnServerIdApplyRuntime(vpnServerId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiOpenVpnServersPiHoleConfigVpnServerIdApplyRuntimeMutationResult = NonNullable<Awaited<ReturnType<typeof postApiOpenVpnServersPiHoleConfigVpnServerIdApplyRuntime>>>

    export type PostApiOpenVpnServersPiHoleConfigVpnServerIdApplyRuntimeMutationError = unknown

    export const usePostApiOpenVpnServersPiHoleConfigVpnServerIdApplyRuntime = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiOpenVpnServersPiHoleConfigVpnServerIdApplyRuntime>>, TError,{vpnServerId: number}, TContext>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiOpenVpnServersPiHoleConfigVpnServerIdApplyRuntime>>,
        TError,
        {vpnServerId: number},
        TContext
      > => {
      return useMutation(getPostApiOpenVpnServersPiHoleConfigVpnServerIdApplyRuntimeMutationOptions(options), queryClient);
    }
    export const getApiOpenVpnServersPiHoleConfigVpnServerIdDiagnostics = (
    vpnServerId: number,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiDataGateOpenVpnManagerDiagnosticsResponsesPiHoleDiagnosticsResponse>(
      {url: `/api/open-vpn-servers/pi-hole-config/${vpnServerId}/diagnostics`, method: 'GET', signal
    },
      options);
    }




export const getGetApiOpenVpnServersPiHoleConfigVpnServerIdDiagnosticsQueryKey = (vpnServerId: number,) => {
    return [
    `/api/open-vpn-servers/pi-hole-config/${vpnServerId}/diagnostics`
    ] as const;
    }


export const getGetApiOpenVpnServersPiHoleConfigVpnServerIdDiagnosticsQueryOptions = <TData = Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerIdDiagnostics>>, TError = unknown>(vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerIdDiagnostics>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiOpenVpnServersPiHoleConfigVpnServerIdDiagnosticsQueryKey(vpnServerId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerIdDiagnostics>>> = ({ signal }) => getApiOpenVpnServersPiHoleConfigVpnServerIdDiagnostics(vpnServerId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: vpnServerId !== null && vpnServerId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerIdDiagnostics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiOpenVpnServersPiHoleConfigVpnServerIdDiagnosticsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerIdDiagnostics>>>
export type GetApiOpenVpnServersPiHoleConfigVpnServerIdDiagnosticsQueryError = unknown


export function useGetApiOpenVpnServersPiHoleConfigVpnServerIdDiagnostics<TData = Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerIdDiagnostics>>, TError = unknown>(
 vpnServerId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerIdDiagnostics>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerIdDiagnostics>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerIdDiagnostics>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiOpenVpnServersPiHoleConfigVpnServerIdDiagnostics<TData = Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerIdDiagnostics>>, TError = unknown>(
 vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerIdDiagnostics>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerIdDiagnostics>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerIdDiagnostics>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiOpenVpnServersPiHoleConfigVpnServerIdDiagnostics<TData = Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerIdDiagnostics>>, TError = unknown>(
 vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerIdDiagnostics>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiOpenVpnServersPiHoleConfigVpnServerIdDiagnostics<TData = Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerIdDiagnostics>>, TError = unknown>(
 vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigVpnServerIdDiagnostics>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiOpenVpnServersPiHoleConfigVpnServerIdDiagnosticsQueryOptions(vpnServerId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiOpenVpnServersPiHoleConfigRuntimeVpnServerId = (
    vpnServerId: number,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiVpnServerPiHoleResponsesVpnServerPiHoleRuntimeConfigResponse>(
      {url: `/api/open-vpn-servers/pi-hole-config/runtime/${vpnServerId}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiOpenVpnServersPiHoleConfigRuntimeVpnServerIdQueryKey = (vpnServerId: number,) => {
    return [
    `/api/open-vpn-servers/pi-hole-config/runtime/${vpnServerId}`
    ] as const;
    }


export const getGetApiOpenVpnServersPiHoleConfigRuntimeVpnServerIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigRuntimeVpnServerId>>, TError = unknown>(vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigRuntimeVpnServerId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiOpenVpnServersPiHoleConfigRuntimeVpnServerIdQueryKey(vpnServerId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigRuntimeVpnServerId>>> = ({ signal }) => getApiOpenVpnServersPiHoleConfigRuntimeVpnServerId(vpnServerId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: vpnServerId !== null && vpnServerId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigRuntimeVpnServerId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiOpenVpnServersPiHoleConfigRuntimeVpnServerIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigRuntimeVpnServerId>>>
export type GetApiOpenVpnServersPiHoleConfigRuntimeVpnServerIdQueryError = unknown


export function useGetApiOpenVpnServersPiHoleConfigRuntimeVpnServerId<TData = Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigRuntimeVpnServerId>>, TError = unknown>(
 vpnServerId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigRuntimeVpnServerId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigRuntimeVpnServerId>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigRuntimeVpnServerId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiOpenVpnServersPiHoleConfigRuntimeVpnServerId<TData = Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigRuntimeVpnServerId>>, TError = unknown>(
 vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigRuntimeVpnServerId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigRuntimeVpnServerId>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigRuntimeVpnServerId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiOpenVpnServersPiHoleConfigRuntimeVpnServerId<TData = Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigRuntimeVpnServerId>>, TError = unknown>(
 vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigRuntimeVpnServerId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiOpenVpnServersPiHoleConfigRuntimeVpnServerId<TData = Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigRuntimeVpnServerId>>, TError = unknown>(
 vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigRuntimeVpnServerId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiOpenVpnServersPiHoleConfigRuntimeVpnServerIdQueryOptions(vpnServerId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiOpenVpnServersPiHoleConfigHealthcheck = (

 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiSystemString>(
      {url: `/api/open-vpn-servers/pi-hole-config/healthcheck`, method: 'GET', signal
    },
      options);
    }




export const getGetApiOpenVpnServersPiHoleConfigHealthcheckQueryKey = () => {
    return [
    `/api/open-vpn-servers/pi-hole-config/healthcheck`
    ] as const;
    }


export const getGetApiOpenVpnServersPiHoleConfigHealthcheckQueryOptions = <TData = Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheck>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheck>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiOpenVpnServersPiHoleConfigHealthcheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheck>>> = ({ signal }) => getApiOpenVpnServersPiHoleConfigHealthcheck(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheck>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiOpenVpnServersPiHoleConfigHealthcheckQueryResult = NonNullable<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheck>>>
export type GetApiOpenVpnServersPiHoleConfigHealthcheckQueryError = unknown


export function useGetApiOpenVpnServersPiHoleConfigHealthcheck<TData = Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheck>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheck>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiOpenVpnServersPiHoleConfigHealthcheck<TData = Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheck>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiOpenVpnServersPiHoleConfigHealthcheck<TData = Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheck>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiOpenVpnServersPiHoleConfigHealthcheck<TData = Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheck>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiOpenVpnServersPiHoleConfigHealthcheckQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiOpenVpnServersPiHoleConfigHealthcheckWithJwt = (

 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiSystemString>(
      {url: `/api/open-vpn-servers/pi-hole-config/healthcheck-with-jwt`, method: 'GET', signal
    },
      options);
    }




export const getGetApiOpenVpnServersPiHoleConfigHealthcheckWithJwtQueryKey = () => {
    return [
    `/api/open-vpn-servers/pi-hole-config/healthcheck-with-jwt`
    ] as const;
    }


export const getGetApiOpenVpnServersPiHoleConfigHealthcheckWithJwtQueryOptions = <TData = Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheckWithJwt>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheckWithJwt>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiOpenVpnServersPiHoleConfigHealthcheckWithJwtQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheckWithJwt>>> = ({ signal }) => getApiOpenVpnServersPiHoleConfigHealthcheckWithJwt(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheckWithJwt>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiOpenVpnServersPiHoleConfigHealthcheckWithJwtQueryResult = NonNullable<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheckWithJwt>>>
export type GetApiOpenVpnServersPiHoleConfigHealthcheckWithJwtQueryError = unknown


export function useGetApiOpenVpnServersPiHoleConfigHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheckWithJwt>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheckWithJwt>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheckWithJwt>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheckWithJwt>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiOpenVpnServersPiHoleConfigHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheckWithJwt>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheckWithJwt>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheckWithJwt>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheckWithJwt>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiOpenVpnServersPiHoleConfigHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheckWithJwt>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheckWithJwt>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiOpenVpnServersPiHoleConfigHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheckWithJwt>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiOpenVpnServersPiHoleConfigHealthcheckWithJwt>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiOpenVpnServersPiHoleConfigHealthcheckWithJwtQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






