/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiSystemString,
  ApiVpnServersResponsesVpnServerWithStatusesV3Response,
  ApiVpnServersResponsesVpnServersV3Response,
  GetApiV3OpenVpnServersGetAllParams,
  GetApiV3OpenVpnServersGetAllWithStatusParams
} from '../model';

import { ogmMutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getApiV3OpenVpnServersGetAll = (
    params?: GetApiV3OpenVpnServersGetAllParams,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiVpnServersResponsesVpnServersV3Response>(
      {url: `/api/v3/open-vpn-servers/get-all`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiV3OpenVpnServersGetAllQueryKey = (params?: GetApiV3OpenVpnServersGetAllParams,) => {
    return [
    `/api/v3/open-vpn-servers/get-all`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV3OpenVpnServersGetAllQueryOptions = <TData = Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAll>>, TError = unknown>(params?: GetApiV3OpenVpnServersGetAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAll>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV3OpenVpnServersGetAllQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAll>>> = ({ signal }) => getApiV3OpenVpnServersGetAll(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV3OpenVpnServersGetAllQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAll>>>
export type GetApiV3OpenVpnServersGetAllQueryError = unknown


export function useGetApiV3OpenVpnServersGetAll<TData = Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAll>>, TError = unknown>(
 params: undefined |  GetApiV3OpenVpnServersGetAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAll>>,
          TError,
          Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV3OpenVpnServersGetAll<TData = Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAll>>, TError = unknown>(
 params?: GetApiV3OpenVpnServersGetAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAll>>,
          TError,
          Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV3OpenVpnServersGetAll<TData = Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAll>>, TError = unknown>(
 params?: GetApiV3OpenVpnServersGetAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAll>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV3OpenVpnServersGetAll<TData = Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAll>>, TError = unknown>(
 params?: GetApiV3OpenVpnServersGetAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAll>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV3OpenVpnServersGetAllQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getApiV3OpenVpnServersGetAllWithStatus = (
    params?: GetApiV3OpenVpnServersGetAllWithStatusParams,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiVpnServersResponsesVpnServerWithStatusesV3Response>(
      {url: `/api/v3/open-vpn-servers/get-all-with-status`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiV3OpenVpnServersGetAllWithStatusQueryKey = (params?: GetApiV3OpenVpnServersGetAllWithStatusParams,) => {
    return [
    `/api/v3/open-vpn-servers/get-all-with-status`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV3OpenVpnServersGetAllWithStatusQueryOptions = <TData = Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAllWithStatus>>, TError = unknown>(params?: GetApiV3OpenVpnServersGetAllWithStatusParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAllWithStatus>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV3OpenVpnServersGetAllWithStatusQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAllWithStatus>>> = ({ signal }) => getApiV3OpenVpnServersGetAllWithStatus(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAllWithStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV3OpenVpnServersGetAllWithStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAllWithStatus>>>
export type GetApiV3OpenVpnServersGetAllWithStatusQueryError = unknown


export function useGetApiV3OpenVpnServersGetAllWithStatus<TData = Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAllWithStatus>>, TError = unknown>(
 params: undefined |  GetApiV3OpenVpnServersGetAllWithStatusParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAllWithStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAllWithStatus>>,
          TError,
          Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAllWithStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV3OpenVpnServersGetAllWithStatus<TData = Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAllWithStatus>>, TError = unknown>(
 params?: GetApiV3OpenVpnServersGetAllWithStatusParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAllWithStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAllWithStatus>>,
          TError,
          Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAllWithStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV3OpenVpnServersGetAllWithStatus<TData = Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAllWithStatus>>, TError = unknown>(
 params?: GetApiV3OpenVpnServersGetAllWithStatusParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAllWithStatus>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV3OpenVpnServersGetAllWithStatus<TData = Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAllWithStatus>>, TError = unknown>(
 params?: GetApiV3OpenVpnServersGetAllWithStatusParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV3OpenVpnServersGetAllWithStatus>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV3OpenVpnServersGetAllWithStatusQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getApiV3OpenVpnServersHealthcheck = (

 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiSystemString>(
      {url: `/api/v3/open-vpn-servers/healthcheck`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV3OpenVpnServersHealthcheckQueryKey = () => {
    return [
    `/api/v3/open-vpn-servers/healthcheck`
    ] as const;
    }


export const getGetApiV3OpenVpnServersHealthcheckQueryOptions = <TData = Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheck>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheck>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV3OpenVpnServersHealthcheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheck>>> = ({ signal }) => getApiV3OpenVpnServersHealthcheck(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheck>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV3OpenVpnServersHealthcheckQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheck>>>
export type GetApiV3OpenVpnServersHealthcheckQueryError = unknown


export function useGetApiV3OpenVpnServersHealthcheck<TData = Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheck>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheck>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV3OpenVpnServersHealthcheck<TData = Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheck>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV3OpenVpnServersHealthcheck<TData = Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheck>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV3OpenVpnServersHealthcheck<TData = Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheck>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV3OpenVpnServersHealthcheckQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getApiV3OpenVpnServersHealthcheckWithJwt = (

 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiSystemString>(
      {url: `/api/v3/open-vpn-servers/healthcheck-with-jwt`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV3OpenVpnServersHealthcheckWithJwtQueryKey = () => {
    return [
    `/api/v3/open-vpn-servers/healthcheck-with-jwt`
    ] as const;
    }


export const getGetApiV3OpenVpnServersHealthcheckWithJwtQueryOptions = <TData = Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheckWithJwt>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheckWithJwt>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV3OpenVpnServersHealthcheckWithJwtQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheckWithJwt>>> = ({ signal }) => getApiV3OpenVpnServersHealthcheckWithJwt(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheckWithJwt>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV3OpenVpnServersHealthcheckWithJwtQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheckWithJwt>>>
export type GetApiV3OpenVpnServersHealthcheckWithJwtQueryError = unknown


export function useGetApiV3OpenVpnServersHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheckWithJwt>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheckWithJwt>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheckWithJwt>>,
          TError,
          Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheckWithJwt>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV3OpenVpnServersHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheckWithJwt>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheckWithJwt>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheckWithJwt>>,
          TError,
          Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheckWithJwt>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV3OpenVpnServersHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheckWithJwt>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheckWithJwt>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV3OpenVpnServersHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheckWithJwt>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV3OpenVpnServersHealthcheckWithJwt>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV3OpenVpnServersHealthcheckWithJwtQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






