/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DataGate Monitor API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateOrUpdateQuotaPlanAllowedServerRequest,
  GetAllQuotaPlanAllowedServersResponseApiResponse,
  GetApiQuotaPlanAllowedServersGetAllParams,
  GetQuotaPlanAllowedServersByQuotaPlanIdResponseApiResponse,
  GetQuotaPlanAllowedServersByVpnServerIdResponseApiResponse,
  QuotaPlanAllowedServerResponseApiResponse,
  StringApiResponse,
} from ".././model";

import { ogmMutator } from "../../mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getApiQuotaPlanAllowedServersGetAll = (
  params?: GetApiQuotaPlanAllowedServersGetAllParams,
  options?: SecondParameter<typeof ogmMutator>,
  signal?: AbortSignal,
) => {
  return ogmMutator<GetAllQuotaPlanAllowedServersResponseApiResponse>(
    {
      url: `/api/quota-plan-allowed-servers/get-all`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

export const getGetApiQuotaPlanAllowedServersGetAllQueryKey = (
  params?: GetApiQuotaPlanAllowedServersGetAllParams,
) => {
  return [
    `/api/quota-plan-allowed-servers/get-all`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetApiQuotaPlanAllowedServersGetAllQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetAll>>,
  TError = unknown,
>(
  params?: GetApiQuotaPlanAllowedServersGetAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetApiQuotaPlanAllowedServersGetAllQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetAll>>
  > = ({ signal }) =>
    getApiQuotaPlanAllowedServersGetAll(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiQuotaPlanAllowedServersGetAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetAll>>
>;
export type GetApiQuotaPlanAllowedServersGetAllQueryError = unknown;

export function useGetApiQuotaPlanAllowedServersGetAll<
  TData = Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetAll>>,
  TError = unknown,
>(
  params: undefined | GetApiQuotaPlanAllowedServersGetAllParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetAll>>,
          TError,
          Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiQuotaPlanAllowedServersGetAll<
  TData = Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetAll>>,
  TError = unknown,
>(
  params?: GetApiQuotaPlanAllowedServersGetAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetAll>>,
          TError,
          Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiQuotaPlanAllowedServersGetAll<
  TData = Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetAll>>,
  TError = unknown,
>(
  params?: GetApiQuotaPlanAllowedServersGetAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiQuotaPlanAllowedServersGetAll<
  TData = Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetAll>>,
  TError = unknown,
>(
  params?: GetApiQuotaPlanAllowedServersGetAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiQuotaPlanAllowedServersGetAllQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiQuotaPlanAllowedServersGetId = (
  id: number,
  options?: SecondParameter<typeof ogmMutator>,
  signal?: AbortSignal,
) => {
  return ogmMutator<QuotaPlanAllowedServerResponseApiResponse>(
    { url: `/api/quota-plan-allowed-servers/get/${id}`, method: "GET", signal },
    options,
  );
};

export const getGetApiQuotaPlanAllowedServersGetIdQueryKey = (id?: number) => {
  return [`/api/quota-plan-allowed-servers/get/${id}`] as const;
};

export const getGetApiQuotaPlanAllowedServersGetIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetId>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiQuotaPlanAllowedServersGetIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetId>>
  > = ({ signal }) =>
    getApiQuotaPlanAllowedServersGetId(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiQuotaPlanAllowedServersGetIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetId>>
>;
export type GetApiQuotaPlanAllowedServersGetIdQueryError = unknown;

export function useGetApiQuotaPlanAllowedServersGetId<
  TData = Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetId>>,
  TError = unknown,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetId>>,
          TError,
          Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiQuotaPlanAllowedServersGetId<
  TData = Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetId>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetId>>,
          TError,
          Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiQuotaPlanAllowedServersGetId<
  TData = Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetId>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiQuotaPlanAllowedServersGetId<
  TData = Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetId>>,
  TError = unknown,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersGetId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiQuotaPlanAllowedServersGetIdQueryOptions(
    id,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanId = (
  quotaPlanId: number,
  options?: SecondParameter<typeof ogmMutator>,
  signal?: AbortSignal,
) => {
  return ogmMutator<GetQuotaPlanAllowedServersByQuotaPlanIdResponseApiResponse>(
    {
      url: `/api/quota-plan-allowed-servers/get-by-quota-plan-id/${quotaPlanId}`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getGetApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanIdQueryKey =
  (quotaPlanId?: number) => {
    return [
      `/api/quota-plan-allowed-servers/get-by-quota-plan-id/${quotaPlanId}`,
    ] as const;
  };

export const getGetApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanIdQueryOptions =
  <
    TData = Awaited<
      ReturnType<
        typeof getApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanId
      >
    >,
    TError = unknown,
  >(
    quotaPlanId: number,
    options?: {
      query?: Partial<
        UseQueryOptions<
          Awaited<
            ReturnType<
              typeof getApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanId
            >
          >,
          TError,
          TData
        >
      >;
      request?: SecondParameter<typeof ogmMutator>;
    },
  ) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
      queryOptions?.queryKey ??
      getGetApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanIdQueryKey(
        quotaPlanId,
      );

    const queryFn: QueryFunction<
      Awaited<
        ReturnType<
          typeof getApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanId
        >
      >
    > = ({ signal }) =>
      getApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanId(
        quotaPlanId,
        requestOptions,
        signal,
      );

    return {
      queryKey,
      queryFn,
      enabled: !!quotaPlanId,
      ...queryOptions,
    } as UseQueryOptions<
      Awaited<
        ReturnType<
          typeof getApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanId
        >
      >,
      TError,
      TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
  };

export type GetApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanIdQueryResult =
  NonNullable<
    Awaited<
      ReturnType<
        typeof getApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanId
      >
    >
  >;
export type GetApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanIdQueryError =
  unknown;

export function useGetApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanId<
  TData = Awaited<
    ReturnType<typeof getApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanId>
  >,
  TError = unknown,
>(
  quotaPlanId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof getApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanId
          >
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<
              typeof getApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanId
            >
          >,
          TError,
          Awaited<
            ReturnType<
              typeof getApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanId
            >
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanId<
  TData = Awaited<
    ReturnType<typeof getApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanId>
  >,
  TError = unknown,
>(
  quotaPlanId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof getApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanId
          >
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<
              typeof getApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanId
            >
          >,
          TError,
          Awaited<
            ReturnType<
              typeof getApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanId
            >
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanId<
  TData = Awaited<
    ReturnType<typeof getApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanId>
  >,
  TError = unknown,
>(
  quotaPlanId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof getApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanId
          >
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanId<
  TData = Awaited<
    ReturnType<typeof getApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanId>
  >,
  TError = unknown,
>(
  quotaPlanId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof getApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanId
          >
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetApiQuotaPlanAllowedServersGetByQuotaPlanIdQuotaPlanIdQueryOptions(
      quotaPlanId,
      options,
    );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerId = (
  vpnServerId: number,
  options?: SecondParameter<typeof ogmMutator>,
  signal?: AbortSignal,
) => {
  return ogmMutator<GetQuotaPlanAllowedServersByVpnServerIdResponseApiResponse>(
    {
      url: `/api/quota-plan-allowed-servers/get-by-vpn-server-id/${vpnServerId}`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getGetApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerIdQueryKey =
  (vpnServerId?: number) => {
    return [
      `/api/quota-plan-allowed-servers/get-by-vpn-server-id/${vpnServerId}`,
    ] as const;
  };

export const getGetApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerIdQueryOptions =
  <
    TData = Awaited<
      ReturnType<
        typeof getApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerId
      >
    >,
    TError = unknown,
  >(
    vpnServerId: number,
    options?: {
      query?: Partial<
        UseQueryOptions<
          Awaited<
            ReturnType<
              typeof getApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerId
            >
          >,
          TError,
          TData
        >
      >;
      request?: SecondParameter<typeof ogmMutator>;
    },
  ) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
      queryOptions?.queryKey ??
      getGetApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerIdQueryKey(
        vpnServerId,
      );

    const queryFn: QueryFunction<
      Awaited<
        ReturnType<
          typeof getApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerId
        >
      >
    > = ({ signal }) =>
      getApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerId(
        vpnServerId,
        requestOptions,
        signal,
      );

    return {
      queryKey,
      queryFn,
      enabled: !!vpnServerId,
      ...queryOptions,
    } as UseQueryOptions<
      Awaited<
        ReturnType<
          typeof getApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerId
        >
      >,
      TError,
      TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
  };

export type GetApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerIdQueryResult =
  NonNullable<
    Awaited<
      ReturnType<
        typeof getApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerId
      >
    >
  >;
export type GetApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerIdQueryError =
  unknown;

export function useGetApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerId<
  TData = Awaited<
    ReturnType<typeof getApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerId>
  >,
  TError = unknown,
>(
  vpnServerId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof getApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerId
          >
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<
              typeof getApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerId
            >
          >,
          TError,
          Awaited<
            ReturnType<
              typeof getApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerId
            >
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerId<
  TData = Awaited<
    ReturnType<typeof getApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerId>
  >,
  TError = unknown,
>(
  vpnServerId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof getApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerId
          >
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<
              typeof getApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerId
            >
          >,
          TError,
          Awaited<
            ReturnType<
              typeof getApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerId
            >
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerId<
  TData = Awaited<
    ReturnType<typeof getApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerId>
  >,
  TError = unknown,
>(
  vpnServerId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof getApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerId
          >
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerId<
  TData = Awaited<
    ReturnType<typeof getApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerId>
  >,
  TError = unknown,
>(
  vpnServerId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof getApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerId
          >
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetApiQuotaPlanAllowedServersGetByVpnServerIdVpnServerIdQueryOptions(
      vpnServerId,
      options,
    );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const postApiQuotaPlanAllowedServersCreate = (
  createOrUpdateQuotaPlanAllowedServerRequest: CreateOrUpdateQuotaPlanAllowedServerRequest,
  options?: SecondParameter<typeof ogmMutator>,
  signal?: AbortSignal,
) => {
  return ogmMutator<QuotaPlanAllowedServerResponseApiResponse>(
    {
      url: `/api/quota-plan-allowed-servers/create`,
      method: "POST",
      headers: { "Content-Type": "application/json-patch+json" },
      data: createOrUpdateQuotaPlanAllowedServerRequest,
      signal,
    },
    options,
  );
};

export const getPostApiQuotaPlanAllowedServersCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiQuotaPlanAllowedServersCreate>>,
    TError,
    { data: CreateOrUpdateQuotaPlanAllowedServerRequest },
    TContext
  >;
  request?: SecondParameter<typeof ogmMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiQuotaPlanAllowedServersCreate>>,
  TError,
  { data: CreateOrUpdateQuotaPlanAllowedServerRequest },
  TContext
> => {
  const mutationKey = ["postApiQuotaPlanAllowedServersCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiQuotaPlanAllowedServersCreate>>,
    { data: CreateOrUpdateQuotaPlanAllowedServerRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiQuotaPlanAllowedServersCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiQuotaPlanAllowedServersCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiQuotaPlanAllowedServersCreate>>
>;
export type PostApiQuotaPlanAllowedServersCreateMutationBody =
  CreateOrUpdateQuotaPlanAllowedServerRequest;
export type PostApiQuotaPlanAllowedServersCreateMutationError = unknown;

export const usePostApiQuotaPlanAllowedServersCreate = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiQuotaPlanAllowedServersCreate>>,
      TError,
      { data: CreateOrUpdateQuotaPlanAllowedServerRequest },
      TContext
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiQuotaPlanAllowedServersCreate>>,
  TError,
  { data: CreateOrUpdateQuotaPlanAllowedServerRequest },
  TContext
> => {
  const mutationOptions =
    getPostApiQuotaPlanAllowedServersCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const putApiQuotaPlanAllowedServersUpdate = (
  createOrUpdateQuotaPlanAllowedServerRequest: CreateOrUpdateQuotaPlanAllowedServerRequest,
  options?: SecondParameter<typeof ogmMutator>,
) => {
  return ogmMutator<StringApiResponse>(
    {
      url: `/api/quota-plan-allowed-servers/update`,
      method: "PUT",
      headers: { "Content-Type": "application/json-patch+json" },
      data: createOrUpdateQuotaPlanAllowedServerRequest,
    },
    options,
  );
};

export const getPutApiQuotaPlanAllowedServersUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiQuotaPlanAllowedServersUpdate>>,
    TError,
    { data: CreateOrUpdateQuotaPlanAllowedServerRequest },
    TContext
  >;
  request?: SecondParameter<typeof ogmMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiQuotaPlanAllowedServersUpdate>>,
  TError,
  { data: CreateOrUpdateQuotaPlanAllowedServerRequest },
  TContext
> => {
  const mutationKey = ["putApiQuotaPlanAllowedServersUpdate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiQuotaPlanAllowedServersUpdate>>,
    { data: CreateOrUpdateQuotaPlanAllowedServerRequest }
  > = (props) => {
    const { data } = props ?? {};

    return putApiQuotaPlanAllowedServersUpdate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiQuotaPlanAllowedServersUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiQuotaPlanAllowedServersUpdate>>
>;
export type PutApiQuotaPlanAllowedServersUpdateMutationBody =
  CreateOrUpdateQuotaPlanAllowedServerRequest;
export type PutApiQuotaPlanAllowedServersUpdateMutationError = unknown;

export const usePutApiQuotaPlanAllowedServersUpdate = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiQuotaPlanAllowedServersUpdate>>,
      TError,
      { data: CreateOrUpdateQuotaPlanAllowedServerRequest },
      TContext
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiQuotaPlanAllowedServersUpdate>>,
  TError,
  { data: CreateOrUpdateQuotaPlanAllowedServerRequest },
  TContext
> => {
  const mutationOptions =
    getPutApiQuotaPlanAllowedServersUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteApiQuotaPlanAllowedServersDeleteId = (
  id: number,
  options?: SecondParameter<typeof ogmMutator>,
) => {
  return ogmMutator<StringApiResponse>(
    { url: `/api/quota-plan-allowed-servers/delete/${id}`, method: "DELETE" },
    options,
  );
};

export const getDeleteApiQuotaPlanAllowedServersDeleteIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiQuotaPlanAllowedServersDeleteId>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof ogmMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiQuotaPlanAllowedServersDeleteId>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteApiQuotaPlanAllowedServersDeleteId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiQuotaPlanAllowedServersDeleteId>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiQuotaPlanAllowedServersDeleteId(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiQuotaPlanAllowedServersDeleteIdMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof deleteApiQuotaPlanAllowedServersDeleteId>>
  >;

export type DeleteApiQuotaPlanAllowedServersDeleteIdMutationError = unknown;

export const useDeleteApiQuotaPlanAllowedServersDeleteId = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiQuotaPlanAllowedServersDeleteId>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiQuotaPlanAllowedServersDeleteId>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions =
    getDeleteApiQuotaPlanAllowedServersDeleteIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getApiQuotaPlanAllowedServersHealthcheck = (
  options?: SecondParameter<typeof ogmMutator>,
  signal?: AbortSignal,
) => {
  return ogmMutator<StringApiResponse>(
    {
      url: `/api/quota-plan-allowed-servers/healthcheck`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getGetApiQuotaPlanAllowedServersHealthcheckQueryKey = () => {
  return [`/api/quota-plan-allowed-servers/healthcheck`] as const;
};

export const getGetApiQuotaPlanAllowedServersHealthcheckQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheck>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheck>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof ogmMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetApiQuotaPlanAllowedServersHealthcheckQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheck>>
  > = ({ signal }) =>
    getApiQuotaPlanAllowedServersHealthcheck(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheck>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiQuotaPlanAllowedServersHealthcheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheck>>
>;
export type GetApiQuotaPlanAllowedServersHealthcheckQueryError = unknown;

export function useGetApiQuotaPlanAllowedServersHealthcheck<
  TData = Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheck>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheck>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheck>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiQuotaPlanAllowedServersHealthcheck<
  TData = Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheck>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheck>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiQuotaPlanAllowedServersHealthcheck<
  TData = Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheck>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiQuotaPlanAllowedServersHealthcheck<
  TData = Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheck>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetApiQuotaPlanAllowedServersHealthcheckQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiQuotaPlanAllowedServersHealthcheckWithJwt = (
  options?: SecondParameter<typeof ogmMutator>,
  signal?: AbortSignal,
) => {
  return ogmMutator<StringApiResponse>(
    {
      url: `/api/quota-plan-allowed-servers/healthcheck-with-jwt`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getGetApiQuotaPlanAllowedServersHealthcheckWithJwtQueryKey =
  () => {
    return [`/api/quota-plan-allowed-servers/healthcheck-with-jwt`] as const;
  };

export const getGetApiQuotaPlanAllowedServersHealthcheckWithJwtQueryOptions = <
  TData = Awaited<
    ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheckWithJwt>
  >,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<
        ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheckWithJwt>
      >,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof ogmMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetApiQuotaPlanAllowedServersHealthcheckWithJwtQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheckWithJwt>>
  > = ({ signal }) =>
    getApiQuotaPlanAllowedServersHealthcheckWithJwt(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheckWithJwt>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiQuotaPlanAllowedServersHealthcheckWithJwtQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheckWithJwt>>
  >;
export type GetApiQuotaPlanAllowedServersHealthcheckWithJwtQueryError = unknown;

export function useGetApiQuotaPlanAllowedServersHealthcheckWithJwt<
  TData = Awaited<
    ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheckWithJwt>
  >,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheckWithJwt>
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheckWithJwt>
          >,
          TError,
          Awaited<
            ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheckWithJwt>
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiQuotaPlanAllowedServersHealthcheckWithJwt<
  TData = Awaited<
    ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheckWithJwt>
  >,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheckWithJwt>
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheckWithJwt>
          >,
          TError,
          Awaited<
            ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheckWithJwt>
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiQuotaPlanAllowedServersHealthcheckWithJwt<
  TData = Awaited<
    ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheckWithJwt>
  >,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheckWithJwt>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiQuotaPlanAllowedServersHealthcheckWithJwt<
  TData = Awaited<
    ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheckWithJwt>
  >,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getApiQuotaPlanAllowedServersHealthcheckWithJwt>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetApiQuotaPlanAllowedServersHealthcheckWithJwtQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
