/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiSystemObject,
  ApiSystemString,
  XrayNodeRequestsXrayNodeUserActionRequest
} from '../model';

import { ogmMutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const postApiVpnServersVpnServerIdXrayKickUser = (
    vpnServerId: number,
    xrayNodeRequestsXrayNodeUserActionRequest?: XrayNodeRequestsXrayNodeUserActionRequest,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiSystemObject>(
      {url: `/api/vpn-servers/${vpnServerId}/xray/kick-user`, method: 'POST',
      headers: {'Content-Type': 'application/json-patch+json', },
      data: xrayNodeRequestsXrayNodeUserActionRequest, signal
    },
      options);
    }



export const getPostApiVpnServersVpnServerIdXrayKickUserMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiVpnServersVpnServerIdXrayKickUser>>, TError,{vpnServerId: number;data?: XrayNodeRequestsXrayNodeUserActionRequest}, TContext>, request?: SecondParameter<typeof ogmMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiVpnServersVpnServerIdXrayKickUser>>, TError,{vpnServerId: number;data?: XrayNodeRequestsXrayNodeUserActionRequest}, TContext> => {

const mutationKey = ['postApiVpnServersVpnServerIdXrayKickUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiVpnServersVpnServerIdXrayKickUser>>, {vpnServerId: number;data?: XrayNodeRequestsXrayNodeUserActionRequest}> = (props) => {
          const {vpnServerId,data} = props ?? {};

          return  postApiVpnServersVpnServerIdXrayKickUser(vpnServerId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiVpnServersVpnServerIdXrayKickUserMutationResult = NonNullable<Awaited<ReturnType<typeof postApiVpnServersVpnServerIdXrayKickUser>>>
    export type PostApiVpnServersVpnServerIdXrayKickUserMutationBody = XrayNodeRequestsXrayNodeUserActionRequest | undefined
    export type PostApiVpnServersVpnServerIdXrayKickUserMutationError = unknown

    export const usePostApiVpnServersVpnServerIdXrayKickUser = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiVpnServersVpnServerIdXrayKickUser>>, TError,{vpnServerId: number;data?: XrayNodeRequestsXrayNodeUserActionRequest}, TContext>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiVpnServersVpnServerIdXrayKickUser>>,
        TError,
        {vpnServerId: number;data?: XrayNodeRequestsXrayNodeUserActionRequest},
        TContext
      > => {
      return useMutation(getPostApiVpnServersVpnServerIdXrayKickUserMutationOptions(options), queryClient);
    }
    export const postApiVpnServersVpnServerIdXrayDisableUser = (
    vpnServerId: number,
    xrayNodeRequestsXrayNodeUserActionRequest?: XrayNodeRequestsXrayNodeUserActionRequest,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiSystemObject>(
      {url: `/api/vpn-servers/${vpnServerId}/xray/disable-user`, method: 'POST',
      headers: {'Content-Type': 'application/json-patch+json', },
      data: xrayNodeRequestsXrayNodeUserActionRequest, signal
    },
      options);
    }



export const getPostApiVpnServersVpnServerIdXrayDisableUserMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiVpnServersVpnServerIdXrayDisableUser>>, TError,{vpnServerId: number;data?: XrayNodeRequestsXrayNodeUserActionRequest}, TContext>, request?: SecondParameter<typeof ogmMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiVpnServersVpnServerIdXrayDisableUser>>, TError,{vpnServerId: number;data?: XrayNodeRequestsXrayNodeUserActionRequest}, TContext> => {

const mutationKey = ['postApiVpnServersVpnServerIdXrayDisableUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiVpnServersVpnServerIdXrayDisableUser>>, {vpnServerId: number;data?: XrayNodeRequestsXrayNodeUserActionRequest}> = (props) => {
          const {vpnServerId,data} = props ?? {};

          return  postApiVpnServersVpnServerIdXrayDisableUser(vpnServerId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiVpnServersVpnServerIdXrayDisableUserMutationResult = NonNullable<Awaited<ReturnType<typeof postApiVpnServersVpnServerIdXrayDisableUser>>>
    export type PostApiVpnServersVpnServerIdXrayDisableUserMutationBody = XrayNodeRequestsXrayNodeUserActionRequest | undefined
    export type PostApiVpnServersVpnServerIdXrayDisableUserMutationError = unknown

    export const usePostApiVpnServersVpnServerIdXrayDisableUser = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiVpnServersVpnServerIdXrayDisableUser>>, TError,{vpnServerId: number;data?: XrayNodeRequestsXrayNodeUserActionRequest}, TContext>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiVpnServersVpnServerIdXrayDisableUser>>,
        TError,
        {vpnServerId: number;data?: XrayNodeRequestsXrayNodeUserActionRequest},
        TContext
      > => {
      return useMutation(getPostApiVpnServersVpnServerIdXrayDisableUserMutationOptions(options), queryClient);
    }
    export const getApiVpnServersVpnServerIdXrayHealthcheck = (
    vpnServerId: string,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiSystemString>(
      {url: `/api/vpn-servers/${vpnServerId}/xray/healthcheck`, method: 'GET', signal
    },
      options);
    }




export const getGetApiVpnServersVpnServerIdXrayHealthcheckQueryKey = (vpnServerId: string,) => {
    return [
    `/api/vpn-servers/${vpnServerId}/xray/healthcheck`
    ] as const;
    }


export const getGetApiVpnServersVpnServerIdXrayHealthcheckQueryOptions = <TData = Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheck>>, TError = unknown>(vpnServerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheck>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiVpnServersVpnServerIdXrayHealthcheckQueryKey(vpnServerId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheck>>> = ({ signal }) => getApiVpnServersVpnServerIdXrayHealthcheck(vpnServerId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: vpnServerId !== null && vpnServerId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheck>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiVpnServersVpnServerIdXrayHealthcheckQueryResult = NonNullable<Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheck>>>
export type GetApiVpnServersVpnServerIdXrayHealthcheckQueryError = unknown


export function useGetApiVpnServersVpnServerIdXrayHealthcheck<TData = Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheck>>, TError = unknown>(
 vpnServerId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheck>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiVpnServersVpnServerIdXrayHealthcheck<TData = Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheck>>, TError = unknown>(
 vpnServerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheck>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiVpnServersVpnServerIdXrayHealthcheck<TData = Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheck>>, TError = unknown>(
 vpnServerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheck>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiVpnServersVpnServerIdXrayHealthcheck<TData = Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheck>>, TError = unknown>(
 vpnServerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheck>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiVpnServersVpnServerIdXrayHealthcheckQueryOptions(vpnServerId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getApiVpnServersVpnServerIdXrayHealthcheckWithJwt = (
    vpnServerId: string,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiSystemString>(
      {url: `/api/vpn-servers/${vpnServerId}/xray/healthcheck-with-jwt`, method: 'GET', signal
    },
      options);
    }




export const getGetApiVpnServersVpnServerIdXrayHealthcheckWithJwtQueryKey = (vpnServerId: string,) => {
    return [
    `/api/vpn-servers/${vpnServerId}/xray/healthcheck-with-jwt`
    ] as const;
    }


export const getGetApiVpnServersVpnServerIdXrayHealthcheckWithJwtQueryOptions = <TData = Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheckWithJwt>>, TError = unknown>(vpnServerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheckWithJwt>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiVpnServersVpnServerIdXrayHealthcheckWithJwtQueryKey(vpnServerId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheckWithJwt>>> = ({ signal }) => getApiVpnServersVpnServerIdXrayHealthcheckWithJwt(vpnServerId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: vpnServerId !== null && vpnServerId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheckWithJwt>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiVpnServersVpnServerIdXrayHealthcheckWithJwtQueryResult = NonNullable<Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheckWithJwt>>>
export type GetApiVpnServersVpnServerIdXrayHealthcheckWithJwtQueryError = unknown


export function useGetApiVpnServersVpnServerIdXrayHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheckWithJwt>>, TError = unknown>(
 vpnServerId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheckWithJwt>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheckWithJwt>>,
          TError,
          Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheckWithJwt>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiVpnServersVpnServerIdXrayHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheckWithJwt>>, TError = unknown>(
 vpnServerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheckWithJwt>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheckWithJwt>>,
          TError,
          Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheckWithJwt>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiVpnServersVpnServerIdXrayHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheckWithJwt>>, TError = unknown>(
 vpnServerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheckWithJwt>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiVpnServersVpnServerIdXrayHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheckWithJwt>>, TError = unknown>(
 vpnServerId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiVpnServersVpnServerIdXrayHealthcheckWithJwt>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiVpnServersVpnServerIdXrayHealthcheckWithJwtQueryOptions(vpnServerId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






