/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DataGate Monitor API
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BooleanApiResponse,
  GetAdminsResponseApiResponse,
  GetAllTelegramUsersResponseApiResponse,
  StringApiResponse,
  TelegramUserActionRequest,
  UserRequestApiResponse,
} from ".././model";

import { ogmMutator } from "../../mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getApiTgbotUsersCheckExistsTelegramId = (
  telegramId: number,
  options?: SecondParameter<typeof ogmMutator>,
  signal?: AbortSignal,
) => {
  return ogmMutator<BooleanApiResponse>(
    {
      url: `/api/tgbot-users/check-exists/${telegramId}`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getGetApiTgbotUsersCheckExistsTelegramIdQueryKey = (
  telegramId?: number,
) => {
  return [`/api/tgbot-users/check-exists/${telegramId}`] as const;
};

export const getGetApiTgbotUsersCheckExistsTelegramIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiTgbotUsersCheckExistsTelegramId>>,
  TError = unknown,
>(
  telegramId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersCheckExistsTelegramId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetApiTgbotUsersCheckExistsTelegramIdQueryKey(telegramId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiTgbotUsersCheckExistsTelegramId>>
  > = ({ signal }) =>
    getApiTgbotUsersCheckExistsTelegramId(telegramId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!telegramId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiTgbotUsersCheckExistsTelegramId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiTgbotUsersCheckExistsTelegramIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiTgbotUsersCheckExistsTelegramId>>
>;
export type GetApiTgbotUsersCheckExistsTelegramIdQueryError = unknown;

export function useGetApiTgbotUsersCheckExistsTelegramId<
  TData = Awaited<ReturnType<typeof getApiTgbotUsersCheckExistsTelegramId>>,
  TError = unknown,
>(
  telegramId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersCheckExistsTelegramId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTgbotUsersCheckExistsTelegramId>>,
          TError,
          Awaited<ReturnType<typeof getApiTgbotUsersCheckExistsTelegramId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiTgbotUsersCheckExistsTelegramId<
  TData = Awaited<ReturnType<typeof getApiTgbotUsersCheckExistsTelegramId>>,
  TError = unknown,
>(
  telegramId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersCheckExistsTelegramId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTgbotUsersCheckExistsTelegramId>>,
          TError,
          Awaited<ReturnType<typeof getApiTgbotUsersCheckExistsTelegramId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiTgbotUsersCheckExistsTelegramId<
  TData = Awaited<ReturnType<typeof getApiTgbotUsersCheckExistsTelegramId>>,
  TError = unknown,
>(
  telegramId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersCheckExistsTelegramId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiTgbotUsersCheckExistsTelegramId<
  TData = Awaited<ReturnType<typeof getApiTgbotUsersCheckExistsTelegramId>>,
  TError = unknown,
>(
  telegramId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersCheckExistsTelegramId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiTgbotUsersCheckExistsTelegramIdQueryOptions(
    telegramId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiTgbotUsersGetTelegramId = (
  telegramId: number,
  options?: SecondParameter<typeof ogmMutator>,
  signal?: AbortSignal,
) => {
  return ogmMutator<UserRequestApiResponse>(
    { url: `/api/tgbot-users/get/${telegramId}`, method: "GET", signal },
    options,
  );
};

export const getGetApiTgbotUsersGetTelegramIdQueryKey = (
  telegramId?: number,
) => {
  return [`/api/tgbot-users/get/${telegramId}`] as const;
};

export const getGetApiTgbotUsersGetTelegramIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiTgbotUsersGetTelegramId>>,
  TError = unknown,
>(
  telegramId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersGetTelegramId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetApiTgbotUsersGetTelegramIdQueryKey(telegramId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiTgbotUsersGetTelegramId>>
  > = ({ signal }) =>
    getApiTgbotUsersGetTelegramId(telegramId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!telegramId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiTgbotUsersGetTelegramId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiTgbotUsersGetTelegramIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiTgbotUsersGetTelegramId>>
>;
export type GetApiTgbotUsersGetTelegramIdQueryError = unknown;

export function useGetApiTgbotUsersGetTelegramId<
  TData = Awaited<ReturnType<typeof getApiTgbotUsersGetTelegramId>>,
  TError = unknown,
>(
  telegramId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersGetTelegramId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTgbotUsersGetTelegramId>>,
          TError,
          Awaited<ReturnType<typeof getApiTgbotUsersGetTelegramId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiTgbotUsersGetTelegramId<
  TData = Awaited<ReturnType<typeof getApiTgbotUsersGetTelegramId>>,
  TError = unknown,
>(
  telegramId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersGetTelegramId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTgbotUsersGetTelegramId>>,
          TError,
          Awaited<ReturnType<typeof getApiTgbotUsersGetTelegramId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiTgbotUsersGetTelegramId<
  TData = Awaited<ReturnType<typeof getApiTgbotUsersGetTelegramId>>,
  TError = unknown,
>(
  telegramId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersGetTelegramId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiTgbotUsersGetTelegramId<
  TData = Awaited<ReturnType<typeof getApiTgbotUsersGetTelegramId>>,
  TError = unknown,
>(
  telegramId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersGetTelegramId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiTgbotUsersGetTelegramIdQueryOptions(
    telegramId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiTgbotUsersGetAdmins = (
  options?: SecondParameter<typeof ogmMutator>,
  signal?: AbortSignal,
) => {
  return ogmMutator<GetAdminsResponseApiResponse>(
    { url: `/api/tgbot-users/get-admins`, method: "GET", signal },
    options,
  );
};

export const getGetApiTgbotUsersGetAdminsQueryKey = () => {
  return [`/api/tgbot-users/get-admins`] as const;
};

export const getGetApiTgbotUsersGetAdminsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiTgbotUsersGetAdmins>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiTgbotUsersGetAdmins>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof ogmMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiTgbotUsersGetAdminsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiTgbotUsersGetAdmins>>
  > = ({ signal }) => getApiTgbotUsersGetAdmins(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiTgbotUsersGetAdmins>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiTgbotUsersGetAdminsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiTgbotUsersGetAdmins>>
>;
export type GetApiTgbotUsersGetAdminsQueryError = unknown;

export function useGetApiTgbotUsersGetAdmins<
  TData = Awaited<ReturnType<typeof getApiTgbotUsersGetAdmins>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersGetAdmins>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTgbotUsersGetAdmins>>,
          TError,
          Awaited<ReturnType<typeof getApiTgbotUsersGetAdmins>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiTgbotUsersGetAdmins<
  TData = Awaited<ReturnType<typeof getApiTgbotUsersGetAdmins>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersGetAdmins>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTgbotUsersGetAdmins>>,
          TError,
          Awaited<ReturnType<typeof getApiTgbotUsersGetAdmins>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiTgbotUsersGetAdmins<
  TData = Awaited<ReturnType<typeof getApiTgbotUsersGetAdmins>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersGetAdmins>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiTgbotUsersGetAdmins<
  TData = Awaited<ReturnType<typeof getApiTgbotUsersGetAdmins>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersGetAdmins>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiTgbotUsersGetAdminsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiTgbotUsersGetAll = (
  options?: SecondParameter<typeof ogmMutator>,
  signal?: AbortSignal,
) => {
  return ogmMutator<GetAllTelegramUsersResponseApiResponse>(
    { url: `/api/tgbot-users/get-all`, method: "GET", signal },
    options,
  );
};

export const getGetApiTgbotUsersGetAllQueryKey = () => {
  return [`/api/tgbot-users/get-all`] as const;
};

export const getGetApiTgbotUsersGetAllQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiTgbotUsersGetAll>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiTgbotUsersGetAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof ogmMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiTgbotUsersGetAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiTgbotUsersGetAll>>
  > = ({ signal }) => getApiTgbotUsersGetAll(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiTgbotUsersGetAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiTgbotUsersGetAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiTgbotUsersGetAll>>
>;
export type GetApiTgbotUsersGetAllQueryError = unknown;

export function useGetApiTgbotUsersGetAll<
  TData = Awaited<ReturnType<typeof getApiTgbotUsersGetAll>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersGetAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTgbotUsersGetAll>>,
          TError,
          Awaited<ReturnType<typeof getApiTgbotUsersGetAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiTgbotUsersGetAll<
  TData = Awaited<ReturnType<typeof getApiTgbotUsersGetAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersGetAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTgbotUsersGetAll>>,
          TError,
          Awaited<ReturnType<typeof getApiTgbotUsersGetAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiTgbotUsersGetAll<
  TData = Awaited<ReturnType<typeof getApiTgbotUsersGetAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersGetAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiTgbotUsersGetAll<
  TData = Awaited<ReturnType<typeof getApiTgbotUsersGetAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersGetAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiTgbotUsersGetAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const postApiTgbotUsersBlock = (
  telegramUserActionRequest: TelegramUserActionRequest,
  options?: SecondParameter<typeof ogmMutator>,
  signal?: AbortSignal,
) => {
  return ogmMutator<BooleanApiResponse>(
    {
      url: `/api/tgbot-users/block`,
      method: "POST",
      headers: { "Content-Type": "application/json-patch+json" },
      data: telegramUserActionRequest,
      signal,
    },
    options,
  );
};

export const getPostApiTgbotUsersBlockMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiTgbotUsersBlock>>,
    TError,
    { data: TelegramUserActionRequest },
    TContext
  >;
  request?: SecondParameter<typeof ogmMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiTgbotUsersBlock>>,
  TError,
  { data: TelegramUserActionRequest },
  TContext
> => {
  const mutationKey = ["postApiTgbotUsersBlock"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiTgbotUsersBlock>>,
    { data: TelegramUserActionRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiTgbotUsersBlock(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiTgbotUsersBlockMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiTgbotUsersBlock>>
>;
export type PostApiTgbotUsersBlockMutationBody = TelegramUserActionRequest;
export type PostApiTgbotUsersBlockMutationError = unknown;

export const usePostApiTgbotUsersBlock = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiTgbotUsersBlock>>,
      TError,
      { data: TelegramUserActionRequest },
      TContext
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiTgbotUsersBlock>>,
  TError,
  { data: TelegramUserActionRequest },
  TContext
> => {
  const mutationOptions = getPostApiTgbotUsersBlockMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const postApiTgbotUsersUnblock = (
  telegramUserActionRequest: TelegramUserActionRequest,
  options?: SecondParameter<typeof ogmMutator>,
  signal?: AbortSignal,
) => {
  return ogmMutator<BooleanApiResponse>(
    {
      url: `/api/tgbot-users/unblock`,
      method: "POST",
      headers: { "Content-Type": "application/json-patch+json" },
      data: telegramUserActionRequest,
      signal,
    },
    options,
  );
};

export const getPostApiTgbotUsersUnblockMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiTgbotUsersUnblock>>,
    TError,
    { data: TelegramUserActionRequest },
    TContext
  >;
  request?: SecondParameter<typeof ogmMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiTgbotUsersUnblock>>,
  TError,
  { data: TelegramUserActionRequest },
  TContext
> => {
  const mutationKey = ["postApiTgbotUsersUnblock"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiTgbotUsersUnblock>>,
    { data: TelegramUserActionRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiTgbotUsersUnblock(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiTgbotUsersUnblockMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiTgbotUsersUnblock>>
>;
export type PostApiTgbotUsersUnblockMutationBody = TelegramUserActionRequest;
export type PostApiTgbotUsersUnblockMutationError = unknown;

export const usePostApiTgbotUsersUnblock = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiTgbotUsersUnblock>>,
      TError,
      { data: TelegramUserActionRequest },
      TContext
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiTgbotUsersUnblock>>,
  TError,
  { data: TelegramUserActionRequest },
  TContext
> => {
  const mutationOptions = getPostApiTgbotUsersUnblockMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const postApiTgbotUsersSetAdmin = (
  telegramUserActionRequest: TelegramUserActionRequest,
  options?: SecondParameter<typeof ogmMutator>,
  signal?: AbortSignal,
) => {
  return ogmMutator<BooleanApiResponse>(
    {
      url: `/api/tgbot-users/set-admin`,
      method: "POST",
      headers: { "Content-Type": "application/json-patch+json" },
      data: telegramUserActionRequest,
      signal,
    },
    options,
  );
};

export const getPostApiTgbotUsersSetAdminMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiTgbotUsersSetAdmin>>,
    TError,
    { data: TelegramUserActionRequest },
    TContext
  >;
  request?: SecondParameter<typeof ogmMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiTgbotUsersSetAdmin>>,
  TError,
  { data: TelegramUserActionRequest },
  TContext
> => {
  const mutationKey = ["postApiTgbotUsersSetAdmin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiTgbotUsersSetAdmin>>,
    { data: TelegramUserActionRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiTgbotUsersSetAdmin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiTgbotUsersSetAdminMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiTgbotUsersSetAdmin>>
>;
export type PostApiTgbotUsersSetAdminMutationBody = TelegramUserActionRequest;
export type PostApiTgbotUsersSetAdminMutationError = unknown;

export const usePostApiTgbotUsersSetAdmin = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiTgbotUsersSetAdmin>>,
      TError,
      { data: TelegramUserActionRequest },
      TContext
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiTgbotUsersSetAdmin>>,
  TError,
  { data: TelegramUserActionRequest },
  TContext
> => {
  const mutationOptions = getPostApiTgbotUsersSetAdminMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const postApiTgbotUsersUnsetAdmin = (
  telegramUserActionRequest: TelegramUserActionRequest,
  options?: SecondParameter<typeof ogmMutator>,
  signal?: AbortSignal,
) => {
  return ogmMutator<BooleanApiResponse>(
    {
      url: `/api/tgbot-users/unset-admin`,
      method: "POST",
      headers: { "Content-Type": "application/json-patch+json" },
      data: telegramUserActionRequest,
      signal,
    },
    options,
  );
};

export const getPostApiTgbotUsersUnsetAdminMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiTgbotUsersUnsetAdmin>>,
    TError,
    { data: TelegramUserActionRequest },
    TContext
  >;
  request?: SecondParameter<typeof ogmMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiTgbotUsersUnsetAdmin>>,
  TError,
  { data: TelegramUserActionRequest },
  TContext
> => {
  const mutationKey = ["postApiTgbotUsersUnsetAdmin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiTgbotUsersUnsetAdmin>>,
    { data: TelegramUserActionRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiTgbotUsersUnsetAdmin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiTgbotUsersUnsetAdminMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiTgbotUsersUnsetAdmin>>
>;
export type PostApiTgbotUsersUnsetAdminMutationBody = TelegramUserActionRequest;
export type PostApiTgbotUsersUnsetAdminMutationError = unknown;

export const usePostApiTgbotUsersUnsetAdmin = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiTgbotUsersUnsetAdmin>>,
      TError,
      { data: TelegramUserActionRequest },
      TContext
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiTgbotUsersUnsetAdmin>>,
  TError,
  { data: TelegramUserActionRequest },
  TContext
> => {
  const mutationOptions =
    getPostApiTgbotUsersUnsetAdminMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getApiTgbotUsersHealthcheck = (
  options?: SecondParameter<typeof ogmMutator>,
  signal?: AbortSignal,
) => {
  return ogmMutator<StringApiResponse>(
    { url: `/api/tgbot-users/healthcheck`, method: "GET", signal },
    options,
  );
};

export const getGetApiTgbotUsersHealthcheckQueryKey = () => {
  return [`/api/tgbot-users/healthcheck`] as const;
};

export const getGetApiTgbotUsersHealthcheckQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiTgbotUsersHealthcheck>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiTgbotUsersHealthcheck>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof ogmMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiTgbotUsersHealthcheckQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiTgbotUsersHealthcheck>>
  > = ({ signal }) => getApiTgbotUsersHealthcheck(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiTgbotUsersHealthcheck>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiTgbotUsersHealthcheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiTgbotUsersHealthcheck>>
>;
export type GetApiTgbotUsersHealthcheckQueryError = unknown;

export function useGetApiTgbotUsersHealthcheck<
  TData = Awaited<ReturnType<typeof getApiTgbotUsersHealthcheck>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersHealthcheck>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTgbotUsersHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiTgbotUsersHealthcheck>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiTgbotUsersHealthcheck<
  TData = Awaited<ReturnType<typeof getApiTgbotUsersHealthcheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersHealthcheck>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTgbotUsersHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiTgbotUsersHealthcheck>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiTgbotUsersHealthcheck<
  TData = Awaited<ReturnType<typeof getApiTgbotUsersHealthcheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersHealthcheck>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiTgbotUsersHealthcheck<
  TData = Awaited<ReturnType<typeof getApiTgbotUsersHealthcheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersHealthcheck>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiTgbotUsersHealthcheckQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiTgbotUsersHealthcheckWithJwt = (
  options?: SecondParameter<typeof ogmMutator>,
  signal?: AbortSignal,
) => {
  return ogmMutator<StringApiResponse>(
    { url: `/api/tgbot-users/healthcheck-with-jwt`, method: "GET", signal },
    options,
  );
};

export const getGetApiTgbotUsersHealthcheckWithJwtQueryKey = () => {
  return [`/api/tgbot-users/healthcheck-with-jwt`] as const;
};

export const getGetApiTgbotUsersHealthcheckWithJwtQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiTgbotUsersHealthcheckWithJwt>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiTgbotUsersHealthcheckWithJwt>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof ogmMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiTgbotUsersHealthcheckWithJwtQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiTgbotUsersHealthcheckWithJwt>>
  > = ({ signal }) =>
    getApiTgbotUsersHealthcheckWithJwt(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiTgbotUsersHealthcheckWithJwt>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiTgbotUsersHealthcheckWithJwtQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiTgbotUsersHealthcheckWithJwt>>
>;
export type GetApiTgbotUsersHealthcheckWithJwtQueryError = unknown;

export function useGetApiTgbotUsersHealthcheckWithJwt<
  TData = Awaited<ReturnType<typeof getApiTgbotUsersHealthcheckWithJwt>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersHealthcheckWithJwt>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTgbotUsersHealthcheckWithJwt>>,
          TError,
          Awaited<ReturnType<typeof getApiTgbotUsersHealthcheckWithJwt>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiTgbotUsersHealthcheckWithJwt<
  TData = Awaited<ReturnType<typeof getApiTgbotUsersHealthcheckWithJwt>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersHealthcheckWithJwt>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTgbotUsersHealthcheckWithJwt>>,
          TError,
          Awaited<ReturnType<typeof getApiTgbotUsersHealthcheckWithJwt>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiTgbotUsersHealthcheckWithJwt<
  TData = Awaited<ReturnType<typeof getApiTgbotUsersHealthcheckWithJwt>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersHealthcheckWithJwt>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiTgbotUsersHealthcheckWithJwt<
  TData = Awaited<ReturnType<typeof getApiTgbotUsersHealthcheckWithJwt>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiTgbotUsersHealthcheckWithJwt>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetApiTgbotUsersHealthcheckWithJwtQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
