/**
 * Stable names for app code. Orval regenerates `orval/model` with long C#-style names;
 * this module re-exports them under the legacy short names used across the UI.
 */
export * from "./orval/model";

export type { OpenVpnFilesRequestsAddFileRequest as AddFileRequest } from "./orval/model/openVpnFilesRequestsAddFileRequest";
export type { AuthRequestsAdminForgotPasswordRequest as AdminForgotPasswordRequest } from "./orval/model/authRequestsAdminForgotPasswordRequest";
export type { AuthRequestsAdminResetPasswordRequest as AdminResetPasswordRequest } from "./orval/model/authRequestsAdminResetPasswordRequest";
export type { ApplicationsDtoApplicationDto as ApplicationDto } from "./orval/model/applicationsDtoApplicationDto";
export type { VpnServerCertsRequestsBuildCertificateRequest as BuildCertificateRequest } from "./orval/model/vpnServerCertsRequestsBuildCertificateRequest";
export type { VpnServerClientsResponsesConnectedClientsResponse as ConnectedClientsResponse } from "./orval/model/vpnServerClientsResponsesConnectedClientsResponse";
export type { QuotaPlansRequestsCreateOrUpdateQuotaPlanRequest as CreateOrUpdateQuotaPlanRequest } from "./orval/model/quotaPlansRequestsCreateOrUpdateQuotaPlanRequest";
export type { UserQuotaPlansRequestsCreateOrUpdateUserQuotaPlanRequest as CreateOrUpdateUserQuotaPlanRequest } from "./orval/model/userQuotaPlansRequestsCreateOrUpdateUserQuotaPlanRequest";
export type { OpenVpnFilesRequestsDownloadFileRequest as DownloadFileRequest } from "./orval/model/openVpnFilesRequestsDownloadFileRequest";
export type { OpenVpnFilesResponsesDownloadFileResponse as DownloadFileResponse } from "./orval/model/openVpnFilesResponsesDownloadFileResponse";
export type { ApiOpenVpnFilesResponsesDownloadFileResponse as DownloadFileResponseApiResponse } from "./orval/model/apiOpenVpnFilesResponsesDownloadFileResponse";
export type { VpnServerClientsDtoGeoPointAggDto as GeoPointAggDto } from "./orval/model/vpnServerClientsDtoGeoPointAggDto";
export type { VpnServerCertsResponsesGetAllCertificatesResponse as GetAllCertificatesResponse } from "./orval/model/vpnServerCertsResponsesGetAllCertificatesResponse";
export type { TelegramBotIncomingMessageLogResponsesGetAllMessagesResponse as GetAllMessagesResponse } from "./orval/model/telegramBotIncomingMessageLogResponsesGetAllMessagesResponse";
export type { TelegramBotUserResponsesGetAllTelegramUsersResponse as GetAllTelegramUsersResponse } from "./orval/model/telegramBotUserResponsesGetAllTelegramUsersResponse";
export type { UserResponsesGetAllUsersResponse as GetAllUsersResponse } from "./orval/model/userResponsesGetAllUsersResponse";
export type { ApiTelegramBotIncomingMessageLogResponsesGetByTelegramIdMessagesResponse as GetByTelegramIdMessagesResponseApiResponse } from "./orval/model/apiTelegramBotIncomingMessageLogResponsesGetByTelegramIdMessagesResponse";
export type { NotificationsResponsesGetNotificationsResponse as GetNotificationsResponse } from "./orval/model/notificationsResponsesGetNotificationsResponse";
export type { QuotaPlanAllowedServersResponsesGetQuotaPlanAllowedServersByQuotaPlanIdResponse as GetQuotaPlanAllowedServersByQuotaPlanIdResponse } from "./orval/model/quotaPlanAllowedServersResponsesGetQuotaPlanAllowedServersByQuotaPlanIdResponse";
export type { UserQuotaPlansResponsesGetUserQuotaPlansByUserIdResponse as GetUserQuotaPlansByUserIdResponse } from "./orval/model/userQuotaPlansResponsesGetUserQuotaPlansByUserIdResponse";
export type { GeoLiteResponsesGetVersionDatabaseResponse as GetVersionDatabaseResponse } from "./orval/model/geoLiteResponsesGetVersionDatabaseResponse";
export type { VpnProfileNotificationPreferencesGetVpnProfileNotificationPreferencesResponse as GetVpnProfileNotificationPreferencesResponse } from "./orval/model/vpnProfileNotificationPreferencesGetVpnProfileNotificationPreferencesResponse";
export type { AuthRequestsGoogleLoginRequest as GoogleLoginRequest } from "./orval/model/authRequestsGoogleLoginRequest";
export type { AuthResponsesGoogleLoginResponse as GoogleLoginResponse } from "./orval/model/authResponsesGoogleLoginResponse";
export type { OpenVpnFilesResponsesDtoIssuedOvpnFileDto as IssuedOvpnFileDto } from "./orval/model/openVpnFilesResponsesDtoIssuedOvpnFileDto";
export type { AuthRequestsLoginRequest as LoginRequest } from "./orval/model/authRequestsLoginRequest";
export type { AuthResponsesLoginResponse as LoginResponse } from "./orval/model/authResponsesLoginResponse";
export type { AuthResponsesTotpStatusResponse as TotpStatusResponse } from "./orval/model/authResponsesTotpStatusResponse";
export type { AuthResponsesTotpSetupResponse as TotpSetupResponse } from "./orval/model/authResponsesTotpSetupResponse";
export type { AuthResponsesAuthSessionPolicyResponse as AuthSessionPolicyResponse } from "./orval/model/authResponsesAuthSessionPolicyResponse";
export type { AuthResponsesGetUserSessionsResponse as GetUserSessionsResponse } from "./orval/model/authResponsesGetUserSessionsResponse";
export type { AuthResponsesUserSessionDto as UserSessionDto } from "./orval/model/authResponsesUserSessionDto";
export type { AuthRequestsRevokeUserSessionsRequest as RevokeUserSessionsRequest } from "./orval/model/authRequestsRevokeUserSessionsRequest";
export type { AuthRequestsTotpVerifyLoginRequest as TotpVerifyLoginRequest } from "./orval/model/authRequestsTotpVerifyLoginRequest";
export type { AuthRequestsTotpConfirmRequest as TotpConfirmRequest } from "./orval/model/authRequestsTotpConfirmRequest";
export type { AuthRequestsTotpDisableRequest as TotpDisableRequest } from "./orval/model/authRequestsTotpDisableRequest";
export type { TelegramBotIncomingMessageLogDtoMessageDto as MessageDto } from "./orval/model/telegramBotIncomingMessageLogDtoMessageDto";
export type { VpnServerCertsResponsesDtoMonitorServerCertificate as MonitorServerCertificate } from "./orval/model/vpnServerCertsResponsesDtoMonitorServerCertificate";
export type { NotificationsResponsesNotificationItemDto as NotificationItemDto } from "./orval/model/notificationsResponsesNotificationItemDto";
export type { ServicesOthersModelsNotificationRequest as NotificationRequest } from "./orval/model/servicesOthersModelsNotificationRequest";
export type { VpnServerClientsResponsesOverviewSeriesResponse as OverviewSeriesResponse } from "./orval/model/vpnServerClientsResponsesOverviewSeriesResponse";
export type { VpnServerClientsDtoOverviewSeriesRowDto as OverviewSeriesRowDto } from "./orval/model/vpnServerClientsDtoOverviewSeriesRowDto";
export type { VpnServerClientsResponsesOverviewTotalsResponse as OverviewTotalsResponse } from "./orval/model/vpnServerClientsResponsesOverviewTotalsResponse";
export type { VpnServerClientsDtoOverviewUserDto as OverviewUserDto } from "./orval/model/vpnServerClientsDtoOverviewUserDto";
export type { DataBaseServicesQueryVpnServerClientTableOverviewUsersResponse as OverviewUsersResponse } from "./orval/model/dataBaseServicesQueryVpnServerClientTableOverviewUsersResponse";
export type { VpnServerClientsResponsesOverviewUsersSeriesResponse as OverviewUsersSeriesResponse } from "./orval/model/vpnServerClientsResponsesOverviewUsersSeriesResponse";
export type { ApiVpnServerClientsResponsesOverviewUsersSeriesResponse as OverviewUsersSeriesResponseApiResponse } from "./orval/model/apiVpnServerClientsResponsesOverviewUsersSeriesResponse";
export type { VpnServerClientsDtoOverviewUsersSeriesRowDto as OverviewUsersSeriesRowDto } from "./orval/model/vpnServerClientsDtoOverviewUsersSeriesRowDto";
export type { VpnServerOvpnFileConfigResponsesOvpnFileConfigResponse as OvpnFileConfigResponse } from "./orval/model/vpnServerOvpnFileConfigResponsesOvpnFileConfigResponse";
export type { ApiOpenVpnFilesResponsesOvpnFileResponse as OvpnFileResponseApiResponse } from "./orval/model/apiOpenVpnFilesResponsesOvpnFileResponse";
export type { OpenVpnFilesResponsesOvpnFilesResponse as OvpnFilesResponse } from "./orval/model/openVpnFilesResponsesOvpnFilesResponse";
export type { ApiOpenVpnFilesResponsesOvpnFilesResponse as OvpnFilesResponseApiResponse } from "./orval/model/apiOpenVpnFilesResponsesOvpnFilesResponse";
export type { QuotaPlanAllowedServersDtoQuotaPlanAllowedServerDto as QuotaPlanAllowedServerDto } from "./orval/model/quotaPlanAllowedServersDtoQuotaPlanAllowedServerDto";
export type { QuotaPlansDtoQuotaPlanDto as QuotaPlanDto } from "./orval/model/quotaPlansDtoQuotaPlanDto";
export type { QuotaPlansResponsesQuotaPlansResponse as QuotaPlansResponse } from "./orval/model/quotaPlansResponsesQuotaPlansResponse";
export type { AuthRequestsRefreshRequest as RefreshRequest } from "./orval/model/authRequestsRefreshRequest";
export type { AuthResponsesRefreshResponse as RefreshResponse } from "./orval/model/authResponsesRefreshResponse";
export type { ApplicationsRequestsRegisterApplicationRequest as RegisterApplicationRequest } from "./orval/model/applicationsRequestsRegisterApplicationRequest";
export type { AuthRequestsRegisterUserRequest as RegisterUserRequest } from "./orval/model/authRequestsRegisterUserRequest";
export type { ApplicationsRequestsRevokeApplicationRequest as RevokeApplicationRequest } from "./orval/model/applicationsRequestsRevokeApplicationRequest";
export type { VpnServerCertsRequestsRevokeCertificateRequest as RevokeCertificateRequest } from "./orval/model/vpnServerCertsRequestsRevokeCertificateRequest";
export type { OpenVpnFilesRequestsRevokeFileRequest as RevokeFileRequest } from "./orval/model/openVpnFilesRequestsRevokeFileRequest";
export type { UserRolesDtoRoleDto as RoleDto } from "./orval/model/userRolesDtoRoleDto";
export type { UserRolesResponsesRolesResponse as RolesResponse } from "./orval/model/userRolesResponsesRolesResponse";
export type { VpnServersDtoServiceStatusDto as ServiceStatusDto } from "./orval/model/vpnServersDtoServiceStatusDto";
export type { SettingsResponsesSettingResponse as SettingResponse } from "./orval/model/settingsResponsesSettingResponse";
export type { TelegramBotUserResponsesDtoTelegramBotUserDto as TelegramBotUserDto } from "./orval/model/telegramBotUserResponsesDtoTelegramBotUserDto";
export type { TelegramBotUserRequestsTelegramUserActionRequest as TelegramUserActionRequest } from "./orval/model/telegramBotUserRequestsTelegramUserActionRequest";
export type { NotificationsResponsesUnreadCountResponse as UnreadCountResponse } from "./orval/model/notificationsResponsesUnreadCountResponse";
export type { UserResponsesDtoUserDto as UserDto } from "./orval/model/userResponsesDtoUserDto";
export type { UserQuotaPlansDtoUserQuotaPlanDto as UserQuotaPlanDto } from "./orval/model/userQuotaPlansDtoUserQuotaPlanDto";
export type { UserRolesResponsesUserRoleAssignmentResponse as UserRoleAssignmentResponse } from "./orval/model/userRolesResponsesUserRoleAssignmentResponse";
export type { UserResponsesUsersResponse as UsersResponse } from "./orval/model/userResponsesUsersResponse";
export type { VpnServersDtoVpnClientInfoDto as VpnClientInfoDto } from "./orval/model/vpnServersDtoVpnClientInfoDto";
export type { VpnServersDtoVpnServerDto as VpnServerDto } from "./orval/model/vpnServersDtoVpnServerDto";
export type { VpnServersRequestsAddServerRequest as AddServerRequest } from "./orval/model/vpnServersRequestsAddServerRequest";
export type { VpnServersRequestsUpdateServerRequest as UpdateServerRequest } from "./orval/model/vpnServersRequestsUpdateServerRequest";
export type { VpnServersDtoVpnServerV2Dto as VpnServerV2Dto } from "./orval/model/vpnServersDtoVpnServerV2Dto";
export type { VpnServersDtoVpnServerWithStatusDto as VpnServerWithStatusDto } from "./orval/model/vpnServersDtoVpnServerWithStatusDto";
export type { VpnServersDtoVpnServerWithStatusV2Dto as VpnServerWithStatusV2Dto } from "./orval/model/vpnServersDtoVpnServerWithStatusV2Dto";
export type { VpnServerEventDtoVpnServerEventLogDto as VpnServerEventLogDto } from "./orval/model/vpnServerEventDtoVpnServerEventLogDto";
export type { VpnServersResponsesVpnServerResponse as VpnServerResponse } from "./orval/model/vpnServersResponsesVpnServerResponse";
export type { VpnServersResponsesVpnServersV2Response as VpnServersV2Response } from "./orval/model/vpnServersResponsesVpnServersV2Response";
export type { VpnServersResponsesVpnServersV3Response as VpnServersV3Response } from "./orval/model/vpnServersResponsesVpnServersV3Response";
export type { VpnServersResponsesVpnServerWithStatusesV2Response as VpnServerWithStatusesV2Response } from "./orval/model/vpnServersResponsesVpnServerWithStatusesV2Response";
export type { VpnServersResponsesVpnServerWithStatusesV3Response as VpnServerWithStatusesV3Response } from "./orval/model/vpnServersResponsesVpnServerWithStatusesV3Response";
export type { VpnServersResponsesVpnServerWithStatusResponse as VpnServerWithStatusResponse } from "./orval/model/vpnServersResponsesVpnServerWithStatusResponse";
export type { VpnServerOvpnFileConfigRequestsAddOrUpdateOvpnFileConfigRequest as AddOrUpdateOvpnFileConfigRequest } from "./orval/model/vpnServerOvpnFileConfigRequestsAddOrUpdateOvpnFileConfigRequest";
export type { DataGateOpenVpnManagerInfoRootOpenVpnInfoResponse as RootOpenVpnInfoResponse } from "./orval/model/dataGateOpenVpnManagerInfoRootOpenVpnInfoResponse";

export type { EmailBroadcastResponsesDtoSentEmailLogDto as SentEmailLogDto } from "./orval/model/emailBroadcastResponsesDtoSentEmailLogDto";
export type { EmailBroadcastResponsesDtoEmailBroadcastTemplateSummaryDto as EmailBroadcastTemplateSummaryDto } from "./orval/model/emailBroadcastResponsesDtoEmailBroadcastTemplateSummaryDto";
export type { EmailBroadcastResponsesDtoEmailBroadcastTemplateDto as EmailBroadcastTemplateDto } from "./orval/model/emailBroadcastResponsesDtoEmailBroadcastTemplateDto";

export { EnumsServiceStatus as ServiceStatus } from "./orval/model/enumsServiceStatus";
export { EnumsOverviewGrouping as OverviewGrouping } from "./orval/model/enumsOverviewGrouping";
export { EnumsQuotaOverlimitAction as QuotaOverlimitAction } from "./orval/model/enumsQuotaOverlimitAction";
export { EnumsNotificationSeverity as NotificationSeverity } from "./orval/model/enumsNotificationSeverity";
export { EnumsVpnServerType as VpnServerType } from "./orval/model/enumsVpnServerType";
