/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiXrayClientLinksResponsesDownloadXrayClientLinkResponse,
  ApiXrayClientLinksResponsesXrayClientLinkResponse,
  ApiXrayClientLinksResponsesXrayClientLinkWithTokenResponse,
  ApiXrayClientLinksResponsesXrayClientLinksResponse,
  ApiXrayClientLinksResponsesXrayClientLinksWithTokensResponse,
  XrayClientLinksRequestsAddXrayClientLinkRequest,
  XrayClientLinksRequestsDownloadXrayClientLinkByCnRequest,
  XrayClientLinksRequestsDownloadXrayClientLinkRequest,
  XrayClientLinksRequestsRevokeXrayClientLinkRequest
} from '../model';

import { ogmMutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getApiV2XrayClientLinksByTokenToken = (
    token: string,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiXrayClientLinksResponsesXrayClientLinkResponse>(
      {url: `/api/v2/xray-client-links/by-token/${token}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV2XrayClientLinksByTokenTokenQueryKey = (token: string,) => {
    return [
    `/api/v2/xray-client-links/by-token/${token}`
    ] as const;
    }


export const getGetApiV2XrayClientLinksByTokenTokenQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>, TError = unknown>(token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2XrayClientLinksByTokenTokenQueryKey(token);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>> = ({ signal }) => getApiV2XrayClientLinksByTokenToken(token, requestOptions, signal);





   return  { queryKey, queryFn, enabled: token !== null && token !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2XrayClientLinksByTokenTokenQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>>
export type GetApiV2XrayClientLinksByTokenTokenQueryError = unknown


export function useGetApiV2XrayClientLinksByTokenToken<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>, TError = unknown>(
 token: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksByTokenToken<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>, TError = unknown>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksByTokenToken<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>, TError = unknown>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2XrayClientLinksByTokenToken<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>, TError = unknown>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2XrayClientLinksByTokenTokenQueryOptions(token,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiV2XrayClientLinksByServerVpnServerId = (
    vpnServerId: number,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiXrayClientLinksResponsesXrayClientLinksResponse>(
      {url: `/api/v2/xray-client-links/by-server/${vpnServerId}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV2XrayClientLinksByServerVpnServerIdQueryKey = (vpnServerId: number,) => {
    return [
    `/api/v2/xray-client-links/by-server/${vpnServerId}`
    ] as const;
    }


export const getGetApiV2XrayClientLinksByServerVpnServerIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>, TError = unknown>(vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2XrayClientLinksByServerVpnServerIdQueryKey(vpnServerId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>> = ({ signal }) => getApiV2XrayClientLinksByServerVpnServerId(vpnServerId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: vpnServerId !== null && vpnServerId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2XrayClientLinksByServerVpnServerIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>>
export type GetApiV2XrayClientLinksByServerVpnServerIdQueryError = unknown


export function useGetApiV2XrayClientLinksByServerVpnServerId<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>, TError = unknown>(
 vpnServerId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksByServerVpnServerId<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>, TError = unknown>(
 vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksByServerVpnServerId<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>, TError = unknown>(
 vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2XrayClientLinksByServerVpnServerId<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>, TError = unknown>(
 vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2XrayClientLinksByServerVpnServerIdQueryOptions(vpnServerId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId = (
    vpnServerId: number,
    externalId: string,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiXrayClientLinksResponsesXrayClientLinksResponse>(
      {url: `/api/v2/xray-client-links/by-server/${vpnServerId}/by-external-id/${externalId}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdQueryKey = (vpnServerId: number,
    externalId: string,) => {
    return [
    `/api/v2/xray-client-links/by-server/${vpnServerId}/by-external-id/${externalId}`
    ] as const;
    }


export const getGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>, TError = unknown>(vpnServerId: number,
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdQueryKey(vpnServerId,externalId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>> = ({ signal }) => getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId(vpnServerId,externalId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: vpnServerId !== null && vpnServerId !== undefined && externalId !== null && externalId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>>
export type GetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdQueryError = unknown


export function useGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>, TError = unknown>(
 vpnServerId: number,
    externalId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>, TError = unknown>(
 vpnServerId: number,
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>, TError = unknown>(
 vpnServerId: number,
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>, TError = unknown>(
 vpnServerId: number,
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdQueryOptions(vpnServerId,externalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiV2XrayClientLinksByServerVpnServerIdWithTokens = (
    vpnServerId: number,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiXrayClientLinksResponsesXrayClientLinksWithTokensResponse>(
      {url: `/api/v2/xray-client-links/by-server/${vpnServerId}/with-tokens`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV2XrayClientLinksByServerVpnServerIdWithTokensQueryKey = (vpnServerId: number,) => {
    return [
    `/api/v2/xray-client-links/by-server/${vpnServerId}/with-tokens`
    ] as const;
    }


export const getGetApiV2XrayClientLinksByServerVpnServerIdWithTokensQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>, TError = unknown>(vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2XrayClientLinksByServerVpnServerIdWithTokensQueryKey(vpnServerId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>> = ({ signal }) => getApiV2XrayClientLinksByServerVpnServerIdWithTokens(vpnServerId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: vpnServerId !== null && vpnServerId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2XrayClientLinksByServerVpnServerIdWithTokensQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>>
export type GetApiV2XrayClientLinksByServerVpnServerIdWithTokensQueryError = unknown


export function useGetApiV2XrayClientLinksByServerVpnServerIdWithTokens<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>, TError = unknown>(
 vpnServerId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksByServerVpnServerIdWithTokens<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>, TError = unknown>(
 vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksByServerVpnServerIdWithTokens<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>, TError = unknown>(
 vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2XrayClientLinksByServerVpnServerIdWithTokens<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>, TError = unknown>(
 vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2XrayClientLinksByServerVpnServerIdWithTokensQueryOptions(vpnServerId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens = (
    vpnServerId: number,
    externalId: string,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiXrayClientLinksResponsesXrayClientLinksWithTokensResponse>(
      {url: `/api/v2/xray-client-links/by-server/${vpnServerId}/by-external-id/${externalId}/with-tokens`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokensQueryKey = (vpnServerId: number,
    externalId: string,) => {
    return [
    `/api/v2/xray-client-links/by-server/${vpnServerId}/by-external-id/${externalId}/with-tokens`
    ] as const;
    }


export const getGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokensQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>, TError = unknown>(vpnServerId: number,
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokensQueryKey(vpnServerId,externalId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>> = ({ signal }) => getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens(vpnServerId,externalId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: vpnServerId !== null && vpnServerId !== undefined && externalId !== null && externalId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokensQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>>
export type GetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokensQueryError = unknown


export function useGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>, TError = unknown>(
 vpnServerId: number,
    externalId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>, TError = unknown>(
 vpnServerId: number,
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>, TError = unknown>(
 vpnServerId: number,
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>, TError = unknown>(
 vpnServerId: number,
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokensQueryOptions(vpnServerId,externalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiV2XrayClientLinksByExternalIdExternalId = (
    externalId: string,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiXrayClientLinksResponsesXrayClientLinksResponse>(
      {url: `/api/v2/xray-client-links/by-external-id/${externalId}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV2XrayClientLinksByExternalIdExternalIdQueryKey = (externalId: string,) => {
    return [
    `/api/v2/xray-client-links/by-external-id/${externalId}`
    ] as const;
    }


export const getGetApiV2XrayClientLinksByExternalIdExternalIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>, TError = unknown>(externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2XrayClientLinksByExternalIdExternalIdQueryKey(externalId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>> = ({ signal }) => getApiV2XrayClientLinksByExternalIdExternalId(externalId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: externalId !== null && externalId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2XrayClientLinksByExternalIdExternalIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>>
export type GetApiV2XrayClientLinksByExternalIdExternalIdQueryError = unknown


export function useGetApiV2XrayClientLinksByExternalIdExternalId<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>, TError = unknown>(
 externalId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksByExternalIdExternalId<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>, TError = unknown>(
 externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksByExternalIdExternalId<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>, TError = unknown>(
 externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2XrayClientLinksByExternalIdExternalId<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>, TError = unknown>(
 externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2XrayClientLinksByExternalIdExternalIdQueryOptions(externalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiV2XrayClientLinks = (
    xrayClientLinksRequestsAddXrayClientLinkRequest?: XrayClientLinksRequestsAddXrayClientLinkRequest,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiXrayClientLinksResponsesXrayClientLinkResponse>(
      {url: `/api/v2/xray-client-links`, method: 'POST',
      headers: {'Content-Type': 'application/json-patch+json', },
      data: xrayClientLinksRequestsAddXrayClientLinkRequest, signal
    },
      options);
    }



export const getPostApiV2XrayClientLinksMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinks>>, TError,{data?: XrayClientLinksRequestsAddXrayClientLinkRequest}, TContext>, request?: SecondParameter<typeof ogmMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinks>>, TError,{data?: XrayClientLinksRequestsAddXrayClientLinkRequest}, TContext> => {

const mutationKey = ['postApiV2XrayClientLinks'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV2XrayClientLinks>>, {data?: XrayClientLinksRequestsAddXrayClientLinkRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV2XrayClientLinks(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV2XrayClientLinksMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV2XrayClientLinks>>>
    export type PostApiV2XrayClientLinksMutationBody = XrayClientLinksRequestsAddXrayClientLinkRequest | undefined
    export type PostApiV2XrayClientLinksMutationError = unknown

    export const usePostApiV2XrayClientLinks = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinks>>, TError,{data?: XrayClientLinksRequestsAddXrayClientLinkRequest}, TContext>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV2XrayClientLinks>>,
        TError,
        {data?: XrayClientLinksRequestsAddXrayClientLinkRequest},
        TContext
      > => {
      return useMutation(getPostApiV2XrayClientLinksMutationOptions(options), queryClient);
    }
    export const postApiV2XrayClientLinksWithToken = (
    xrayClientLinksRequestsAddXrayClientLinkRequest?: XrayClientLinksRequestsAddXrayClientLinkRequest,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiXrayClientLinksResponsesXrayClientLinkWithTokenResponse>(
      {url: `/api/v2/xray-client-links/with-token`, method: 'POST',
      headers: {'Content-Type': 'application/json-patch+json', },
      data: xrayClientLinksRequestsAddXrayClientLinkRequest, signal
    },
      options);
    }



export const getPostApiV2XrayClientLinksWithTokenMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinksWithToken>>, TError,{data?: XrayClientLinksRequestsAddXrayClientLinkRequest}, TContext>, request?: SecondParameter<typeof ogmMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinksWithToken>>, TError,{data?: XrayClientLinksRequestsAddXrayClientLinkRequest}, TContext> => {

const mutationKey = ['postApiV2XrayClientLinksWithToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV2XrayClientLinksWithToken>>, {data?: XrayClientLinksRequestsAddXrayClientLinkRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV2XrayClientLinksWithToken(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV2XrayClientLinksWithTokenMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV2XrayClientLinksWithToken>>>
    export type PostApiV2XrayClientLinksWithTokenMutationBody = XrayClientLinksRequestsAddXrayClientLinkRequest | undefined
    export type PostApiV2XrayClientLinksWithTokenMutationError = unknown

    export const usePostApiV2XrayClientLinksWithToken = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinksWithToken>>, TError,{data?: XrayClientLinksRequestsAddXrayClientLinkRequest}, TContext>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV2XrayClientLinksWithToken>>,
        TError,
        {data?: XrayClientLinksRequestsAddXrayClientLinkRequest},
        TContext
      > => {
      return useMutation(getPostApiV2XrayClientLinksWithTokenMutationOptions(options), queryClient);
    }
    export const postApiV2XrayClientLinksRevoke = (
    xrayClientLinksRequestsRevokeXrayClientLinkRequest?: XrayClientLinksRequestsRevokeXrayClientLinkRequest,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiXrayClientLinksResponsesXrayClientLinkResponse>(
      {url: `/api/v2/xray-client-links/revoke`, method: 'POST',
      headers: {'Content-Type': 'application/json-patch+json', },
      data: xrayClientLinksRequestsRevokeXrayClientLinkRequest, signal
    },
      options);
    }



export const getPostApiV2XrayClientLinksRevokeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinksRevoke>>, TError,{data?: XrayClientLinksRequestsRevokeXrayClientLinkRequest}, TContext>, request?: SecondParameter<typeof ogmMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinksRevoke>>, TError,{data?: XrayClientLinksRequestsRevokeXrayClientLinkRequest}, TContext> => {

const mutationKey = ['postApiV2XrayClientLinksRevoke'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV2XrayClientLinksRevoke>>, {data?: XrayClientLinksRequestsRevokeXrayClientLinkRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV2XrayClientLinksRevoke(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV2XrayClientLinksRevokeMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV2XrayClientLinksRevoke>>>
    export type PostApiV2XrayClientLinksRevokeMutationBody = XrayClientLinksRequestsRevokeXrayClientLinkRequest | undefined
    export type PostApiV2XrayClientLinksRevokeMutationError = unknown

    export const usePostApiV2XrayClientLinksRevoke = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinksRevoke>>, TError,{data?: XrayClientLinksRequestsRevokeXrayClientLinkRequest}, TContext>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV2XrayClientLinksRevoke>>,
        TError,
        {data?: XrayClientLinksRequestsRevokeXrayClientLinkRequest},
        TContext
      > => {
      return useMutation(getPostApiV2XrayClientLinksRevokeMutationOptions(options), queryClient);
    }
    export const postApiV2XrayClientLinksDownload = (
    xrayClientLinksRequestsDownloadXrayClientLinkRequest?: XrayClientLinksRequestsDownloadXrayClientLinkRequest,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiXrayClientLinksResponsesDownloadXrayClientLinkResponse>(
      {url: `/api/v2/xray-client-links/download`, method: 'POST',
      headers: {'Content-Type': 'application/json-patch+json', },
      data: xrayClientLinksRequestsDownloadXrayClientLinkRequest, signal
    },
      options);
    }



export const getPostApiV2XrayClientLinksDownloadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinksDownload>>, TError,{data?: XrayClientLinksRequestsDownloadXrayClientLinkRequest}, TContext>, request?: SecondParameter<typeof ogmMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinksDownload>>, TError,{data?: XrayClientLinksRequestsDownloadXrayClientLinkRequest}, TContext> => {

const mutationKey = ['postApiV2XrayClientLinksDownload'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV2XrayClientLinksDownload>>, {data?: XrayClientLinksRequestsDownloadXrayClientLinkRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV2XrayClientLinksDownload(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV2XrayClientLinksDownloadMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV2XrayClientLinksDownload>>>
    export type PostApiV2XrayClientLinksDownloadMutationBody = XrayClientLinksRequestsDownloadXrayClientLinkRequest | undefined
    export type PostApiV2XrayClientLinksDownloadMutationError = unknown

    export const usePostApiV2XrayClientLinksDownload = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinksDownload>>, TError,{data?: XrayClientLinksRequestsDownloadXrayClientLinkRequest}, TContext>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV2XrayClientLinksDownload>>,
        TError,
        {data?: XrayClientLinksRequestsDownloadXrayClientLinkRequest},
        TContext
      > => {
      return useMutation(getPostApiV2XrayClientLinksDownloadMutationOptions(options), queryClient);
    }
    export const postApiV2XrayClientLinksDownloadByCn = (
    xrayClientLinksRequestsDownloadXrayClientLinkByCnRequest?: XrayClientLinksRequestsDownloadXrayClientLinkByCnRequest,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiXrayClientLinksResponsesDownloadXrayClientLinkResponse>(
      {url: `/api/v2/xray-client-links/download-by-cn`, method: 'POST',
      headers: {'Content-Type': 'application/json-patch+json', },
      data: xrayClientLinksRequestsDownloadXrayClientLinkByCnRequest, signal
    },
      options);
    }



export const getPostApiV2XrayClientLinksDownloadByCnMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinksDownloadByCn>>, TError,{data?: XrayClientLinksRequestsDownloadXrayClientLinkByCnRequest}, TContext>, request?: SecondParameter<typeof ogmMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinksDownloadByCn>>, TError,{data?: XrayClientLinksRequestsDownloadXrayClientLinkByCnRequest}, TContext> => {

const mutationKey = ['postApiV2XrayClientLinksDownloadByCn'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV2XrayClientLinksDownloadByCn>>, {data?: XrayClientLinksRequestsDownloadXrayClientLinkByCnRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV2XrayClientLinksDownloadByCn(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV2XrayClientLinksDownloadByCnMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV2XrayClientLinksDownloadByCn>>>
    export type PostApiV2XrayClientLinksDownloadByCnMutationBody = XrayClientLinksRequestsDownloadXrayClientLinkByCnRequest | undefined
    export type PostApiV2XrayClientLinksDownloadByCnMutationError = unknown

    export const usePostApiV2XrayClientLinksDownloadByCn = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinksDownloadByCn>>, TError,{data?: XrayClientLinksRequestsDownloadXrayClientLinkByCnRequest}, TContext>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV2XrayClientLinksDownloadByCn>>,
        TError,
        {data?: XrayClientLinksRequestsDownloadXrayClientLinkByCnRequest},
        TContext
      > => {
      return useMutation(getPostApiV2XrayClientLinksDownloadByCnMutationOptions(options), queryClient);
    }
