/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiOpenVpnFilesResponsesOvpnFilesV2Response,
  ApiSystemString,
  ApiXrayClientLinksResponsesDownloadXrayClientLinkResponse,
  ApiXrayClientLinksResponsesXrayClientLinkResponse,
  ApiXrayClientLinksResponsesXrayClientLinkWithTokenResponse,
  ApiXrayClientLinksResponsesXrayClientLinksResponse,
  ApiXrayClientLinksResponsesXrayClientLinksWithTokensResponse,
  GetApiV2XrayClientLinksParams,
  XrayClientLinksRequestsAddXrayClientLinkRequest,
  XrayClientLinksRequestsDownloadXrayClientLinkByCnRequest,
  XrayClientLinksRequestsDownloadXrayClientLinkRequest,
  XrayClientLinksRequestsRevokeXrayClientLinkRequest
} from '../model';

import { ogmMutator } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const postApiV2XrayClientLinks = (
    xrayClientLinksRequestsAddXrayClientLinkRequest?: XrayClientLinksRequestsAddXrayClientLinkRequest,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiXrayClientLinksResponsesXrayClientLinkResponse>(
      {url: `/api/v2/xray-client-links`, method: 'POST',
      headers: {'Content-Type': 'application/json-patch+json', },
      data: xrayClientLinksRequestsAddXrayClientLinkRequest, signal
    },
      options);
    }




export const getPostApiV2XrayClientLinksMutationKey = () => ['postApiV2XrayClientLinks'] as const;

export const getPostApiV2XrayClientLinksMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinks>>, TError,PostApiV2XrayClientLinksMutationVariables, TContext>, request?: SecondParameter<typeof ogmMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinks>>, TError,PostApiV2XrayClientLinksMutationVariables, TContext> => {

const mutationKey = getPostApiV2XrayClientLinksMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV2XrayClientLinks>>, PostApiV2XrayClientLinksMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiV2XrayClientLinks(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV2XrayClientLinksMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV2XrayClientLinks>>>
    export type PostApiV2XrayClientLinksMutationBody = XrayClientLinksRequestsAddXrayClientLinkRequest | undefined
    export type PostApiV2XrayClientLinksMutationError = unknown
    export type PostApiV2XrayClientLinksMutationVariables = {data?: XrayClientLinksRequestsAddXrayClientLinkRequest}

    export const usePostApiV2XrayClientLinks = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinks>>, TError,PostApiV2XrayClientLinksMutationVariables, TContext>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV2XrayClientLinks>>,
        TError,
        PostApiV2XrayClientLinksMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV2XrayClientLinksMutationOptions(options), queryClient);
    }
    export const getApiV2XrayClientLinks = (
    params: GetApiV2XrayClientLinksParams,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiOpenVpnFilesResponsesOvpnFilesV2Response>(
      {url: `/api/v2/xray-client-links`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetApiV2XrayClientLinksQueryKey = (params?: GetApiV2XrayClientLinksParams,) => {
    return [
    `/api/v2/xray-client-links`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiV2XrayClientLinksQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2XrayClientLinks>>, TError = unknown>(params: GetApiV2XrayClientLinksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinks>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2XrayClientLinksQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2XrayClientLinks>>> = ({ signal }) => getApiV2XrayClientLinks(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2XrayClientLinksQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2XrayClientLinks>>>
export type GetApiV2XrayClientLinksQueryError = unknown


export function useGetApiV2XrayClientLinks<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinks>>, TError = unknown>(
 params: GetApiV2XrayClientLinksParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinks>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinks<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinks>>, TError = unknown>(
 params: GetApiV2XrayClientLinksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinks>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinks<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinks>>, TError = unknown>(
 params: GetApiV2XrayClientLinksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinks>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2XrayClientLinks<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinks>>, TError = unknown>(
 params: GetApiV2XrayClientLinksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinks>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2XrayClientLinksQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiV2XrayClientLinksByExternalIdExternalId = (
    externalId: string,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiXrayClientLinksResponsesXrayClientLinksResponse>(
      {url: `/api/v2/xray-client-links/by-external-id/${externalId}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV2XrayClientLinksByExternalIdExternalIdQueryKey = (externalId: string,) => {
    return [
    `/api/v2/xray-client-links/by-external-id/${externalId}`
    ] as const;
    }


export const getGetApiV2XrayClientLinksByExternalIdExternalIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>, TError = unknown>(externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2XrayClientLinksByExternalIdExternalIdQueryKey(externalId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>> = ({ signal }) => getApiV2XrayClientLinksByExternalIdExternalId(externalId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: externalId !== null && externalId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2XrayClientLinksByExternalIdExternalIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>>
export type GetApiV2XrayClientLinksByExternalIdExternalIdQueryError = unknown


export function useGetApiV2XrayClientLinksByExternalIdExternalId<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>, TError = unknown>(
 externalId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksByExternalIdExternalId<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>, TError = unknown>(
 externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksByExternalIdExternalId<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>, TError = unknown>(
 externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2XrayClientLinksByExternalIdExternalId<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>, TError = unknown>(
 externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByExternalIdExternalId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2XrayClientLinksByExternalIdExternalIdQueryOptions(externalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiV2XrayClientLinksByServerVpnServerId = (
    vpnServerId: number,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiXrayClientLinksResponsesXrayClientLinksResponse>(
      {url: `/api/v2/xray-client-links/by-server/${vpnServerId}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV2XrayClientLinksByServerVpnServerIdQueryKey = (vpnServerId: number,) => {
    return [
    `/api/v2/xray-client-links/by-server/${vpnServerId}`
    ] as const;
    }


export const getGetApiV2XrayClientLinksByServerVpnServerIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>, TError = unknown>(vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2XrayClientLinksByServerVpnServerIdQueryKey(vpnServerId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>> = ({ signal }) => getApiV2XrayClientLinksByServerVpnServerId(vpnServerId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: vpnServerId !== null && vpnServerId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2XrayClientLinksByServerVpnServerIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>>
export type GetApiV2XrayClientLinksByServerVpnServerIdQueryError = unknown


export function useGetApiV2XrayClientLinksByServerVpnServerId<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>, TError = unknown>(
 vpnServerId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksByServerVpnServerId<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>, TError = unknown>(
 vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksByServerVpnServerId<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>, TError = unknown>(
 vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2XrayClientLinksByServerVpnServerId<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>, TError = unknown>(
 vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2XrayClientLinksByServerVpnServerIdQueryOptions(vpnServerId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId = (
    vpnServerId: number,
    externalId: string,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiXrayClientLinksResponsesXrayClientLinksResponse>(
      {url: `/api/v2/xray-client-links/by-server/${vpnServerId}/by-external-id/${externalId}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdQueryKey = (vpnServerId: number,
    externalId: string,) => {
    return [
    `/api/v2/xray-client-links/by-server/${vpnServerId}/by-external-id/${externalId}`
    ] as const;
    }


export const getGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>, TError = unknown>(vpnServerId: number,
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdQueryKey(vpnServerId,externalId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>> = ({ signal }) => getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId(vpnServerId,externalId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: vpnServerId !== null && vpnServerId !== undefined && externalId !== null && externalId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>>
export type GetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdQueryError = unknown


export function useGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>, TError = unknown>(
 vpnServerId: number,
    externalId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>, TError = unknown>(
 vpnServerId: number,
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>, TError = unknown>(
 vpnServerId: number,
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>, TError = unknown>(
 vpnServerId: number,
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalId>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdQueryOptions(vpnServerId,externalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens = (
    vpnServerId: number,
    externalId: string,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiXrayClientLinksResponsesXrayClientLinksWithTokensResponse>(
      {url: `/api/v2/xray-client-links/by-server/${vpnServerId}/by-external-id/${externalId}/with-tokens`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokensQueryKey = (vpnServerId: number,
    externalId: string,) => {
    return [
    `/api/v2/xray-client-links/by-server/${vpnServerId}/by-external-id/${externalId}/with-tokens`
    ] as const;
    }


export const getGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokensQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>, TError = unknown>(vpnServerId: number,
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokensQueryKey(vpnServerId,externalId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>> = ({ signal }) => getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens(vpnServerId,externalId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: vpnServerId !== null && vpnServerId !== undefined && externalId !== null && externalId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokensQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>>
export type GetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokensQueryError = unknown


export function useGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>, TError = unknown>(
 vpnServerId: number,
    externalId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>, TError = unknown>(
 vpnServerId: number,
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>, TError = unknown>(
 vpnServerId: number,
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>, TError = unknown>(
 vpnServerId: number,
    externalId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokens>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2XrayClientLinksByServerVpnServerIdByExternalIdExternalIdWithTokensQueryOptions(vpnServerId,externalId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiV2XrayClientLinksByServerVpnServerIdWithTokens = (
    vpnServerId: number,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiXrayClientLinksResponsesXrayClientLinksWithTokensResponse>(
      {url: `/api/v2/xray-client-links/by-server/${vpnServerId}/with-tokens`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV2XrayClientLinksByServerVpnServerIdWithTokensQueryKey = (vpnServerId: number,) => {
    return [
    `/api/v2/xray-client-links/by-server/${vpnServerId}/with-tokens`
    ] as const;
    }


export const getGetApiV2XrayClientLinksByServerVpnServerIdWithTokensQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>, TError = unknown>(vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2XrayClientLinksByServerVpnServerIdWithTokensQueryKey(vpnServerId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>> = ({ signal }) => getApiV2XrayClientLinksByServerVpnServerIdWithTokens(vpnServerId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: vpnServerId !== null && vpnServerId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2XrayClientLinksByServerVpnServerIdWithTokensQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>>
export type GetApiV2XrayClientLinksByServerVpnServerIdWithTokensQueryError = unknown


export function useGetApiV2XrayClientLinksByServerVpnServerIdWithTokens<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>, TError = unknown>(
 vpnServerId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksByServerVpnServerIdWithTokens<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>, TError = unknown>(
 vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksByServerVpnServerIdWithTokens<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>, TError = unknown>(
 vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2XrayClientLinksByServerVpnServerIdWithTokens<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>, TError = unknown>(
 vpnServerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByServerVpnServerIdWithTokens>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2XrayClientLinksByServerVpnServerIdWithTokensQueryOptions(vpnServerId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiV2XrayClientLinksByTokenToken = (
    token: string,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiXrayClientLinksResponsesXrayClientLinkResponse>(
      {url: `/api/v2/xray-client-links/by-token/${token}`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV2XrayClientLinksByTokenTokenQueryKey = (token: string,) => {
    return [
    `/api/v2/xray-client-links/by-token/${token}`
    ] as const;
    }


export const getGetApiV2XrayClientLinksByTokenTokenQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>, TError = unknown>(token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2XrayClientLinksByTokenTokenQueryKey(token);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>> = ({ signal }) => getApiV2XrayClientLinksByTokenToken(token, requestOptions, signal);





   return  { queryKey, queryFn, enabled: token !== null && token !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2XrayClientLinksByTokenTokenQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>>
export type GetApiV2XrayClientLinksByTokenTokenQueryError = unknown


export function useGetApiV2XrayClientLinksByTokenToken<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>, TError = unknown>(
 token: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksByTokenToken<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>, TError = unknown>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksByTokenToken<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>, TError = unknown>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2XrayClientLinksByTokenToken<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>, TError = unknown>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksByTokenToken>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2XrayClientLinksByTokenTokenQueryOptions(token,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiV2XrayClientLinksDownload = (
    xrayClientLinksRequestsDownloadXrayClientLinkRequest?: XrayClientLinksRequestsDownloadXrayClientLinkRequest,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiXrayClientLinksResponsesDownloadXrayClientLinkResponse>(
      {url: `/api/v2/xray-client-links/download`, method: 'POST',
      headers: {'Content-Type': 'application/json-patch+json', },
      data: xrayClientLinksRequestsDownloadXrayClientLinkRequest, signal
    },
      options);
    }




export const getPostApiV2XrayClientLinksDownloadMutationKey = () => ['postApiV2XrayClientLinksDownload'] as const;

export const getPostApiV2XrayClientLinksDownloadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinksDownload>>, TError,PostApiV2XrayClientLinksDownloadMutationVariables, TContext>, request?: SecondParameter<typeof ogmMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinksDownload>>, TError,PostApiV2XrayClientLinksDownloadMutationVariables, TContext> => {

const mutationKey = getPostApiV2XrayClientLinksDownloadMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV2XrayClientLinksDownload>>, PostApiV2XrayClientLinksDownloadMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiV2XrayClientLinksDownload(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV2XrayClientLinksDownloadMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV2XrayClientLinksDownload>>>
    export type PostApiV2XrayClientLinksDownloadMutationBody = XrayClientLinksRequestsDownloadXrayClientLinkRequest | undefined
    export type PostApiV2XrayClientLinksDownloadMutationError = unknown
    export type PostApiV2XrayClientLinksDownloadMutationVariables = {data?: XrayClientLinksRequestsDownloadXrayClientLinkRequest}

    export const usePostApiV2XrayClientLinksDownload = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinksDownload>>, TError,PostApiV2XrayClientLinksDownloadMutationVariables, TContext>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV2XrayClientLinksDownload>>,
        TError,
        PostApiV2XrayClientLinksDownloadMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV2XrayClientLinksDownloadMutationOptions(options), queryClient);
    }
    export const postApiV2XrayClientLinksDownloadByCn = (
    xrayClientLinksRequestsDownloadXrayClientLinkByCnRequest?: XrayClientLinksRequestsDownloadXrayClientLinkByCnRequest,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiXrayClientLinksResponsesDownloadXrayClientLinkResponse>(
      {url: `/api/v2/xray-client-links/download-by-cn`, method: 'POST',
      headers: {'Content-Type': 'application/json-patch+json', },
      data: xrayClientLinksRequestsDownloadXrayClientLinkByCnRequest, signal
    },
      options);
    }




export const getPostApiV2XrayClientLinksDownloadByCnMutationKey = () => ['postApiV2XrayClientLinksDownloadByCn'] as const;

export const getPostApiV2XrayClientLinksDownloadByCnMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinksDownloadByCn>>, TError,PostApiV2XrayClientLinksDownloadByCnMutationVariables, TContext>, request?: SecondParameter<typeof ogmMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinksDownloadByCn>>, TError,PostApiV2XrayClientLinksDownloadByCnMutationVariables, TContext> => {

const mutationKey = getPostApiV2XrayClientLinksDownloadByCnMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV2XrayClientLinksDownloadByCn>>, PostApiV2XrayClientLinksDownloadByCnMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiV2XrayClientLinksDownloadByCn(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV2XrayClientLinksDownloadByCnMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV2XrayClientLinksDownloadByCn>>>
    export type PostApiV2XrayClientLinksDownloadByCnMutationBody = XrayClientLinksRequestsDownloadXrayClientLinkByCnRequest | undefined
    export type PostApiV2XrayClientLinksDownloadByCnMutationError = unknown
    export type PostApiV2XrayClientLinksDownloadByCnMutationVariables = {data?: XrayClientLinksRequestsDownloadXrayClientLinkByCnRequest}

    export const usePostApiV2XrayClientLinksDownloadByCn = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinksDownloadByCn>>, TError,PostApiV2XrayClientLinksDownloadByCnMutationVariables, TContext>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV2XrayClientLinksDownloadByCn>>,
        TError,
        PostApiV2XrayClientLinksDownloadByCnMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV2XrayClientLinksDownloadByCnMutationOptions(options), queryClient);
    }
    export const getApiV2XrayClientLinksHealthcheck = (

 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiSystemString>(
      {url: `/api/v2/xray-client-links/healthcheck`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV2XrayClientLinksHealthcheckQueryKey = () => {
    return [
    `/api/v2/xray-client-links/healthcheck`
    ] as const;
    }


export const getGetApiV2XrayClientLinksHealthcheckQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheck>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheck>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2XrayClientLinksHealthcheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheck>>> = ({ signal }) => getApiV2XrayClientLinksHealthcheck(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheck>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2XrayClientLinksHealthcheckQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheck>>>
export type GetApiV2XrayClientLinksHealthcheckQueryError = unknown


export function useGetApiV2XrayClientLinksHealthcheck<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheck>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheck>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksHealthcheck<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheck>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksHealthcheck<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheck>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2XrayClientLinksHealthcheck<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheck>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2XrayClientLinksHealthcheckQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getApiV2XrayClientLinksHealthcheckWithJwt = (

 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiSystemString>(
      {url: `/api/v2/xray-client-links/healthcheck-with-jwt`, method: 'GET', signal
    },
      options);
    }




export const getGetApiV2XrayClientLinksHealthcheckWithJwtQueryKey = () => {
    return [
    `/api/v2/xray-client-links/healthcheck-with-jwt`
    ] as const;
    }


export const getGetApiV2XrayClientLinksHealthcheckWithJwtQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheckWithJwt>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheckWithJwt>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2XrayClientLinksHealthcheckWithJwtQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheckWithJwt>>> = ({ signal }) => getApiV2XrayClientLinksHealthcheckWithJwt(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheckWithJwt>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2XrayClientLinksHealthcheckWithJwtQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheckWithJwt>>>
export type GetApiV2XrayClientLinksHealthcheckWithJwtQueryError = unknown


export function useGetApiV2XrayClientLinksHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheckWithJwt>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheckWithJwt>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheckWithJwt>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheckWithJwt>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheckWithJwt>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheckWithJwt>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheckWithJwt>>,
          TError,
          Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheckWithJwt>>
        > , 'initialData'
      >, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2XrayClientLinksHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheckWithJwt>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheckWithJwt>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2XrayClientLinksHealthcheckWithJwt<TData = Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheckWithJwt>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2XrayClientLinksHealthcheckWithJwt>>, TError, TData>>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2XrayClientLinksHealthcheckWithJwtQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const postApiV2XrayClientLinksRevoke = (
    xrayClientLinksRequestsRevokeXrayClientLinkRequest?: XrayClientLinksRequestsRevokeXrayClientLinkRequest,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiXrayClientLinksResponsesXrayClientLinkResponse>(
      {url: `/api/v2/xray-client-links/revoke`, method: 'POST',
      headers: {'Content-Type': 'application/json-patch+json', },
      data: xrayClientLinksRequestsRevokeXrayClientLinkRequest, signal
    },
      options);
    }




export const getPostApiV2XrayClientLinksRevokeMutationKey = () => ['postApiV2XrayClientLinksRevoke'] as const;

export const getPostApiV2XrayClientLinksRevokeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinksRevoke>>, TError,PostApiV2XrayClientLinksRevokeMutationVariables, TContext>, request?: SecondParameter<typeof ogmMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinksRevoke>>, TError,PostApiV2XrayClientLinksRevokeMutationVariables, TContext> => {

const mutationKey = getPostApiV2XrayClientLinksRevokeMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV2XrayClientLinksRevoke>>, PostApiV2XrayClientLinksRevokeMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiV2XrayClientLinksRevoke(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV2XrayClientLinksRevokeMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV2XrayClientLinksRevoke>>>
    export type PostApiV2XrayClientLinksRevokeMutationBody = XrayClientLinksRequestsRevokeXrayClientLinkRequest | undefined
    export type PostApiV2XrayClientLinksRevokeMutationError = unknown
    export type PostApiV2XrayClientLinksRevokeMutationVariables = {data?: XrayClientLinksRequestsRevokeXrayClientLinkRequest}

    export const usePostApiV2XrayClientLinksRevoke = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinksRevoke>>, TError,PostApiV2XrayClientLinksRevokeMutationVariables, TContext>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV2XrayClientLinksRevoke>>,
        TError,
        PostApiV2XrayClientLinksRevokeMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV2XrayClientLinksRevokeMutationOptions(options), queryClient);
    }
    export const postApiV2XrayClientLinksWithToken = (
    xrayClientLinksRequestsAddXrayClientLinkRequest?: XrayClientLinksRequestsAddXrayClientLinkRequest,
 options?: SecondParameter<typeof ogmMutator>,signal?: AbortSignal
) => {


      return ogmMutator<ApiXrayClientLinksResponsesXrayClientLinkWithTokenResponse>(
      {url: `/api/v2/xray-client-links/with-token`, method: 'POST',
      headers: {'Content-Type': 'application/json-patch+json', },
      data: xrayClientLinksRequestsAddXrayClientLinkRequest, signal
    },
      options);
    }




export const getPostApiV2XrayClientLinksWithTokenMutationKey = () => ['postApiV2XrayClientLinksWithToken'] as const;

export const getPostApiV2XrayClientLinksWithTokenMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinksWithToken>>, TError,PostApiV2XrayClientLinksWithTokenMutationVariables, TContext>, request?: SecondParameter<typeof ogmMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinksWithToken>>, TError,PostApiV2XrayClientLinksWithTokenMutationVariables, TContext> => {

const mutationKey = getPostApiV2XrayClientLinksWithTokenMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV2XrayClientLinksWithToken>>, PostApiV2XrayClientLinksWithTokenMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiV2XrayClientLinksWithToken(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiV2XrayClientLinksWithTokenMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV2XrayClientLinksWithToken>>>
    export type PostApiV2XrayClientLinksWithTokenMutationBody = XrayClientLinksRequestsAddXrayClientLinkRequest | undefined
    export type PostApiV2XrayClientLinksWithTokenMutationError = unknown
    export type PostApiV2XrayClientLinksWithTokenMutationVariables = {data?: XrayClientLinksRequestsAddXrayClientLinkRequest}

    export const usePostApiV2XrayClientLinksWithToken = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV2XrayClientLinksWithToken>>, TError,PostApiV2XrayClientLinksWithTokenMutationVariables, TContext>, request?: SecondParameter<typeof ogmMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV2XrayClientLinksWithToken>>,
        TError,
        PostApiV2XrayClientLinksWithTokenMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiV2XrayClientLinksWithTokenMutationOptions(options), queryClient);
    }
