/**
 * OpenVPN Management Interface commands.
 * Based on: https://openvpn.net/community-docs/management-interface.html
 */
export const OVP_MGMT_COMMANDS: { name: string; hint?: string }[] = [
  { name: "status", hint: "[n] - Show daemon status (format #n)" },
  { name: "status 3", hint: "Status with format version 3" },
  { name: "help", hint: "Print command list" },
  { name: "state", hint: "[on|off] [N|all] - Show state history" },
  { name: "log", hint: "[on|off] [N|all] - Log messages" },
  { name: "log on all", hint: "Show history + real-time log" },
  { name: "log off", hint: "Turn off log" },
  { name: "bytecount", hint: "n - Bandwidth every n secs, 0=off" },
  { name: "echo", hint: "[on|off] [N|all] - Echo messages" },
  { name: "hold", hint: "[on|off|release] - Hold flag" },
  { name: "hold release", hint: "Release hold and start" },
  { name: "kill", hint: "cn|IP:port - Kill client" },
  { name: "mute", hint: "[n] - Set mute level" },
  { name: "verb", hint: "[n] - Set verbosity 0-15" },
  { name: "version", hint: "[n] - Show version" },
  { name: "exit", hint: "Close management session" },
  { name: "quit", hint: "Close management session" },
  { name: "password", hint: "type p - Enter password" },
  { name: "username", hint: "type u - Enter username" },
  { name: "forget-passwords", hint: "Forget entered passwords" },
  { name: "signal", hint: "SIGHUP|SIGTERM|SIGUSR1|SIGUSR2" },
  { name: "auth-retry", hint: "t - none|interact|nointeract" },
  { name: "needok", hint: "type action - Confirm NEED-OK" },
  { name: "needstr", hint: "type action - Confirm NEED-STR" },
  { name: "client-auth", hint: "CID KID - Auth client (multiline)" },
  { name: "client-auth-nt", hint: "CID KID - Auth client" },
  { name: "client-deny", hint: "CID KID reason [client-reason]" },
  { name: "client-kill", hint: "CID [M] - Kill client" },
  { name: "client-pf", hint: "CID - Push packet filter" },
  { name: "remote", hint: "ACCEPT|MOD|SKIP [host port]" },
  { name: "proxy", hint: "TYPE HOST PORT [nct]" },
  { name: "load-stats", hint: "Show server load stats" },
  { name: "pid", hint: "Show process ID" },
];
