/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenVPN Gate Monitor API
 * OpenAPI spec version: v1
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AverageSessionDurationsResponseApiResponse,
  GeoConnectionsResponseApiResponse,
  StringApiResponse,
  TrafficByClientsResponseApiResponse,
} from ".././model";

import { ogmMutator } from "../../mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getApiOpenVpnStatisticsGetVpnServerId = (
  vpnServerId: number,
  options?: SecondParameter<typeof ogmMutator>,
  signal?: AbortSignal,
) => {
  return ogmMutator<TrafficByClientsResponseApiResponse>(
    {
      url: `/api/open-vpn-statistics/get/${vpnServerId}`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getGetApiOpenVpnStatisticsGetVpnServerIdQueryKey = (
  vpnServerId?: number,
) => {
  return [`/api/open-vpn-statistics/get/${vpnServerId}`] as const;
};

export const getGetApiOpenVpnStatisticsGetVpnServerIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiOpenVpnStatisticsGetVpnServerId>>,
  TError = unknown,
>(
  vpnServerId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnStatisticsGetVpnServerId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetApiOpenVpnStatisticsGetVpnServerIdQueryKey(vpnServerId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiOpenVpnStatisticsGetVpnServerId>>
  > = ({ signal }) =>
    getApiOpenVpnStatisticsGetVpnServerId(vpnServerId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!vpnServerId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiOpenVpnStatisticsGetVpnServerId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiOpenVpnStatisticsGetVpnServerIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiOpenVpnStatisticsGetVpnServerId>>
>;
export type GetApiOpenVpnStatisticsGetVpnServerIdQueryError = unknown;

export function useGetApiOpenVpnStatisticsGetVpnServerId<
  TData = Awaited<ReturnType<typeof getApiOpenVpnStatisticsGetVpnServerId>>,
  TError = unknown,
>(
  vpnServerId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnStatisticsGetVpnServerId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnStatisticsGetVpnServerId>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnStatisticsGetVpnServerId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnStatisticsGetVpnServerId<
  TData = Awaited<ReturnType<typeof getApiOpenVpnStatisticsGetVpnServerId>>,
  TError = unknown,
>(
  vpnServerId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnStatisticsGetVpnServerId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnStatisticsGetVpnServerId>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnStatisticsGetVpnServerId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnStatisticsGetVpnServerId<
  TData = Awaited<ReturnType<typeof getApiOpenVpnStatisticsGetVpnServerId>>,
  TError = unknown,
>(
  vpnServerId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnStatisticsGetVpnServerId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiOpenVpnStatisticsGetVpnServerId<
  TData = Awaited<ReturnType<typeof getApiOpenVpnStatisticsGetVpnServerId>>,
  TError = unknown,
>(
  vpnServerId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnStatisticsGetVpnServerId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiOpenVpnStatisticsGetVpnServerIdQueryOptions(
    vpnServerId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiOpenVpnStatisticsGetConnectionsByLocationVpnServerId = (
  vpnServerId: number,
  options?: SecondParameter<typeof ogmMutator>,
  signal?: AbortSignal,
) => {
  return ogmMutator<GeoConnectionsResponseApiResponse>(
    {
      url: `/api/open-vpn-statistics/get-connections-by-location/${vpnServerId}`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getGetApiOpenVpnStatisticsGetConnectionsByLocationVpnServerIdQueryKey =
  (vpnServerId?: number) => {
    return [
      `/api/open-vpn-statistics/get-connections-by-location/${vpnServerId}`,
    ] as const;
  };

export const getGetApiOpenVpnStatisticsGetConnectionsByLocationVpnServerIdQueryOptions =
  <
    TData = Awaited<
      ReturnType<
        typeof getApiOpenVpnStatisticsGetConnectionsByLocationVpnServerId
      >
    >,
    TError = unknown,
  >(
    vpnServerId: number,
    options?: {
      query?: Partial<
        UseQueryOptions<
          Awaited<
            ReturnType<
              typeof getApiOpenVpnStatisticsGetConnectionsByLocationVpnServerId
            >
          >,
          TError,
          TData
        >
      >;
      request?: SecondParameter<typeof ogmMutator>;
    },
  ) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
      queryOptions?.queryKey ??
      getGetApiOpenVpnStatisticsGetConnectionsByLocationVpnServerIdQueryKey(
        vpnServerId,
      );

    const queryFn: QueryFunction<
      Awaited<
        ReturnType<
          typeof getApiOpenVpnStatisticsGetConnectionsByLocationVpnServerId
        >
      >
    > = ({ signal }) =>
      getApiOpenVpnStatisticsGetConnectionsByLocationVpnServerId(
        vpnServerId,
        requestOptions,
        signal,
      );

    return {
      queryKey,
      queryFn,
      enabled: !!vpnServerId,
      ...queryOptions,
    } as UseQueryOptions<
      Awaited<
        ReturnType<
          typeof getApiOpenVpnStatisticsGetConnectionsByLocationVpnServerId
        >
      >,
      TError,
      TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
  };

export type GetApiOpenVpnStatisticsGetConnectionsByLocationVpnServerIdQueryResult =
  NonNullable<
    Awaited<
      ReturnType<
        typeof getApiOpenVpnStatisticsGetConnectionsByLocationVpnServerId
      >
    >
  >;
export type GetApiOpenVpnStatisticsGetConnectionsByLocationVpnServerIdQueryError =
  unknown;

export function useGetApiOpenVpnStatisticsGetConnectionsByLocationVpnServerId<
  TData = Awaited<
    ReturnType<
      typeof getApiOpenVpnStatisticsGetConnectionsByLocationVpnServerId
    >
  >,
  TError = unknown,
>(
  vpnServerId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof getApiOpenVpnStatisticsGetConnectionsByLocationVpnServerId
          >
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<
              typeof getApiOpenVpnStatisticsGetConnectionsByLocationVpnServerId
            >
          >,
          TError,
          Awaited<
            ReturnType<
              typeof getApiOpenVpnStatisticsGetConnectionsByLocationVpnServerId
            >
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnStatisticsGetConnectionsByLocationVpnServerId<
  TData = Awaited<
    ReturnType<
      typeof getApiOpenVpnStatisticsGetConnectionsByLocationVpnServerId
    >
  >,
  TError = unknown,
>(
  vpnServerId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof getApiOpenVpnStatisticsGetConnectionsByLocationVpnServerId
          >
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<
              typeof getApiOpenVpnStatisticsGetConnectionsByLocationVpnServerId
            >
          >,
          TError,
          Awaited<
            ReturnType<
              typeof getApiOpenVpnStatisticsGetConnectionsByLocationVpnServerId
            >
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnStatisticsGetConnectionsByLocationVpnServerId<
  TData = Awaited<
    ReturnType<
      typeof getApiOpenVpnStatisticsGetConnectionsByLocationVpnServerId
    >
  >,
  TError = unknown,
>(
  vpnServerId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof getApiOpenVpnStatisticsGetConnectionsByLocationVpnServerId
          >
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiOpenVpnStatisticsGetConnectionsByLocationVpnServerId<
  TData = Awaited<
    ReturnType<
      typeof getApiOpenVpnStatisticsGetConnectionsByLocationVpnServerId
    >
  >,
  TError = unknown,
>(
  vpnServerId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof getApiOpenVpnStatisticsGetConnectionsByLocationVpnServerId
          >
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetApiOpenVpnStatisticsGetConnectionsByLocationVpnServerIdQueryOptions(
      vpnServerId,
      options,
    );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiOpenVpnStatisticsGetAverageSessionDurationVpnServerId = (
  vpnServerId: number,
  options?: SecondParameter<typeof ogmMutator>,
  signal?: AbortSignal,
) => {
  return ogmMutator<AverageSessionDurationsResponseApiResponse>(
    {
      url: `/api/open-vpn-statistics/get-average-session-duration/${vpnServerId}`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getGetApiOpenVpnStatisticsGetAverageSessionDurationVpnServerIdQueryKey =
  (vpnServerId?: number) => {
    return [
      `/api/open-vpn-statistics/get-average-session-duration/${vpnServerId}`,
    ] as const;
  };

export const getGetApiOpenVpnStatisticsGetAverageSessionDurationVpnServerIdQueryOptions =
  <
    TData = Awaited<
      ReturnType<
        typeof getApiOpenVpnStatisticsGetAverageSessionDurationVpnServerId
      >
    >,
    TError = unknown,
  >(
    vpnServerId: number,
    options?: {
      query?: Partial<
        UseQueryOptions<
          Awaited<
            ReturnType<
              typeof getApiOpenVpnStatisticsGetAverageSessionDurationVpnServerId
            >
          >,
          TError,
          TData
        >
      >;
      request?: SecondParameter<typeof ogmMutator>;
    },
  ) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
      queryOptions?.queryKey ??
      getGetApiOpenVpnStatisticsGetAverageSessionDurationVpnServerIdQueryKey(
        vpnServerId,
      );

    const queryFn: QueryFunction<
      Awaited<
        ReturnType<
          typeof getApiOpenVpnStatisticsGetAverageSessionDurationVpnServerId
        >
      >
    > = ({ signal }) =>
      getApiOpenVpnStatisticsGetAverageSessionDurationVpnServerId(
        vpnServerId,
        requestOptions,
        signal,
      );

    return {
      queryKey,
      queryFn,
      enabled: !!vpnServerId,
      ...queryOptions,
    } as UseQueryOptions<
      Awaited<
        ReturnType<
          typeof getApiOpenVpnStatisticsGetAverageSessionDurationVpnServerId
        >
      >,
      TError,
      TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
  };

export type GetApiOpenVpnStatisticsGetAverageSessionDurationVpnServerIdQueryResult =
  NonNullable<
    Awaited<
      ReturnType<
        typeof getApiOpenVpnStatisticsGetAverageSessionDurationVpnServerId
      >
    >
  >;
export type GetApiOpenVpnStatisticsGetAverageSessionDurationVpnServerIdQueryError =
  unknown;

export function useGetApiOpenVpnStatisticsGetAverageSessionDurationVpnServerId<
  TData = Awaited<
    ReturnType<
      typeof getApiOpenVpnStatisticsGetAverageSessionDurationVpnServerId
    >
  >,
  TError = unknown,
>(
  vpnServerId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof getApiOpenVpnStatisticsGetAverageSessionDurationVpnServerId
          >
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<
              typeof getApiOpenVpnStatisticsGetAverageSessionDurationVpnServerId
            >
          >,
          TError,
          Awaited<
            ReturnType<
              typeof getApiOpenVpnStatisticsGetAverageSessionDurationVpnServerId
            >
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnStatisticsGetAverageSessionDurationVpnServerId<
  TData = Awaited<
    ReturnType<
      typeof getApiOpenVpnStatisticsGetAverageSessionDurationVpnServerId
    >
  >,
  TError = unknown,
>(
  vpnServerId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof getApiOpenVpnStatisticsGetAverageSessionDurationVpnServerId
          >
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<
              typeof getApiOpenVpnStatisticsGetAverageSessionDurationVpnServerId
            >
          >,
          TError,
          Awaited<
            ReturnType<
              typeof getApiOpenVpnStatisticsGetAverageSessionDurationVpnServerId
            >
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnStatisticsGetAverageSessionDurationVpnServerId<
  TData = Awaited<
    ReturnType<
      typeof getApiOpenVpnStatisticsGetAverageSessionDurationVpnServerId
    >
  >,
  TError = unknown,
>(
  vpnServerId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof getApiOpenVpnStatisticsGetAverageSessionDurationVpnServerId
          >
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiOpenVpnStatisticsGetAverageSessionDurationVpnServerId<
  TData = Awaited<
    ReturnType<
      typeof getApiOpenVpnStatisticsGetAverageSessionDurationVpnServerId
    >
  >,
  TError = unknown,
>(
  vpnServerId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof getApiOpenVpnStatisticsGetAverageSessionDurationVpnServerId
          >
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetApiOpenVpnStatisticsGetAverageSessionDurationVpnServerIdQueryOptions(
      vpnServerId,
      options,
    );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiOpenVpnStatisticsHealthcheck = (
  options?: SecondParameter<typeof ogmMutator>,
  signal?: AbortSignal,
) => {
  return ogmMutator<StringApiResponse>(
    { url: `/api/open-vpn-statistics/healthcheck`, method: "GET", signal },
    options,
  );
};

export const getGetApiOpenVpnStatisticsHealthcheckQueryKey = () => {
  return [`/api/open-vpn-statistics/healthcheck`] as const;
};

export const getGetApiOpenVpnStatisticsHealthcheckQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheck>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheck>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof ogmMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiOpenVpnStatisticsHealthcheckQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheck>>
  > = ({ signal }) =>
    getApiOpenVpnStatisticsHealthcheck(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheck>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiOpenVpnStatisticsHealthcheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheck>>
>;
export type GetApiOpenVpnStatisticsHealthcheckQueryError = unknown;

export function useGetApiOpenVpnStatisticsHealthcheck<
  TData = Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheck>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheck>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheck>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnStatisticsHealthcheck<
  TData = Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheck>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheck>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheck>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnStatisticsHealthcheck<
  TData = Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheck>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiOpenVpnStatisticsHealthcheck<
  TData = Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheck>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheck>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetApiOpenVpnStatisticsHealthcheckQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiOpenVpnStatisticsHealthcheckWithJwt = (
  options?: SecondParameter<typeof ogmMutator>,
  signal?: AbortSignal,
) => {
  return ogmMutator<StringApiResponse>(
    {
      url: `/api/open-vpn-statistics/healthcheck-with-jwt`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getGetApiOpenVpnStatisticsHealthcheckWithJwtQueryKey = () => {
  return [`/api/open-vpn-statistics/healthcheck-with-jwt`] as const;
};

export const getGetApiOpenVpnStatisticsHealthcheckWithJwtQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheckWithJwt>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheckWithJwt>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof ogmMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetApiOpenVpnStatisticsHealthcheckWithJwtQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheckWithJwt>>
  > = ({ signal }) =>
    getApiOpenVpnStatisticsHealthcheckWithJwt(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheckWithJwt>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiOpenVpnStatisticsHealthcheckWithJwtQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheckWithJwt>>
>;
export type GetApiOpenVpnStatisticsHealthcheckWithJwtQueryError = unknown;

export function useGetApiOpenVpnStatisticsHealthcheckWithJwt<
  TData = Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheckWithJwt>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheckWithJwt>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheckWithJwt>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheckWithJwt>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnStatisticsHealthcheckWithJwt<
  TData = Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheckWithJwt>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheckWithJwt>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheckWithJwt>>,
          TError,
          Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheckWithJwt>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiOpenVpnStatisticsHealthcheckWithJwt<
  TData = Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheckWithJwt>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheckWithJwt>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetApiOpenVpnStatisticsHealthcheckWithJwt<
  TData = Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheckWithJwt>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiOpenVpnStatisticsHealthcheckWithJwt>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof ogmMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetApiOpenVpnStatisticsHealthcheckWithJwtQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
